lib/media/localmedia.js

Because `LocalMedia#removeTrack()` is [simply calling `Media#_removeTrack()`](https://github.com/twilio/twilio-conversations.js/blob/7259a9b4066a63c2c12890f5b75910cc72fdd565/lib/media/localmedia.js#L69-L78), it doesn't properly stop and remove the track from the media stream, as is being done correctly in `LocalMedia#_removeTrack()`.
My suggestion is to remove the current definition of `LocalMedia#removeTrack()`, and replace it with the current definition of `LocalMedia#_removeTrack()`, [which overrides the underlying `Media#_removeTrack()` properly](https://github.com/twilio/twilio-conversations.js/blob/7259a9b4066a63c2c12890f5b75910cc72fdd565/lib/media/localmedia.js#L208-L220). This will by side-affect fix the behavior of `LocalMedia#removeStream()`, which calls into the current broken …

LocalMedia#removeStream() and LocalMedia#removeTrack() do not properly stop and remove tracks

---

lib/signaling/sipjsdialog.js
lib/signaling/sipjsmediahandler.js
package.json

@ryan-rowland mind taking a look? This PR updates twilio-conversations.js to use Twilio's fork of SIP.js 0.7.3. There are some new required methods on MediaHandler instances, and the
`getAllowedMethods` function has gone away from the top-level SIP.js object.

Update SIPJSDialog and SIPJSMediaHandler for SIP.js 0.7.3

---

lib/signaling/v2/conversation.js

The `conversationInfo` function is shadowed by the `conversationInfo` parameter which results in a SyntaxError.

rename function to prevent a `strict mode` error

---

package.json

(This shows up as a broken link on the npm page for twilio-video)

Fix link to git repo

---

test/framework/index.js
test/framework/options.js
test/framework/twilio-video-meteor.json
test/framework/twilio-video-no-framework/app.js
test/framework/waitforserver.js

@manjeshbhargav this PR adds
* Per-Framework Test timeouts (since we've since Meteor can take much longer),
* Waits between HTTP OPTIONS checks (in case we are spamming the server and slowing down its startup), and
* Prints stdout from the Framework Test "start" command (so that we can see if something is going wrong).

wait after OPTIONS check; add per-Framework timeouts

---

package.json

@markandrus ,
Newer versions of chromedriver require Chrome 55 or higher. So restricting chromedriver's version to 2.26.1

chromedriver dependency should resolve to the exact version.

---

lib/connect.js
lib/localparticipant.js
test/unit/spec/connect.js
test/unit/spec/localparticipant.js

@manjeshbhargav @ryan-rowland This behavior got lost in the transition from 1.0.0-beta4 to 1.0.0-beta5. This commit adds it back with some unit tests to prevent future regression. See [here](https://github.com/twilio/twilio-video.js/blob/1.0.0-beta4/lib/room.js#L302) how it worked before. Should fix #75.

Stop LocalTracks on disconnect

---

.travis.yml

@manjeshbhargav travis-multirunner's `setup.sh` drops a Firefox tar.bz2 as well as the `browsers/` directory in wherever it is called from. This causes problems with our release-tool script for publishing to NPM. This change simply cds into `node_modules/travis-multirunner` before calling the `setup.sh` script (that way we don't pollute the working directory).

Setup travis-multirunner under node_modules

---

CHANGELOG.md
lib/media/track/index.js

Currently, in Chrome, it appears that an HTMLMediaElement's `srcObject` setter takes a "snapshot" of the MediaStream's MediaStreamTracks at the time at which it is set. This means, calls to `removeTrack` don't effect playback. Stranger, if a MediaStreamTrack is removed from the `srcObject`, and then the HTMLMediaElement is detached from the DOM, audio playback will continue. This bug is captured [here](https://bugs.chromium.org/p/chromium/issues/detail?id=749928).
A sufficient workaround is to reset the `srcObject` attribute after making changes to the MediaStream. So this PR introduces that change to `detach`. It's worth mentioning that this `srcObject` behavior also effects _adding_ MediaStreamTracks to a `srcObject`, as reported …

Fix detach behavior in Chrome (and Safari 11 Tech Preview)

---

CHANGELOG.md
karma/makeconf.js
lib/connect.js
lib/createlocaltracks.js
lib/util/index.js
lib/util/log.js
lib/util/sdp.js
lib/util/trackmatcher.js
lib/webrtc/rtcpeerconnection/index.js
lib/webrtc/rtcpeerconnection/safari.js
lib/webrtc/rtcsessiondescription/index.js
package.json
test/integration/spec/localparticipant.js
test/integration/spec/localtracks.js
test/integration/spec/webrtc/rtcpeerconnection.js
test/integration/spec/webrtc/rtcsessiondescription.js
test/lib/sdp.js
test/unit/index.js
test/unit/spec/util/log.js
test/unit/spec/util/trackmatcher.js

_Not ready to merge._
This adds a SafariRTCPeerConnection wrapper to handle Safari 11 Tech Preview quirks. Currently, this PR only passes the WebRTC tests we have. You can check this with
```
BROWSER=safari npm run test:webrtc
```
Integration tests are currently hanging. I'll need to investigate that next.

Support Safari 11

---

CHANGELOG.md
COMMON_ISSUES.md
lib/connect.js
lib/signaling/v2/peerconnection.js
lib/signaling/v2/peerconnectionmanager.js
lib/webaudio/audiocontext.js
test/integration/spec/localtracks.js
test/unit/index.js
test/unit/spec/signaling/v2/peerconnectionmanager.js
test/unit/spec/webaudio/audiocontext.js

@manjeshbhargav would you take a look? As you mentioned earlier, the "dummy" MediaStreamTrack shows up in `getStats`. We'll need to fix that before releasing; however, Deniss also mentioned seeing the dummy MediaStreamTrack in recordings, too. There may be some more work to do here, so here is my proposal: leave this in, but disabled. We can iterate on it in future sprints and try, e.g., filtering the MSID from the SDP, filtering the result of `getStats`, etc. Would like to get these in for 1.2.1-rc2.

1.2.1-rc1 Fixes

---

package.json

@manjeshbhargav with the new Group Rooms deploy, we're actually checking SDPs on the backend, so our "fake SDPs" we've been sending around in our Node-based integration tests won't work anymore. Since we already re-run these same tests as part of our browser-based integration tests, I think we can disable the Node-based ones.

Disable Node integration tests

---

CHANGELOG.md
lib/media/track/index.js
test/unit/spec/media/track/index.js

@manjeshbhargav @ryan-rowland mind taking a look? I just tested with my iPhone and it looks good.

Safari 11 on iOS support: set playsInline to true

---

test/integration/spec/localtracks.js

@manjeshbhargav 
***
We already skip this test for Safari and Firefox. Now, with the introduction of Chrome 62, we should remove the test entirely (and possibly land a unit test for it later). The test relied on `MediaStreamTrack#stop` raising the "ended" event on the MediaStreamTrack; but, according to
[Media Capture and Streams](https://www.w3.org/TR/mediacapture-streams), this event is only raised if "a MediaStreamTrack _track_ ends for any reason other than the `stop()` method being invoked."
This was fixed in Chrome 62 via [Issue 752913](https://bugs.chromium.org/p/chromium/issues/detail?id=752913).

Remove invalid LocalAudioTrack/LocalVideoTrack test

---

CHANGELOG.md
lib/connect.js
lib/createlocaltrack.js
lib/createlocaltracks.js
lib/localparticipant.js

@manjeshbhargav mind taking a look? I also combed through some of the `@example`s and
* Where the Room `name` deviated, standardized on "my-cool-room".
* Used "microphone" and "camera" for the LocalAudioTrack and LocalVideoTrack names.
My feeling is we should be prescriptive in the names, here. It also lets us standardize on future language we might use (for example, the `name` "screenshare") when we update the screensharing guide. ~~We might also want to fix https://github.com/twilio/twilio-video.js/issues/184 for this release since it looks pretty small.~~ EDIT: Actually, looks like that is now in twilio-webrtc.js.

Update CHANGELOG.md for 1.5.0

---

lib/signaling/v2/peerconnection.js

@manjeshbhargav please take a look. Fix for https://bugzilla.mozilla.org/show_bug.cgi?id=1405893. The `filter` should not really be necessary in spec-compliant implementations, but there _was_ [this bug](https://bugs.chromium.org/p/chromium/issues/detail?id=751785), so perhaps worth keeping the check?

Use RTCRtpReceivers where available

---

lib/media/track/localdatatrack.js

@manjeshbhargav not quite sure about this example--it's rather large, but seems like we really want to explain both halves (local and remote).

Add LocalDataTrack example to JSDoc

---

lib/connect.js
lib/util/index.js
test/unit/spec/connect.js

@markandrus ,
We now remove any keys in `ConnectOptions` that are explicitly set to `undefined`. That way,
in this specific bug, `wsServer` is properly constructed.

JSDK-1579 Removing options items which are explicitly "undefined".

---

lib/signaling/v2/peerconnection.js
test/integration/spec/localparticipant.js

@markandrus 
In some places we were passing `RTCSessionDescription` to `._setLocalDescription`, where we were trying to apply the sdp transform for simulcast. So this PR now passes only the `RTCSessionDescriptionInitDict`.

JSDK-1626 Should always pass SDP dict to ._setLocalDescription()

---

lib/data/receiver.js
test/integration/spec/localparticipant.js

@markandrus In Firefox, The `DataTrackReceiver`'s `RTCDataChannel` has it's `.binaryType` set to "blob", where as in Chrome/Safari it is set to "arraybuffer". So we explicitly set it.

JSDK-1627 Set DataTrackReceiver's RTCDataChannel .binaryType to "arraybuffer"

---

package.json

3.3.1 also contains a fix for a DOS attack for ws servers that most packages will be updating to. Keeping twilio-video.js on 2.x forces consumers to duplicate packages

Update ws package to 3.x

---

lib/util/sdp/index.js
test/integration/spec/connect.js

Porting this forward from https://github.com/twilio/twilio-video.js/pull/225

Allow PCMU/PCMA rtpmap entries to be missing

---

CHANGELOG.md
lib/signaling/v2/peerconnection.js
test/unit/spec/signaling/v2/peerconnection.js

PeerConnectionV2 had a bug that I noticed when testing Firefox Stable/Beta to Firefox Stable/Beta. The bug is this: in order to decide whether to renegotiate, we always check if the current offer (local _or_ remote) contains at least as many media sections with directions "sendrecv" or "recvonly" as RTCRtpSenders we have (taking into account kind).
However, this doesn't work in the local case with Firefox Stable/Beta. Consider if we have two local audio tracks, we've been offered one remote audio track in a previous round of negotiation, and now we call `createOffer`:
* We have two RTCRtpSenders (one for each of our two local audio tracks)
* We have two m=sections, one with "a=sendrecv" and one with "a=sendonly"
But our check is for "sendrecv" or "recvonly", and so our logic would say to …

Fix negotiation loop in Firefox

---

CHANGELOG.md
lib/media/track/remotetrackpublication.js
lib/participant.js
lib/remoteparticipant.js
lib/room.js
lib/signaling/remotetrack.js
lib/signaling/v2/room.js
test/unit/spec/remoteparticipant.js
test/unit/spec/room.js
test/unit/spec/signaling/v2/room.js

_Not ready to merge._
The point of this PR is to allow raising "trackSubscriptionFailed" events in the event that, for example,
1. A VP8-only Participant connects to a Group Room that supports VP8 and H.264.
2. An H.264-only Participant connects to the same Group Room and publishes a VideoTrack.
Once Step 2 occurs, we want the VP8-only Participant to learn that there was a VideoTrack they ought to have subscribed to, but couldn't, because they didn't support the required codec.

JSDK-1599: Track subscription errors

---

lib/signaling/v2/localparticipant.js
lib/signaling/v2/room.js
test/unit/index.js
test/unit/spec/signaling/v2/localparticipant.js
test/unit/spec/signaling/v2/room.js

@manjeshbhargav previously, RoomV2 was managing LocalParticipantV2's `revision`, which we identified as being weird. Now, LocalParticipantV2 manages it in response to
* Tracks being added,
* Tracks being removed, and
* Added Tracks changing (except for SID assignment).
Basically, I just moved the logic from lib/signaling/v2/room.js into lib/signaling/v2/localparticipant.js.
I still need to find a way to test the `revision` re-use bug when enabling/disabling a Track early when connecting to a Room.

Move LocalParticipantV2 revision management out of RoomV2

---

lib/connect.js
lib/iceserversource/nts.js

The current default in twilio-video.js is to wait 3 s for ICE servers (STUN and TURN). If this takes longer than 3 s, twilio-video.js proceeds with hard-coded STUN servers. On some networks, 3 s is too short a timeout. So now it can be extended, e.g.
```js
connect(token, {
iceServersTimeout: 10 * 1000 // ms
});
```
will wait 10 s. Additionally, on some networks, connecting to a Room isn't going to work at all without TURN servers. So there is a new option, `abortIfIceServersTimeout`, that allows failing the `connect` call, e.g.
```js
try {
await connect(token, {
abortIfIceServersTimeout: true,
iceServersTimeout: 10 * 1000 // ms
})
} catch (error) {
switch (error.code) {
case 53500: // ConfigurationAcquireFailedError
console.error('It took too long to get ICE servers! Check any HTTP …
```

JSDK-1796: Add iceServersTimeout and abortIfIceServersTimeout to ConnectOptions

---

CHANGELOG.md
bower.json
lib/connect.js
lib/iceserversource/nts.js
package.json

@manjeshbhargav it was suggested we rename `abortIfIceServersTimeout` to `abortOnIceServersTimeout`. Also, since this is a new feature, we'll need to bump the minor version.

Prepare for 1.9.0

---

CHANGELOG.md
lib/signaling/v2/peerconnection.js
test/unit/spec/signaling/v2/peerconnection.js

If an ICE failure occurs (i.e., an individual RTCPeerConnection's `iceConnectionState` transitions to "failed"), we now perform an ICE restart. Subsequent offers from the Client will block until the ICE restart has completed (not unlike what we do in the initial round of negotiation with the `_needsInitialAnswer` boolean); however, glare will still force the Client to rollback, apply the Server's answer, and then restart ICE (with yet another unique set of ICE credentials).

JSDK-1810: Add support for ICE restart

---

lib/room.js
lib/signaling/v2/peerconnection.js
lib/signaling/v2/peerconnectionmanager.js
lib/signaling/v2/room.js
lib/stats/statsreport.js
package.json
test/unit/spec/signaling/v2/room.js

@markandrus For now, the active ICE candidate pair will be behind a private property `._activeIceCandidatePair` of `StatsReport`. Once we decide to implement the IDL spec, we will
then make this property public.

JSDK-1228 Publish ICE candidate pair stats to Insights.

---

CHANGELOG.md
lib/stats/trackstats.js
test/unit/spec/signaling/v2/room.js

https://github.com/twilio/twilio-video.js/pull/302 started sending `trackSid` to insights, but this PR adds it to the public API.

Add TrackSid to TrackStats public API

---

lib/localparticipant.js
lib/media/track/sender.js
lib/room.js
lib/signaling/localparticipant.js
lib/signaling/localtrackpublication.js
lib/signaling/participant.js
lib/signaling/v2/localparticipant.js
test/integration/spec/connect.js
test/lib/fakemediastream.js
test/unit/spec/localparticipant.js
test/unit/spec/media/track/sender.js
test/unit/spec/signaling/v2/localparticipant.js
test/unit/spec/signaling/v2/localtrackpublication.js
test/unit/spec/signaling/v2/remoteparticipant.js

_This is a breaking API change, so we will not merge it until we have a plan for releasing 2.0.0._
__Why make this change?__
Whenever a LocalAudioTrack or LocalVideoTrack is published to a Room, we're going to clone the underlying MediaStreamTrack. This will ensure we're always signaling a unique MSID in SDPs and a unique Track ID in our signaling messages. Our signaling protocol doesn't work well if the same LocalAudioTrack or LocalVideoTrack is 1. published, unpublished, and then published, and 2. these messages cross on the wire. This should also let us work around issues like WebKit [Bug 174327](https://bugs.webkit.org/show_bug.cgi?id=174327).
__Why is it a breaking API change?__
Although we consider Track IDs "deprecated" in favor of Track Names or Track SIDs ([since …

JSDK-1912: Implement MediaStreamTrack cloning

---

lib/media/track/mediatrack.js
lib/media/track/remotemediatrack.js
lib/room.js
test/unit/spec/media/track/remotemediatrack.js
test/unit/spec/remoteparticipant.js
test/unit/spec/room.js

@manjeshbhargav I think we missed a small change in 595b467382389d2750876e704bdfb43487314081 (the `this` argument was omitted when the emitting "enabled"/"disabled" Track event). Adding it back fixes JSDK-1932. I also took the opportunity to expand a few other unit tests and fix some JSDoc.

Fix for JSDK-1932

---

CHANGELOG.md
lib/connect.js
lib/participant.js

* One method was not marked private
* An ESLint comment was excluding LogLevel from the JSDoc
---
@manjeshbhargav as these are only JSDoc changes and 1.10.0-rc2 passed QE, I think we can release 1.10.0 without another RC.

Fix JSDoc issues

---

lib/remoteparticipant.js
lib/room.js

@markandrus 
I was not sure if I should update `RemoteTrackPublication` guide in `CHANGELOG.md`, since it is present under an earlier version.
Please let me know if this clarification is sufficient, and whether we should include something in `CHANGELOG.md`.

JSDK-2038 Clarifying "trackPublished" behavior.

---

CHANGELOG.md
lib/createlocaltrack.js
lib/createlocaltracks.js
lib/webaudio/detectsilence.js
lib/webaudio/workaround180748.js

_Not ready to merge. Still needs testing._
---
You can specify this in any of the following ways:
```js
connect(token, { audio: { workaroundWebKitBug180748: true });
createLocalAudioTrack({ workaroundWebKitBug180748: true });
createLocalTracks({ audio: { workaroundWebKitBug180748: true } });
```
In Safari, this *might* workaround [WebKit Bug 180748](https://bugs.webkit.org/show_bug.cgi?id=180748). In the worst case, it will slow down LocalAudioTrack creation.

Add workaroundWebKitBug180748 option

---

lib/iceserversource/constant.js
lib/iceserversource/index.js
lib/iceserversource/nts.js
lib/signaling/v2/cancelableroomsignalingpromise.js
lib/signaling/v2/transport.js

This property will indicate if
* `iceServers` was overridden in ConnectOptions, and therefore ECS was bypassed;
* Acquiring ICE servers from ECS succeeded; or
* Acquiring ICE servers from ECS failed.
**EDIT**: I've now manually tested the "success" case, the "failure" case, and the "overrode" case.

Add `ice_servers` property to "connect" message

---

test/lib/mocksdp.js
test/unit/spec/util/sdp/index.js

@manjeshbhargav i made a mistake in merging the previous RTX PR. I had `only` enabled (and forgot to remove a `console.log`). Also, the `only` masked the fact that we needed to update other tests.

Fix tests after RTX change

---

package.json

We'll cut a twilio-video.js@1.12.0-rc1 soon to validate twilio-webrtc.js@2.1.1-rc2. If that looks good, we'll publish twilio-webrtc.js@2.1.1, update twilio-video.js to depend on `^2.1.1`, then publish twilio-video.js@1.12.0.

twilio-webrtc.js@2.1.1-rc2

---

README.md
lib/media/track/remoteaudiotrackpublication.js
lib/media/track/remotedatatrackpublication.js
lib/media/track/remotetrackpublication.js
lib/media/track/remotevideotrackpublication.js

@markandrus 
Corollary: Also updated README.md links to point to `2.0.0-beta1`.

JSDK-2096: Documenting "subscriptionFailed" event

---

lib/eventemitter.js
lib/media/track/index.js
lib/media/track/localdatatrack.js
lib/media/track/localmediatrack.js
lib/media/track/localtrackpublication.js
lib/media/track/mediatrack.js
lib/media/track/remotedatatrack.js
lib/media/track/remotemediatrack.js
lib/media/track/remotetrackpublication.js
lib/media/track/trackpublication.js
lib/media/track/videotrack.js
lib/participant.js
lib/room.js
lib/util/index.js
test/unit/spec/localparticipant.js
test/unit/spec/media/track/localdatatrack.js
test/unit/spec/media/track/localmediatrack.js
test/unit/spec/media/track/localtrackpublication.js
test/unit/spec/media/track/remotedatatrack.js
test/unit/spec/media/track/remotemediatrack.js
test/unit/spec/media/track/remotetrackpublication.js
test/unit/spec/remoteparticipant.js
test/unit/spec/room.js
test/unit/spec/util/index.js

_Work-in-progress. Not ready to merge._
When we moved to ES6 classes, we didn't really think about the effect of adopting ES6 class getters. These differ from the instance getters we previously defined, because they don't show up when calling `Object.getOwnProperties(instance)`. This is because they are defined on the `prototype`. As a consequence of this, `Object.assign` and object spread (`{ ...foo }`) might not copy all the properties we're interested in. Of course, you can always pick out the properties by hand, but it'd be nice if we could support this syntax. To do so, we'd have to abandon ES6 getters and move these back into the constructor.
So, open question, would we consider moving away from ES6 getters? I haven't begun implementing in this PR yet. **EDIT:** Based on discussion …

JSDK-2025: Improve Object.keys & JSON.stringify behavior for public classes

---

lib/data/transport.js
test/integration/spec/room.js
test/unit/spec/data/transport.js

@markandrus
This PR fixes [JSDK-2098](https://issues.corp.twilio.com/browse/JSDK-2098) by ensuring that the DataTransport's RTCDataChannel's .readyState is "open" before sending the "ready" message.

JSDK-2098 (2.x)

---

lib/signaling/v2/peerconnectionmanager.js
test/unit/spec/signaling/v2/peerconnectionmanager.js

Notes:
* I had to update the call to `makeMediaStream`; otherwise, the test trivially passed because no other MediaStreamTracks were added, meaning the dummy MediaStreamTrack was always first.
* In the future, we should eliminate the dummy MediaStreamTrack in favor of a single call to `addTransceiver('audio')`.

JSDK-2097: Always add dummyAudioTrack first

---

README.md

Fixes #344. I tested by adding these policy directives (plus rules for `'self'`) to one of our internal dog food applications. I verified that things continued to work.

Add Content Security Policy (CSP) section to README.md

---

lib/data/transport.js
lib/signaling/v2/dominantspeakersignaling.js
test/unit/spec/data/transport.js

Since we move sending the "ready" message into DataTransport, it'll fire for Dominant Speaker and Network Quality APIs.

JSDK-2095: DataTransport should send "ready" message

---

CHANGELOG.md
lib/data/transport.js
lib/signaling/v2/dominantspeakersignaling.js
package.json
test/unit/spec/data/transport.js

This bumps the twilio-webrtc.js dependency for the RC, and it includes the fix for JSDK-2095.

Prepare for 1.13.1 rc1

---

lib/media/track/audiotrack.js
lib/media/track/mediatrack.js
lib/media/track/videotrack.js
lib/signaling/v2/peerconnection.js
lib/signaling/v2/peerconnectionmanager.js
test/unit/spec/media/track/mediatrack.js

I wonder if integration tests will be improved or not with these changes. I still want to do some manual testing before merging. **EDIT:** Oops, I didn't realize [Bug 1231414](https://bugzilla.mozilla.org/show_bug.cgi?id=1231414) is still a thing, so we can't just `addTrack` without a MediaStream argument.

JSDK-2118: Reduce MediaStream usage in Firefox

---

CHANGELOG.md
lib/connect.js
lib/signaling/v2/cancelableroomsignalingpromise.js
lib/signaling/v2/transport.js

Per discussion today. **EDIT:** Rather than ship this by default to all users at once, we'll let users opt-in to these features. This also means, if you don't want the Dominant Speaker or Network Quality APIs, you don't need to enable them.

Add `dominantSpeaker` and `networkQuality` ConnectOptions

---

CHANGELOG.md
lib/localparticipant.js
test/unit/spec/localparticipant.js

@mhuynh5757 
This PR fixes a bug where calling `LocalVideoTrack#stop()` does not turn the camera light off. This is due to the fact that when a `LocalParticipant` disconnects from the `Room`, we do not stop all the cloned `MediaTrackSender`s that are published to the `Room`. So, even if `LocalVideoTrack#stop()` stops the `MediaTrackSender` associated with it, the cloned `MediaTrackSender`s are still capturing media.
These changes will fix the behavior described [here](https://github.com/twilio/video-quickstart-js/issues/53).

JSDK-2156 Stopping all the cloned MediaTrackSenders upon disconnect.

---

CHANGELOG.md
lib/signaling/localparticipant.js
test/unit/spec/signaling/v2/localparticipant.js

JSDK-2169 Stopping the cloned MediaTrackSender instead of the original.

---

karma/makeconf.js
lib/util/index.js
package.json

@manjeshbhargav @markandrus 
Should we care about sdpSemantics in the connect options?
I still need to test by passing sdpSemantics='plan-b' and check how Edge behaves.

Use unified sdpFormat for Edge

---

lib/twilioconnection.js

@markandrus 
Chrome's WebSocket sometimes takes a really long time (~1 min) to emit a `CloseEvent` after calling `WebSocket#close()` whenever there is a network problem. So, this PR makes sure that the `TwilioConnection` is closed as soon as `WebSocket#close()` is called.

Transition to "closed" state without waiting for WebSocket's "close" event.

---

CHANGELOG.md
lib/util/sdp/simulcast.js
test/unit/spec/util/sdp/index.js

This reverts commit 51a2cb26c3cbcd58873abfbb53adc1ea156e6cd8.

Revert "Include "a=x-google-flag:conference" for Simulcast"

---

package.json

This RC contains [changes](https://github.com/twilio/twilio-webrtc.js/tree/3.1.0-rc1/CHANGELOG.md) required for JSDK-2146.

Upgrading to twilio-webrtc.js@3.1.0-rc1.

---

package.json

This RC contains [changes](https://github.com/twilio/twilio-webrtc.js/tree/2.2.0-rc1/CHANGELOG.md) required for JSDK-2146.

Upgrading to twilio-webrtc.js@2.2.0-rc1.

---

CHANGELOG.md
lib/localparticipant.js
test/integration/spec/localparticipant.js

This PR fixes [JSDK-2212](https://issues.corp.twilio.com/browse/JSDK-2212).

JSDK-2212 Ensure LocalTrackPublicationV2 is not null.

---

karma/makeconf.js
lib/signaling/v2/peerconnectionmanager.js
lib/util/index.js
package.json
test/lib/util.js

* Replacing karma-safaritechpreview-launcher with karma-safari-launcher. You can still run Safari Tech Preview by overriding SAFARI_BIN env variable with the path to the executable.
@syerrapragada

JSDK-2232 Unified Plan support for Safari 12.1.

---

lib/participant.js
lib/signaling/localtrackpublication.js
lib/signaling/participant.js
lib/signaling/remotetrackpublication.js
lib/signaling/track.js
lib/signaling/v2/remoteparticipant.js
lib/signaling/v2/remotetrackpublication.js
lib/signaling/v2/room.js
lib/signaling/v2/transport.js
test/integration/spec/connect.js
test/integration/spec/rest.js
test/unit/spec/signaling/v2/remoteparticipant.js
test/unit/spec/signaling/v2/remotetrackpublication.js
test/unit/spec/signaling/v2/transport.js

Since we consume the `published` and `subscribed` payloads in RSP, we now bump the RSP version to 2.

JSDK-2245 Bump RSP version to 2.

---

lib/signaling/v2/peerconnection.js
package.json

We work around this issue for now by triggering a re-negotiation with Chrome("plan-b") as the offerer.

Workaround for media problems b/w Chrome("unfied-plan") offerer and Chrome("plan-b") answerer.

---

CHANGELOG.md
package.json

This PR is for preparing for twilio-video.js@2.0.0-rc11.

Prep for 2.0.0-rc11

---

CHANGELOG.md
package.json

This PR addresses [this issue](https://github.com/twilio/twilio-video.js/issues/507) raised by a customer.

JSDK-2266 Fixing broken Electron 2.x support.

---

lib/signaling/v2/peerconnection.js
package.json
test/integration/spec/localparticipant.js
test/lib/util.js

Starting from Chrome 73 and Firefox 64, calling createOffer() a second time without calling setLocalDescription() on the first offer will change the mids of those RTCRtpTransceivers that have not yet been fully negotiated (gone through an offer --> answer cycle).
Also, `offerToReceive{Audio,Video}` reuses the first m= line of its kind, thereby generating a new mid for it.
This PR does the following to handle the above behaviors:
* Reduce instances of `createOffer` being called more than once per negotiation.
* Ensure that the first audio and video m= lines are never recycled (Firefox only).
This PR does the following to handle the above behaviors:
* Reduce instances of `createOffer` being called more than once per negotiation.
* Ensure that the first audio and video m= …

JSDK-2219 Avoid changing mids of RTCRtpTransceivers during negotiation.

---

CHANGELOG.md
lib/media/track/localmediatrack.js
package.json

This PR fixes:
JSDK-2267: getStats support for Electron 2.x and 3.x.
JSDK-2268: Safari console's object explorer throws TypeError for `isEnabled` and `isStopped`.

JSDK-2267, JSDK-2268

---

CHANGELOG.md
lib/connect.js
lib/media/track/localmediatrack.js
lib/signaling/v2/cancelableroomsignalingpromise.js
lib/signaling/v2/peerconnection.js
lib/signaling/v2/peerconnectionmanager.js
lib/signaling/v2/transport.js
lib/signaling/v2/twilioconnectiontransport.js
lib/util/index.js
lib/util/support.js
package.json
test/env.js
test/integration/spec/localparticipant.js
test/integration/spec/util/simulcast.js
test/lib/defaults.js
test/lib/guessbrowser.js
test/umd/index.js
test/umd/require-browser/index.html
test/umd/require-browser/min.html
test/unit/spec/signaling/v2/twilioconnectiontransport.js

This PR:
* Removes "plan-b" enforcement.
* Consumes twilio-webrtc.js#JSDK-2265 changes.

JSDK-2265 Removing "plan-b" enforcement.

---

CHANGELOG.md
COMMON_ISSUES.md
lib/room.js
lib/signaling/room.js
test/unit/spec/room.js
test/unit/spec/signaling/room.js

@syerrapragada @innerverse 
* Ensuring the proper TwilioError passed to the Room#reconnecting event listener ([IDL](https://code.hq.twilio.com/pages/client/video-sdk-api/idl/room.html)).
* Updating unit tests.
* Updating Room#reconnecting event documentation.
* CHANGELOG.md entry to announce the opt-in feature.
TODO
=====

Prepping for 2.0.0-rc12

---

lib/signaling/v2/peerconnection.js
test/integration/spec/localparticipant.js
test/unit/spec/signaling/v2/peerconnection.js

~~WIP.~~
While #518 reduced the instances of SDPs with changing mids for the same m= sections during negotiation, it did not fully eliminate them because we still can create an offer in the middle of a negotiation (that is while an offer has already been sent and awaiting an answer).
This PR makes sure that calls to createOffer() are queued until the existing offer <--> answer negotiation is complete.

JSDK-2219 Queueing calls to createOffer() until the current negotiation is complete.

---

CHANGELOG.md
karma/makeconf.js
lib/connect.js
lib/signaling/v2/cancelableroomsignalingpromise.js
lib/signaling/v2/peerconnection.js
lib/signaling/v2/peerconnectionmanager.js
lib/signaling/v2/transport.js
lib/util/index.js
lib/util/support.js
package.json
test/env.js
test/integration/spec/localparticipant.js
test/integration/spec/util/simulcast.js
test/lib/defaults.js
test/lib/guessbrowser.js
test/umd/index.js
test/umd/require-browser/index.html
test/umd/require-browser/min.html
test/unit/spec/signaling/v2/transport.js

* Removing plan-b enforcement (twilio-webrtc.js#JSDK-2265-2.x).
* Since PhantomJS is no longer supported, the UMD test is re-written with puppeteer + headless Chrome.
* Disabling autoplay policy in Firefox 66+ for tests.
* Updating CHANGELOG.md to include Unified Plan Guide.

JSDK-2265 Using default SDP format.

---

CHANGELOG.md
lib/signaling/v2/peerconnection.js

@manjeshbhargav 
This PR removes workaround for Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1481335 on Firefox 65 and Above.

JSDK-2280: Remove dummy RTCDataChannel for Firefox 65 and above.

---

COMMON_ISSUES.md

@idelgado @anna-vasilko 
This entry is based on this [paper doc](https://paper.dropbox.com/doc/Firefox-63Mobile-WebRTC-57-Compatibility-Issue--AXTPxhC6ozZIrJMw189c5PVyAg-gE0UAL0lv4JGHg8s50fCl). Please leave your feedback where appropriate.

JSDK-2281 Add COMMON_ISSUES.md entry for FF63+ and WebRTC 57 mobile clients.

---

CHANGELOG.md
lib/signaling/v2/peerconnection.js

@manjeshbhargav 
cherry-pick JSDK-2280 for 1.x branch

JSDK-2280: Remove dummy RTCDataChannel for Firefox 65 and above. (#536)

---

lib/signaling/v2/peerconnection.js
lib/util/sdp/index.js
package.json
scripts/karma.js
test/integration/spec/localparticipant.js
test/integration/spec/localtrackpublication.js
test/unit/spec/util/sdp/index.js

@innerverse @syerrapragada 
In order to prevent ever-increasing SDP sizes on Chrome 72+ (`RTCRtpTransceiver.stop()` has not been implemented), we use the following alternate method to re-use m= lines in unified plan browsers:
* Re-use any available "recvonly" RTCRtpTransceivers while adding a MediaStreamTrack.
* Make sure all calls to RTCRtpSender.replaceTrack() resolve before creating the offer.
* Make sure that SDPs sent to the remote peer contain the local IDs for the MediaStreamTracks added using RTCRtpSender.replaceTrack().

JSDK-2276 Alternate method of re-using m= lines.

---

CHANGELOG.md
lib/connect.js
lib/twilioconnection.js
test/integration/spec/connect.js
test/lib/defaults.js
test/unit/spec/connect.js

Because the EMG and rtc-conversation-orchestrator have SIP payload limits, and coupled with the lack of support for recycling m= lines in Chrome 72+ resulting in large SDPs, the EMG terminates the signaling connection after a few rounds of publish/unpublish tracks. So, TCMP is enabled as the default transport because it does not have a payload limit.

JSDK-2296 Enable TCMP as the default signaling transport.

---

CHANGELOG.md
lib/connect.js
package.json
test/lib/defaults.js

* Reverting to SIP as the default transport.
* Reverting to "plan-b" as the default SDP format on Chrome 72+.

JSDK-2306 Enabling unified plan only for Safari 12.1+

---

CHANGELOG.md
package.json

* Enforcing "plan-b" SDP format for Chrome
* Retaining "unified-plan" SDP format support for Safari 12.2+

 JSDK-2305 Enabling unified plan only for Safari 12.2+

---

CHANGELOG.md
COMMON_ISSUES.md

@idelgado @syerrapragada 
* Describe changes in AccessToken behavior between SIP and TCMP.
* Reword Safari Unified Plan support to be version-agnostic.

CHANGELOG.md update for 2.0.0-beta6

---

lib/signaling/v2/networkqualitymonitor.js
lib/signaling/v2/networkqualitysignaling.js
lib/signaling/v2/room.js
test/integration/spec/localparticipant.js
test/integration/spec/room.js
test/unit/spec/signaling/v2/networkqualitymonitor.js
test/unit/spec/signaling/v2/networkqualitysignaling.js
test/unit/spec/signaling/v2/room.js

@manjeshbhargav 
This PR enables NQ scores for remote participants.
1. Enabled remote participants scores (`remoteReportLevel: 1`) in MSP message.
2. Added `remoteLevels` property in both NetworkSignaling and NetworkMonitor Objects.
3. Upon `updated` event, Update remote participant's Network Quality scores if available.
I have cut this PR to get your initial feedback. Please review.

JSDK-2254: Report network quality scores for remote participant

---

CHANGELOG.md
karma/makeconf.js
lib/signaling/v2/peerconnection.js
test/integration/spec/room.js

This PR fixes [JSDK-2323](https://issues.corp.twilio.com/browse/JSDK-2323), which is happening due to "muted" being  sometimes fired on the MediaStreamTrack (currently happening in Chrome only, probably a bug), which removes the corresponding MediaTrackReceiver from the collection, resulting in getStats() no longer containing an entry for that particular Track. We no longer depend on "muted" and manually updated the collection of MediaTrackReceivers.

JSDK-2323 Removing dependency on "mute" event to remove unpublished MediaTrackReceivers.

---

CHANGELOG.md
karma/makeconf.js
lib/signaling/v2/peerconnection.js
lib/util/sdp/index.js
package.json
test/integration/spec/connect.js
test/integration/spec/localparticipant.js
test/integration/spec/room.js
test/integration/spec/util/insightspublisher.js
test/unit/spec/util/sdp/index.js

* JSDK-2313 - Enable unified plan support for Chrome.
* JSDK-2318 - Convert audioLevel fron 0-1 to 0-32767.
In 2.x, since we clone MediaStreamTracks, when a previously added LocalTrack is re-added, a new MediaStreamTrack is added to the new transceiver's sender, so the MSID in the corresponding m= section will be equal to the MediaStreamTrack ID.
However, in 1.x, since we re-add the same MediaStreamTrack to the new transceiver's sender, it will generate a different MSID in the corresponding m= section. So, the track id rewrite logic is a bit different here.

JSDK-2313, JSDK-2318

---

CHANGELOG.md
COMMON_ISSUES.md
README.md

@makarandp0 
This PR updates the docs links to point to 2.0.0-beta9 and updates COMMON_ISSUES.md to note that Firefox fails to recover media connections during network interruptions or handoffs.

Prep for 2.0.0-beta9.

---

lib/signaling/v2/peerconnection.js

This PR fixes [JSDK-2330](https://issues.corp.twilio.com/browse/JSDK-2330). We now maintain a set of locally supported codecs and a map of MIDs and their remotely supported codecs. Now, when we add a new MediaStreamTrack, we choose the RTCRtpTransceiver as follows:
* If no preferred codecs are specified, just use the first re-useable RTCRtpTransceiver if present.
* Find the first preferred codec that is locally supported, and if present, choose an RTCRtpTransceiver which supports this codec remotely.
* If there are no locally supported preferred codecs, then this is equivalent to no preferred codecs, so just use the first re-useable RTCRtpTransceiver, if present.

JSDK-2330 Make sure preferredCodecs is honored.

---

README.md

@innerverse 
CSP now contains the TCMP endpoint and no longer has the SIP.js endpoint.

JSDK-2343 Modify Content Security Policy to replace SIP.js endpoint with TCMP global endpoint.

---

CHANGELOG.md
lib/signaling/v2/peerconnection.js
lib/util/sdp/index.js
test/integration/spec/connect.js
test/lib/mocksdp.js
test/lib/rest.js
test/unit/spec/util/sdp/index.js

This PR attempts to fix the issue where the group room failed when simulcast is enabled for H264 media sections.
for chrome and safari browsers:
Offerer case:
- client creates offer
**- cache the created offer (offerWithoutSimulcast)**
- enable simulcast
- setLocalDescription
- starts negotiation
- upon receiving the answer:
**- use the cached offer to reverts simulcast in the negotiated offer for sections where vp8 is not the preferred codec in the corresponding section of the remote answer**
**- rollback** 
**- call setLocalDescription with this new offer**
- setRemoteDescription to complete the negotiation
Answerer case:
- client receives offer
- setRemoteDescription
- createAnswer
- enable simulcast
**- revert simulcast for sections where vp8 is not the preferred codec in the …

Enable simulcast only if VP8 is the preferred codec in answer.

---

.travis.yml
lib/signaling/v2/peerconnection.js
lib/util/sdp/index.js
test/unit/spec/util/sdp/index.js

@syerrapragada @makarandp0 
This PR attempts to mitigate the issues found in [JSDK-2357](https://issues.corp.twilio.com/browse/JSDK-2357), where the signaling transport closes due to large SDP sizes if more than 10-12 Participants are in a Group Room with 1 audio and 1 video Track.
The main reason why this happens is the browser supports more codecs than those supported by VMS, and each of these extra codecs/profiles add significantly to the size of each m= section. The function `unifiedPlanFilterLocalCodecs` in `lib/util/sdp/index.js` filters the codecs in the m=sections of the local SDP based on the codecs present in the corresponding m= sections in the remote SDP.
According to @syerrapragada 's initial tests, the signaling transport can handle about 23 Participants in a Group Room with …

JSDK-2357 Filter codecs in unified plan local SDPs based on remote SDPs.

---

lib/util/sdp/index.js
test/unit/spec/util/sdp/index.js

@syerrapragada @makarandp0 
This PR fixes [JSDK-2368](https://issues.corp.twilio.com/browse/JSDK-2368), which was being caused due to a bug in the filtering logic where rtx payload types for filtered codecs were being retained. For ex, if the codec payload type 50 was removed, we would still retain the rtx payload type with `apt=50`.
The solution is to not consider rtx payload types in the remote RTCSessionDescription while constructing a list of local codecs to retain.

JSDK-2368 Consider only non-rtx payload types in the remote RTCSessionDescription while filtering local codecs.

---

karma/makeconf.js
package.json

To run electron tests on this repo, previously we used a fork of karma-electron (https://github.com/twilio/karma-electron) that added a new flag to disable custom user agent. 
Our change is now accepted and merged (https://github.com/twolfson/karma-electron/pull/39) into upstream repo we no more need to maintain our fork. This change takes a direct dependency on upstream repo to enable retiring our fork.
verified that electron tests passed after the change. 
```
BROWSER=electron npm run test:integration
...
Electron 5.0.0 (Mac OS X 10.14.5): Executed 289 of 298 (skipped 9) SUCCESS (2.803 secs / 0.204 secs)
TOTAL: 289 SUCCESS 
```
Also similar change in PR: https://github.com/twilio/twilio-webrtc.js/pull/103

use upstream karma-electron + updated flag

---

lib/media/track/remoteaudiotrackpublication.js
lib/media/track/remotedatatrackpublication.js
lib/media/track/remotetrackpublication.js
lib/media/track/remotevideotrackpublication.js

This change fixes error in doc annotation.
after
```
~/work/twilio-video.js> npm run docs
> twilio-video@2.0.0-dev docs /Users/mpatwardhan/work/twilio-video.js
> node ./scripts/docs.js ./dist/docs
(node:72097) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
~/work/twilio-video.js> 
```
before:
```
~/work/twilio-video.js> npm run docs
> twilio-video@2.0.0-dev docs /Users/mpatwardhan/work/twilio-video.js
> node ./scripts/docs.js ./dist/docs
Error: unable to parse RemoteAudioTrack</a>.</p>: Expected "!", "$", "'", "(", "*", ".", "...", "0", "?", "@", "Function", "\"", "\\", "_", "break", "case", "catch", "class", "const", "continue", "debugger", "default", …
```

JSDK-2370 fix doc annotation error

---

.travis.yml
CHANGELOG.md
lib/signaling/v2/peerconnection.js
lib/util/sdp/index.js
test/unit/spec/util/sdp/index.js

This PR fixes JSDK-2381. Firefox 68 onwards no longer generates local SDPs with the same Track IDs as the added MediaStreamTracks, even if they are added the first time. This is I think an intermediate step to removing Track IDs from SDPs altogether.
So, this PR rewrites the generated Track IDs with the Track IDs signaled via RSP, so that the RemoteParticipant can match a remote MediaStreamTrack to a given signaled Track ID.

JSDK-2381 Rewriting Track IDs in local SDPs with the Track IDs signaled via RSP.

---

.travis.yml
CHANGELOG.md
lib/signaling/v2/peerconnection.js
lib/util/sdp/index.js
test/unit/spec/util/sdp/index.js

This PR fixes JSDK-2381 for 1.x.

JSDK-2381 [1.x] Rewriting Track IDs in local SDPs with the Track IDs signaled via RSP.

---

test/env.js
test/integration/spec/connect.js
test/lib/defaults.js

This PR adds a new environment variable `REGIONS` to the integration test suite. In `stage`, you can use this to pass only those signaling regions that are supported in this environment like this:
```
... ENVIRONMENT=stage REGIONS=au1,in1,us1 ... npm run test:integration 
```
If you don't specify `REGIONS`, then all the signaling regions will be tested.

JSDK-2387 Consuming REGIONS environment variable in integration tests for signaling region.

---

lib/connect.js
lib/data/sender.js
lib/data/transport.js
lib/signaling/v2/cancelableroomsignalingpromise.js
lib/signaling/v2/peerconnection.js
lib/signaling/v2/twilioconnectiontransport.js
lib/util/constants.js
lib/util/sdp/index.js
package.json
test/integration/spec/connect.js
test/integration/spec/localparticipant.js
test/integration/spec/util/simulcast.js
test/lib/mocksdp.js
test/unit/spec/util/sdp/index.js

This PR has two sections:
1. As of now, each m= section has this line `a=msid:<streamId> <appdata>`. The `appdata` field represents the Track ID associated with the m= section. This need not be the same as the ID of the actual MediaStreamTrack that is assigned to this m= section. So we have been rewriting the `appdata` field with the actual MediaStreamTrack ID. In this PR, we make sure that we write the MediaStreamTrack ID even if `appdata` is not present in the m= section, because WebRTC spec has been updated to remove `appdata`.
2. A new (or rather a previously available) `sdpSemantics` ConnectOptions flag is (re)introduced to switch easily between `plan-b` and `unified-plan`. Now, we don't need to maintain a separate branch for the Plan B implementation. …

JSDK-2385 Add or rewrite Track IDs in local SDPs even if "appdata" field is not present.

---

CHANGELOG.md
lib/data/receiver.js
lib/signaling/v2/room.js
test/unit/spec/signaling/v2/room.js

Note: This PR was originally opened as https://github.com/twilio/twilio-video.js/pull/665, 
For network quality and dominant speaker updates client  listen on a datachannel. The id for the channels is obtained from RSP field (roomState.media_signaling.network_quality.transport.label, roomState.media_signaling.network_quality.transport.label).
During the call in a group room if the VMS process gets killed, a new instance gets created - This results in an update message on signaling channel with a new peerconnection id. Client responds by creating a new peer connection.
The problem was we were not rehooking our NetoworkMonitor, Dominant Spekear dataChannels from the new peerconnection in such cases.
With this change, we fix this by tearing down the monitors after close event on datachannel. …

JSDK-2307 MSP objects do not recover on JSDK side after SFU Failover

---

CHANGELOG.md
COMMON_ISSUES.md
lib/signaling/v2/peerconnection.js
lib/util/sdp/index.js
test/unit/spec/util/sdp/index.js

JSDK-2410 - Make sure we don't rewrite the dummy audio MediaStreamTrack's appdata field.

---

CHANGELOG.md
lib/signaling/v2/peerconnection.js
lib/util/sdp/index.js
test/lib/mocksdp.js
test/unit/spec/util/sdp/index.js

* JSDK-2383 - Make sure Track IDs are rewritten even when appdata field is absent in local SDPs.
* JSDK-2410 - Make sure we don't rewrite the dummy audio MediaStreamTrack's appdata field.

JSDK-2383, JSDK-2410

---

lib/localparticipant.js
lib/media/track/index.js
lib/media/track/localaudiotrackpublication.js
lib/media/track/localdatatrackpublication.js
lib/media/track/localtrackpublication.js
lib/media/track/localvideotrackpublication.js
lib/media/track/remotetrackpublication.js
lib/signaling/localparticipant.js
lib/signaling/localtrackpublication.js
lib/signaling/remotetrackpublication.js
lib/signaling/track.js
lib/signaling/v2/localparticipant.js
lib/signaling/v2/localtrackpublication.js
lib/signaling/v2/peerconnectionmanager.js
lib/signaling/v2/remotetrackpublication.js
lib/util/constants.js
lib/util/index.js
test/integration/spec/connect.js
test/integration/spec/localparticipant.js
test/unit/spec/localparticipant.js
test/unit/spec/media/track/localtrackpublication.js
test/unit/spec/media/track/remotetrackpublication.js
test/unit/spec/signaling/v2/localparticipant.js
test/unit/spec/signaling/v2/localtrackpublication.js
test/unit/spec/signaling/v2/remotetrackpublication.js

@makarandp0 
This PR implements the publisher side Track Priority API. Please take a look when you can.

JSDK-2346 Track priority for publishing a LocalTrack.

---

CHANGELOG.md
lib/util/constants.js
test/integration/spec/connect.js

Instead of using region specified directly, we now `encodeURIComponent` the region, This ensures that if `region` contains invalid characters for URI, it will fail with correct error code.

JSDK-2400 invalid characters in region parameter should return correct errorcode.

---

CHANGELOG.md
lib/signaling/v2/peerconnection.js

@makarandp0 
This PR fixes JSDK-2412 and JSDK-2415. The reason for these bugs is that Firefox 68+ generates an RTCIceCandidate with an empty candidate string to signal the end of candidate gathering. It also generates a null candidate (legacy way of signaling end of candidate gathering). But Chrome and Safari do not yet accept the empty candidate. So, we now just log warnings and suppress the error since it does not affect media connection in any way.
The reason I wanted to log warnings is that we should be able to make out when Chrome and Safari start accepting the empty candidate. When they do, we should no longer see these console warnings.
> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source …

Handle Firefox 68+'s empty ice candidate in Chrome and Safari.

---

CHANGELOG.md
lib/connect.js
lib/localparticipant.js
lib/media/track/remoteaudiotrack.js
lib/media/track/remotedatatrack.js
lib/media/track/remotemediatrack.js
lib/media/track/remotevideotrack.js
lib/signaling/v2/room.js
lib/util/constants.js
lib/util/index.js
test/unit/spec/connect.js
test/unit/spec/localparticipant.js
test/unit/spec/media/track/remotedatatrack.js
test/unit/spec/media/track/remotemediatrack.js

@makarandp0 
This PR adds type checking logic to make sure only valid values are specified for TrackPriority and BandwidthProfileOptions.
TODO
=====

JSDK-2448 Type checks for TrackPriority and BandwidthProfileOptions

---

lib/connect.js
lib/signaling/v2/cancelableroomsignalingpromise.js
lib/signaling/v2/twilioconnectiontransport.js
test/unit/spec/connect.js
test/unit/spec/signaling/v2/twilioconnectiontransport.js

@makarandp0 
This PR makes sure that we don't send the `bandwidth_profile` RSP payload if `bandwidthProfile` is not specified in ConnectOptions.

Prepping for 2.0.0-rc35

---

lib/signaling/v2/room.js
lib/signaling/v2/twilioconnectiontransport.js
lib/util/insightspublisher/index.js
lib/util/insightspublisher/null.js
test/integration/index.js
test/integration/spec/connect.js
test/integration/spec/util/insightspublisher.js
test/unit/spec/signaling/v2/room.js
test/unit/spec/signaling/v2/twilioconnectiontransport.js
test/unit/spec/util/insightspublisher.js

@manjeshbhargav, @innerverse 
This change waits for roomSid, partcipantSid before connecting to event publisher endpoint. That way we can pass roomSid/participantSid along with the connect message. I have few open question around this (https://twilio.slack.com/archives/C35JTJHJP/p1563392120206400), but I would like to get initial feedback. 
TODO:

JSDK-2408 add room and participant sid in connect message.

---

lib/data/transport.js
lib/signaling/v2/peerconnection.js
test/integration/spec/connect.js
test/integration/spec/localparticipant.js
test/lib/util.js
test/unit/spec/signaling/v2/peerconnection.js

@makarandp0 
This PR implements setting max outgoing bitrate values for audio and video using `RTCRtpSender.setParameters()` instead of SDP munging.

JSDK-2250 Use RTCRtpSender.setParameters where available, instead of SDP munging.

---

lib/signaling/v2/room.js
lib/signaling/v2/transport.js
lib/util/insightspublisher/index.js
lib/util/insightspublisher/null.js
test/integration/spec/connect.js
test/integration/spec/util/insightspublisher.js
test/unit/spec/signaling/v2/room.js
test/unit/spec/signaling/v2/transport.js
test/unit/spec/util/insightspublisher.js

* pass roomSid, participantSid along with connect for insights
This PR ports https://github.com/twilio/twilio-video.js/pull/692 into  1.x branch
mostly cherry-pick, except for following files which have diverged significantly from the master 
Following files 
```
lib/signaling/v2/transport.js
test/unit/spec/signaling/v2/transport.js
```

JSDK-2408 pass room sid in connect message (support-1.x-chrome-planb)

---

CHANGELOG.md
lib/connect.js
lib/signaling/v2/peerconnection.js
test/integration/spec/connect.js
test/unit/spec/signaling/v2/peerconnection.js

This change adds an option `dscpTagging` to enable adding dscp headers for audio packets. 

JSDK-2440 support dscp tagging (support-1.x-chrome-planb)

---

lib/signaling/v2/peerconnection.js
package.json
test/integration/spec/connect.js

@makarandp0 
This PR consumes https://github.com/twilio/twilio-webrtc.js/pull/109 and makes sure updates to "_trackIdsToAttributes" are undone when an offer is rolled back.

JSDK-2463 Undoing updates to "_trackIdsToAttributes" when an offer is rolled back.

---

test/integration/spec/connect.js

@makarandp0 
I failed to notice that your DSCP tagging test was not written properly in #702 which resulted in failure on Travis. So I've refactored it to check `networkPriority` for both audio and video only for Chrome. For Firefox and Safari, it should check that `networkPriority` should not exist even after trying to set it.

Fixing failing DSCP tagging test.

---

CHANGELOG.md
lib/connect.js
lib/signaling/v2/peerconnection.js
test/integration/spec/connect.js
test/integration/spec/localparticipant.js
test/lib/util.js
test/unit/spec/signaling/v2/peerconnection.js

This change cherry-picks and merges following PRs that were already merged into 1.x branch
https://github.com/twilio/twilio-video.js/pull/707 Fixing failing DSCP tagging test. 
https://github.com/twilio/twilio-video.js/pull/704 JSDK-2440 support dscp tagging (support-1.x-chrome-planb) 
https://github.com/twilio/twilio-video.js/pull/700 JSDK-2250 Use RTCRtpSender.setParameters where available, instead of SDP munging. 

JSDK-2456 port dscp fix + RTCRtpSender.setParameters use.

---

lib/room.js

@makarandp0 
This PR includes RemoteTrackPublication as the second argument in the event docs. This doc error was pointed out by a customer.

JSDK-2467 Update Room's "trackSubscribed" and "trackUnsubscribed" events docs

---

.travis.yml

When moving our travis tests to run inside docker (https://github.com/twilio/twilio-video.js/pull/712), Instead of running `travis:build` I had it run `test:integration` which skipped some essential steps of the job. It breaks our release process. Our release process uses the travis job to generate dependent files + validate the release and tag the builds. 
This change reverts the docker related changes to travis job. Will figure  out how to re-introduce docker w/o breaking the release process soon. 

JSDK-2483 revert to non-dockerized build on travis

---

COMMON_ISSUES.md

Update common_issues.md to mention Chrome 76 + older mobile sdk data track compatibility issue. This was brought up by a customer [here](https://github.com/twilio/twilio-video.js/issues/714), and @ceaglest created a explained it nicely [here](https://github.com/twilio/twilio-video-ios/issues/52) 

JSDK-2474 - Update common_issues.md - chrome 76 + ios 2.2.0 incompatibility

---

.travis.yml
CHANGELOG.md
COMMON_ISSUES.md
lib/signaling/v2/peerconnection.js
test/integration/spec/connect.js
test/integration/spec/localparticipant.js

@makarandp0 
Porting the changes to fix JSDK-2509 from #743 .
* Instead of setting maxBitrate to 0, remove the property instead.
* Adding CHANGELOG.md entry.
* Adding COMMON_ISSUES.md entry.

JSDK-2509 - Instead of setting maxBitrate to 0, remove the property instead.

---

CHANGELOG.md
lib/media/track/mediatrack.js
lib/media/track/remotemediatrack.js
test/unit/spec/media/track/remotemediatrack.js

This change  workarounds an [issue in chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=749928) where it continues to play audio even when audio element is not part of the DOM.
The matters were more complicated because we always create a dummy media element (audio/video)  at the start of media track creation (https://github.com/twilio/twilio-video.js/blob/JSDK_2490_audio_detached/lib/media/track/mediatrack.js#L102)
With this fix we will use `enabled` [property of MediaStreamTrack](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/enabled) 
We will mark the `track.enabled = false` when its not attached to any element - This prevents it from rendering into the MediaStream.
To see this fix in action: checkout …

JSDK-2490 enable/disable MediaStream track

---

lib/connect.js
lib/createlocaltrack.js
lib/createlocaltracks.js
lib/index.js
lib/media/track/localaudiotrack.js
lib/media/track/localdatatrack.js
lib/media/track/localvideotrack.js
scripts/docs.js

Documented `isSupported` and `version` properties of the twilio-video SDK.
While at it, also updated the docs to declare twilio-video as a module, and all direct methods/properties/classes off it are now listed under the module instead of Globals.  

JSDK-2320: doc'ed isSupported

---

lib/util/support.js
test/unit/index.js
test/unit/spec/util/support.js

This came up as a github [issue](https://github.com/twilio/twilio-video.js/issues/748). Since we do not officially support Edge, `isSupported` should return false for edge. 

JSDK-2515 - Video.isSupported should return false for Edge

---

.circleci/config.yml
lib/util/support.js
test/unit/index.js
test/unit/spec/util/support.js

Port https://github.com/twilio/twilio-video.js/pull/752 into 1.x-chrome-planb branch 
+ default config.yml for circleci so that it won't try to build this branch yet.

JSDK-2515 - Video.isSupported should return false for Edge (1.x-chrome-planb)

---

lib/signaling/v2/peerconnection.js
package.json

@makarandp0 
The following PR makes the following changes:
* Only rollback and apply the offer (without H264 simulcast) only if at least one m= section has selected H264.
* Consume the twilio-webrtc.js change to make sure that the rolled back tracks to SSRCs Map is
restored when setLocalDescription() is called immediately after a rollback.

JSDK-2522 - Fix SDP error raised by a Participant with 2 VideoTracks when another Participant leaves.

---

CHANGELOG.md
package.json

@makarandp0 
This PR has the following changes:
* Adding CHANGELOG.md entry for JSDK-2515.
* Updating twilio-webrtc.js to 4.1.2-rc1.

Prep for 2.0.0-rc43.

---

test/integration/spec/connect.js
test/integration/spec/docker/reconnection.js
test/integration/spec/localparticipant.js
test/integration/spec/localtrackpublication.js
test/lib/util.js

Lately we are seeing few tests failing pretty consistently. This is an attempt at getting more information when tests fail. With this change failing tests will print a message about which promise failed to resolve, than test just timing out. 
for example instead of: https://circleci.com/gh/twilio/twilio-video.js/1061#tests/containers/3
```
Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```
now we will get: https://circleci.com/gh/twilio/twilio-video.js/1161#tests/containers/3
```
Error: Timed out waiting for : participants to receive trackSubscribed
```
> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source …

add debug info when tests fail.

---

test/integration/spec/localtrackpublication.js
test/integration/spec/remotetracks.js

This change 
- re-enables null priority test now that VMS-2128 is fixed in stage. 
- logs room sid to go along with debug info to help debug.
Example output:
https://circleci.com/gh/twilio/twilio-video.js/1851

enable null priority test + add room sid for debugging

---

lib/signaling/v2/localparticipant.js
test/integration/spec/localtrackpublication.js
test/lib/util.js
test/unit/spec/signaling/v2/localparticipant.js

@syerrapragada :
Fixes regression JSDK-2565. This was caused by not updating the cached state of track enabled/disabled. causing it to use stale state and not send RSP update. 

JSDK-2565 enable disable tracks

---

lib/signaling/v2/localparticipant.js
test/integration/spec/localtrackpublication.js
test/lib/util.js

This fixes an issue where we weren't updating cached value of `updatedPrioirty` causing priority updates to not have an effect.
This was the root cause for both JSDK-2347 and JSDK-2442
our integration tests did not catch this because we did not have a test that made multiple priority updates on the same track. (1st priority update works fine, but subsequent would not). Added a test to cover this scenario.
Note: there are lots of indentation changes. Pls turn off whitespace to see just relevant change: https://github.com/twilio/twilio-video.js/pull/792/files?utf8=%E2%9C%93&diff=split&w=1

JSDK-2347, JSDK-2442: stale cached publisher priority prevented updates

---

test/crossbrowser/test/integration/spec/localparticipant.ts
test/unit/spec/signaling/v2/peerconnection.js

our unitests recently [started failing](https://circleci.com/gh/twilio/twilio-video.js/2712) because of incorrect usage of `assert` - Now `assert.equal` requires that at least two parameters be passed to the API.  This change fixes our usage of `assert.equal`

fix recent unit test failures 

---

test/crossbrowser/test/integration/spec/localparticipant.ts
test/unit/spec/signaling/v2/peerconnection.js

port https://github.com/twilio/twilio-video.js/pull/795 to master. 
This is just a cherry-pick `git cherry-pick f77c98f21d2116beed38acf30ff5b5e99b821687`

fix assert.equal usage (master)

---

.circleci/config.yml
.circleci/runbuild.js
scripts/circleci-run-tests.sh

@syerrapragada, 
This change enables using circleci for running JS integration tests against backend for specific tag.
- added a new `backend_workflow`
This workflow will run 8 configurations `(stable chrome, stable  firefox) * (p2, group) * (integration, network)` against  specified environment.
- added support for specifying tag for any workflow.
- updated runBuild.js tool to allow for running this new workflow
To execute this workflow - You can use command like:
```
curl -u ${CIRCLECI_TOKEN}: -X POST \
--header 'Content-Type: application/json' \
-d '{
"branch": "JSDK-2537_migrate_integration_tests",
"parameters": {
"pr_workflow": false,
"custom_workflow": false,
"backend_workflow": true,
"environment": "stage",
"tag": "2.0.0-beta15"
}
}' \ …
```

JSDK-2537 migrate integration tests

---

.gitignore
CHANGELOG.md
package.json
test/crossbrowser/test/integration/spec/localparticipant.ts
test/unit/spec/signaling/v2/peerconnection.js

Prepping for releasing 1.20.0. Main change is adding date in Changelog. + port https://github.com/twilio/twilio-video.js/pull/799 to fix unit tests. 
Before merge:
-  [x] update twilio-webrtc dependency

Prep for 1.20.0

---

lib/media/track/remotetrackpublication.js
test/integration/spec/localtrackpublication.js
test/lib/util.js

https://github.com/twilio/twilio-video.js/commit/9a3f660d8aa1307f8824fa78ce80f387f160ff8c#diff-e2551442b3b2b2bbe92b9d0d5d4a2135  introduced this issue. The change caused events to be fired only when state of track changed. Now reverted the change to mimic existing behavior. We will fire trackDisabled/Enabled trackSwitchOff events even for new tracks. 
+ added integration test. 

JSDK 2582 track disabled is not fired, when track is added as disabled.

---

lib/signaling/v2/peerconnection.js
lib/util/index.js
scripts/karma.js
test/unit/spec/signaling/v2/peerconnection.js

This works around an issue in chrome where it sometimes do not send any data on screenshare track if there was a maxBitate value on the RTCRtpEncodingParameters for the RTCRtpSender associated with the screen share Track: 
This resulted in some issues like the one reported by this github issue: https://github.com/twilio/twilio-video.js/issues/736

JSDK-2557 Chrome screen share does not start

---

lib/signaling/v2/peerconnection.js
scripts/karma.js
test/unit/spec/signaling/v2/peerconnection.js

We did not handle glare when `this._descriptionRevision === 1` - This ensured that DTLS role was negotiated. But that works only for 1st peer connection, when a new peer connection is created in response to VMS failover - the `descriptionRevision` would not be 1. To ensure that every new peerConnection does not handle glare before DLTS negotiation is finished, we will wait for `this._lastStableDescriptionRevision` to be set.

JSDK-2561" wait for initial DLTS handshake before handling glare

---

lib/signaling/v2/peerconnection.js
test/integration/spec/localtrackpublication.js

@syerrapragada, 
We have this logic to recyle the `RTCRtpTransceiver`s - wherein we check for any `recvonly` or `inactive` transceivers and mark them for reuse for next tracks that are added. The problem was a race condition caused a transceiver to be marked as recycle'ed even when it was in process of being used. 
This happens if a `negotiationCompleted` is triggered while the promise to `replaceTrack` on transreciver.sender was still pending. 

JSDK-2573: race condition when recycling transceiver.

---

.travis.yml
package.json
scripts/travis-run-tests.sh

We have moved our integration tests to CircleCI - Travis is now only used with release-tool to cut releases and RCs. This change removes integration tests from travis. Travis will only build and run unit tests and tests against frameworks.
We eventually want to retire travis job and move to using circleCI for cutting releases (https://issues.corp.twilio.com/browse/JSDK-2586), But in the interim, this take burden off travis. This was an ask from (https://twilio.slack.com/archives/C0ANJHZLN/p1573684376320300)
and was also necessitated by our integration tests being flaky lately. Travis won't cut the releases, if tests don't pass.   
> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that …

JSDK-2584 move integration tests off travis

---

lib/media/track/localaudiotrack.js
lib/media/track/localdatatrack.js
lib/media/track/localvideotrack.js

we moved some top level functions and properties (`connect`, `createLocalTrack`)  inside module when we documented missing properties: https://github.com/twilio/twilio-video.js/pull/753
See [new](https://media.twiliocdn.com/sdk/js/video/releases/2.0.0-beta15/docs/module-twilio-video.html) v/s [old](https://media.twiliocdn.com/sdk/js/video/releases/2.0.0-beta14/docs/global.html)
It also moved some top level classes - LocalAudioTrack, LocalVideoTrack, LocalDataTrack - inside the module.  
Moving these classes inside the module has made them less discoverable, has resulted in some [github issue](https://github.com/twilio/twilio-video.js/issues/810). And also some broken links within docs. For example links to Fires: section in https://media.twiliocdn.com/sdk/js/video/releases/2.0.0-beta15/doc …

JSDK-2548 doc: move classes in classes tab not module

---

lib/participant.js
lib/signaling/participant.js
lib/signaling/v2/localparticipant.js
lib/signaling/v2/localtrackpublication.js
lib/signaling/v2/remoteparticipant.js
lib/signaling/v2/remotetrackpublication.js
lib/signaling/v2/room.js
lib/signaling/v2/trackprioritysignaling.js
test/integration/spec/localtrackpublication.js
test/lib/util.js
test/unit/spec/signaling/v2/localparticipant.js
test/unit/spec/signaling/v2/remotetrackpublication.js
test/unit/spec/signaling/v2/room.js
test/unit/spec/signaling/v2/trackprioritysignaling.js

Previously we used MSP objects for updating publish priority of tracks, and to receive updates about publish priority changes. 
But the approach [had a problem](https://issues.corp.twilio.com/browse/VMS-2262) that RS was not aware of the changes, and new participants (the ones who missed the `publishPriorityChanged` event would not see the updated priority of the tracks. 
we [decided](https://issues.corp.twilio.com/browse/VMS-2262?focusedCommentId=1646865&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1646865) to use RSP messages for updating and getting notified about updates on publish priorities. 
TODO:
> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source …

JSDK-2590 use rsp for publish priority updates

---

lib/localparticipant.js
lib/util/validate.js
test/unit/spec/localparticipant.js

We were checking for typeof value === `number` but were not special casing for `NaN` values. Now fixed for numeric values for BWP, as well as for `setNetworkQualityConfiguration`

JSDK-2599 setBandwidthProfile should fail on NaN values where number is expected. 

---

CHANGELOG.md
package.json

Loading twilo-video on firefox with `media.peerconnection.enabled` is set to `false` from `about:config` resulted in page errors. This change updates the webrtc version with the fix: https://code.hq.twilio.com/client/twilio-webrtc.js-burndowns/pull/48
Fixes: https://github.com/twilio/twilio-video.js/issues/811

JSDK-2591 update twilio-webrtc version to fix load errors on firefox

---

.circleci/config.yml
lib/room.js

Fixes doc error. 
Before:
http://stage.twiliocdn.com/sdk/js/video/releases/2.0.0-rc49/docs/Room.html
After:
https://4973-46595751-gh.circle-artifacts.com/0/home/circleci/project/dist/docs/Room.html
Also stores artifacts as part of the build, so that these docs can be viewed. 

JSDK-2605: fix doc + store artifacts for the build

---

.circleci/images/docker-compose.yml
test/integration/spec/docker/reconnection.js
test/integration/spec/localparticipant.js
test/integration/spec/localtrackpublication.js
test/integration/spec/room.js
test/lib/util.js

This continues the work I  started with  https://github.com/twilio/twilio-video.js/pull/815
This change 
- adds instrumentation to print roomSid when tests fails.
- passes TEST_STABLILITY to network tests.
- Fixed a bug in `'publisher can downgrade track\'s priority` where it was expecting track swtich off when both tracks had same priority
- Fixed a bug in `publisher can upgrade and downgrade track priorities` where test was not waiting for publishPriorityChange before validating the `publishPriority`
Example Run with `stability: "stable"`: https://app.circleci.com/github/twilio/twilio-video.js/pipelines/c974e135-7627-471e-bf72-328566fa144f/workflows/65ce914e-c13f-4509-a2e6-088139e35aba 
> All third-party contributors acknowledge that any contributions they …

JSDK-2588: identify and mark unstable tests (develop branch)

---

CHANGELOG.md
lib/media/track/remotetrackpublication.js
test/integration/spec/localtrackpublication.js

for sometime during 2.x beta releases events `trackDisabled`, `trackEnabled` `publishPriorirtyChanged` were getting fired even on initial track state. For example when a track was published with disabled state, the subscriber would get `trackDisabled` event. With this fix these events will fire only when the track state changes.

JSDK 2603 - fire events only on change

---

.eslintrc.json
docker/dockerProxyServer.js
docker/fetchRequest.js
lib/signaling/v2/room.js
test/integration/spec/bandwidthprofile.js
test/integration/spec/connect.js
test/integration/spec/docker/reconnection.js
test/integration/spec/localtrackpublication.js
test/integration/spec/room.js
test/lib/util.js
test/unit/spec/media/track/localmediatrack.js
test/unit/spec/media/track/remotedatatrack.js
test/unit/spec/media/track/remotemediatrack.js
test/unit/spec/signaling/v2/iceconnectionmonitor.js
test/unit/spec/signaling/v2/peerconnection.js
test/unit/spec/signaling/v2/remoteparticipant.js

@manjeshbhargav, you might like [this](https://eslint.org/docs/rules/arrow-parens) eslint rule.
I always end-up adding extra parens. This rule would avoids that mistake.
All the code file changes were auto-fixed with:
```
eslint --fix ./lib ./test/*.js ./docker/**/*.js ./test/framework/*.js ./test/lib/*.js ./test/integration/** ./test/unit/** 
```

eslint rule to enforce arrow paren only when needed

---

CHANGELOG.md
COMMON_ISSUES.md
lib/localparticipant.js

This makes small changes to changelog to prepare for beta16 release. 
- added reference to bandwidth profile doc in change log
- updated `maxVideoBitrate` doc to mention chrome screen-share track exception.
- added known issues with data tracks on firefox. I have kept it vague intentionally because we there are multiple issues with data tracks on firefox.  

Prepare for beta16

---

README.md

Readme still pointed to an old Firefox68 advisory at the top. Edited this section to point to a new advisory and upcoming breaking changes in Chrome.

Pointed to a new advisory

---

COMMON_ISSUES.md
lib/signaling/v2/peerconnection.js
test/integration/spec/remotetracks.js

This is caused by a firefox issue. I have [filed a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1603887) to track it, where dataChannel gets closed unexpected after a round of negotiation. This issue is demonstrated by [this simple JSFiddle](https://jsfiddle.net/makarandp/wynouqhp/). 
This change workarounds the issue by always ensuring that `m=application` section exists in every offer/answer on firefox. This avoid an extra round of negotiation that results into data channel getting disconnected. 
Good part is we had same workaround in the code for a while for another firefox issue :) 
Added two tests that fail on firefox w/o this fix.
**Update**
The workaround only works for firefox participant, if chrome/mobile participant connect without data channels to firefox, they would see …

JSDK-2615 late arrivals do not subscribe to datatracks on firefox.

---

lib/media/track/remoteaudiotrack.js
lib/media/track/remotevideotrack.js

moved the documentation to derived classes so that it shows up in docs (https://6356-46595751-gh.circle-artifacts.com/0/home/circleci/project/dist/docs/RemoteVideoTrack.html#setPriority__anchor)

RemoteVideoTrack.setPriority missing doc entry

---

CHANGELOG.md
README.md
karma/makeconf.js
lib/connect.js
lib/createlocaltrack.js
lib/media/track/localtrackpublication.js
lib/media/track/remotetrackpublication.js
lib/signaling/v2/peerconnection.js
lib/util/support.js
package.json
test/integration/spec/localtrackpublication.js
test/unit/spec/util/support.js

This PR has the following changes:
* JSDK-2625 - Enable integration tests for Chromium-based Edge.
* JSDK-2633 - `isSupported` should return `true` for Chromium-based Edge.
* JSDK-2567 - Add link to MediaTrackConstraints MDN docs.
* JSDK-2638 - JSDoc for LocalTrackPublication and RemoteTrackPublication should `@extend` TrackPublication.
* JSDK-2635 - Limit experimental support warning for Safari 12.0 and below.
* JSDK-2639 - Remove closed PeerConnections from the StatsReport object.

Microsoft Edge + Docs Fix + Safari Warning Refactor

---

CHANGELOG.md
lib/util/sdp/simulcast.js
test/integration/spec/connect.js
test/integration/spec/util/simulcast.js
test/unit/spec/util/sdp/index.js

on v1 we were missing `a=x-google-flag:conference` line in the sdp updated to include simulcast. Newer chrome (81+) seems to care more about it. Maybe they are finally rolling out changes mentioned [here](https://groups.google.com/forum/#!topic/discuss-webrtc/hckBc35579w) 
This ports the lines from v2 into v1. This fixes the issue with screen-share media flow with simulcast enabled.

JSDK 2658 simulcast media does not flow

---

CHANGELOG.md
lib/localparticipant.js
lib/participant.js
lib/remoteparticipant.js
lib/room.js
lib/signaling/participant.js
lib/signaling/v2/remoteparticipant.js
lib/signaling/v2/room.js
test/integration/spec/docker/reconnection.js
test/unit/spec/localparticipant.js
test/unit/spec/remoteparticipant.js
test/unit/spec/room.js
test/unit/spec/signaling/v2/remoteparticipant.js
test/unit/spec/signaling/v2/room.js

@makarandp0 
This PR implements the new Participant state "reconnecting", and new events "reconnecting" and "reconnected". The IDL changes can be referred to [here](https://code.hq.twilio.com/client/video-sdk-api/pull/57/files).

JSDK-2662 Participant reconnecting state.

---

CHANGELOG.md
lib/signaling/v2/iceconnectionmonitor.js
test/unit/spec/signaling/v2/iceconnectionmonitor.js

I got a good repro (updated steps in the bug)   
This fixes issue with media-flow on switching to VPN. Switching network causes the iceConnection to move to `disconnected` state - so we start ice connection  monitor, but it was not triggering `onIceConnectionInactive` because in this case there was no active ice candidate pairs anymore. 
Updated the IceConnectionMonitor to treat no-active-ice-candidate-pair condition as no activity. This causes it to triggers the ice restart logic.
TODO:

JSDK-2667: Media in room stops flowing when participant enables VPN

---

CHANGELOG.md
lib/connect.js
package.json

@makarandp0 
This PR fixes JSDK-2670, which was created due to #869 . Please confirm that your local version of Simpler Signaling does not crash with this change on Chrome and Firefox on iOS (iPhone and iPad).

JSDK-2670 Handle Chrome iOS user agent, which does not contain "Version/*".

---

lib/remoteparticipant.js
lib/room.js

Fixes the type for trackDisabled/trackEnabled events fired on the `Room` and `RemoteParticipant`.
`RemoteTrack` => `RemoteTrackPublication`

JSDK-2678 fix track disabled event params doc

---

CHANGELOG.md
lib/media/track/mediatrack.js

Reverts twilio/twilio-video.js#881 
@timmydoza found an issue where the video gets stuck sometimes. (thanks @timmydoza). I guess we have to live with flicker until we find better fix. 
I have filed a chrome bug to track this:
https://bugs.chromium.org/p/chromium/issues/detail?id=1052353

Revert "JSDK-2641 set mediaEl.srcObject only if needed"

---

CHANGELOG.md
lib/localparticipant.js
lib/signaling/v2/cancelableroomsignalingpromise.js
lib/signaling/v2/localparticipant.js
test/integration/spec/connect.js
test/unit/spec/localparticipant.js
test/unit/spec/signaling/v2/cancelableroomsignalingpromise.js

Reopening #898 here
Added signalingRegion property on the Room.localParticipant object. Implemented integration tests and fixed the LocalParticipantV2 mock for unit testing.

JSDK-2687 Add signalingRegion Property on LocalParticipant

---

CHANGELOG.md
lib/signaling/v2/room.js
test/integration/spec/remotetracks.js

The issue was caused because we were not caching the `this._trackPrioritySignaling` :(. It made `setPriority` ( the api that sets subscriber priority)  no-op, when called against participants that joined after the MSP object was constructed. Our existing tests did not catch it because they always got MSP objects after all participants were in. 
Added a regression test that fails before the fix.
https://app.circleci.com/pipelines/github/twilio/twilio-video.js/1005/workflows/4fb4088b-d8c7-40c3-889c-ba21cf853d87/jobs/10967/tests
and passes after:
https://app.circleci.com/pipelines/github/twilio/twilio-video.js/1007/workflows/a57b7e97-8f03-4293-a4e6-12818c12bfeb/jobs/10970/tests
> All third-party contributors acknowledge that any contributions they provide will be …

JSDK-2707 setPriority does not update subscriber track priority for late arrivals

---

CHANGELOG.md
lib/localparticipant.js
lib/participant.js
lib/room.js
test/unit/spec/localparticipant.js
test/unit/spec/remoteparticipant.js
test/unit/spec/room.js

With this fix, we fire some events (`reconnecting`, `reconnected`) asynchronously - ensuring that our StateMachine lock is not held, so that there would be no side effects by caller synchronously calling into state machine again.

do not emit public events with statemachine locked

---

CHANGELOG.md
lib/signaling/v2/twilioconnectiontransport.js
lib/util/constants.js
test/unit/spec/signaling/v2/twilioconnectiontransport.js

With this change we use session_timeout specified in RSP connected message. 

JSDK-2683  use RSP session timeout for reconnect attempts

---

lib/localparticipant.js
lib/room.js

This fixes 3 doc issues
- added doc for Room.mediaRegion
- added doc for LocalParticipant.signalingRegion
- fixed doc entry for Room.participant.reconnecting.  
LocalParticipant - [Before](http://stage.twiliocdn.com/sdk/js/video/releases/2.3.0-rc1/docs/LocalParticipant.html) and [After](https://11896-46595751-gh.circle-artifacts.com/0/dist/docs/LocalParticipant.html)
Room - [Before](http://stage.twiliocdn.com/sdk/js/video/releases/2.3.0-rc1/docs/Room.html) and [After](https://11896-46595751-gh.circle-artifacts.com/0/dist/docs/Room.html)
page does not include new mediaRegion property

JSDK-2720 - add doc for new properties

---

package.json

framework tests do not work with against stage. Since in-band-turn is not available for prod disable framework tests for travis job, to allow it cut rc

disable framework test for travis

---

test/integration/spec/connect.js

these tests were not passing `environment` option to `connect` causing them to fail on stage.
https://app.circleci.com/pipelines/github/twilio/twilio-video.js/1146/workflows/6ecef648-1013-4138-87e6-bf4e023eb188/jobs/12362

JSDK-2729: fix media region tests for stage

---

lib/util/index.js
test/unit/spec/util/index.js

Added in extra logic for maxbitrate for chrome tabs as well as application windows to be handled similar to screen share.

JSDK-2660 Chrome tab share should be handled similar to screenshare

---

COMMON_ISSUES.md

Added information about Android Encoder/Decoder issues to the COMMON_ISSUES.md. Includes description as well as link to the WebRTC issue that was filed.

JSDK-2751 Addind Android Encoder issue to COMMON_ISSUES.md

---

lib/signaling/v2/peerconnection.js
lib/util/sdp/index.js
test/unit/spec/util/sdp/index.js

Chrome is soon [going to deprecate](https://groups.google.com/forum/#!searchin/discuss-webrtc/PSA%7Csort:date/discuss-webrtc/jcZO-Wj0Wus/k2XvPCvoAwAJ) SSRC attributes mslabel and label. 
I did not see references to these attributes in our code, but This now removes it from the sdp, to force the condition and ensure that things works - This will help validate that no backend code is referencing these attributes either. This will also help shave off ~250 bytes from the offer/answer messages ( before chrome actually removes those attributes )

remove deprecated attributes from sdp

---

CHANGELOG.md
lib/index.js
lib/util/support.js
test/unit/spec/util/support.js

@makarandp0 
With this change, `isSupported` should return `false` for all Chrome-based browsers that are not Electron or Edge (ex: Brave, Samsung, Opera).

JSDK-2756 isSupported returns false for Chrome based browsers that are not Electron or Edge.

---

lib/signaling/v2/iceconnectionmonitor.js
lib/signaling/v2/peerconnection.js
test/unit/spec/signaling/v2/iceconnectionmonitor.js
test/unit/spec/signaling/v2/peerconnection.js

This change updates our media monitor to start when ice connection state goes to `connected` instead of `disconnected`. it will make this behavior consistent with native sdk, and will kick off the ice restart quicker when connection loses.  

JSDK-2742 start media monitor earlier

---

lib/signaling/v2/room.js
test/unit/spec/signaling/v2/room.js

@makarandp0 @ceaglest 
With the changes in this PR, the SDK publishes insights events at the following frequency:
* One `stats-report` event every 10 seconds.
* One `active-ice-candidate-pair` every 20 seconds.

JSDK-2762 Reduce publish frequency for insights events.

---

lib/media/track/localdatatrack.js
test/integration/spec/remotetracks.js

Fixes the documentation issue was reported by customer as https://github.com/twilio/twilio-video.js/issues/980
LocalDataTrack doc [Before](https://media.twiliocdn.com/sdk/js/video/releases/2.3.0/docs/LocalDataTrack.html) and [After](https://14780-46595751-gh.circle-artifacts.com/0/dist/docs/LocalDataTrack.html)

JSDK-2784: fix data channel usage example

---

lib/signaling/v2/peerconnection.js
test/integration/spec/localparticipant.js
test/integration/spec/localtrackpublication.js
test/integration/spec/room.js

@makarandp0 
The reason sometimes calling `unpublishTrack` / `publishTrack` multiple times in quick succession resulted in publication not being complete is because a new negotiation was not being triggered after adding the track to the PeerConnection. This was happening because of the following sequence:
```
PeerConnectionV2.offer() -- remove track --> _needsAnswer = true
createOffer1 = PeerConnection.createOffer()
PeerConnectionV2.offer() -- add track --> _shouldOffer = true, before createOffer1 is resolved
await createOffer1 --> _shouldOffer = false
```
Because of this sequence of events, there is no negotiation initiated for the second `offer()` when a new track is added, and therefore the publication is never completed.
This fix makes sure that after the current negotiation is …

JSDK-2769 Renegotiate when a Track is added during a current negotiation.

---

package.json

changes twilio/webrtc dependency from branch to [commit](https://github.com/twilio/twilio-webrtc.js/commit/1499aa43fb200614103ef8e2556eeb97558ad4b1)

update dependency on commit

---

package.json

consumes [twilio-webrc change](https://github.com/twilio/twilio-webrtc.js/pull/120) to fix insights issue.

JSDK-2826 wrong state inprogress

---

CHANGELOG.md
lib/connect.js
lib/signaling/v2/twilioconnectiontransport.js
lib/twilioconnection.js
lib/util/eventobserver.js
test/unit/spec/signaling/v2/twilioconnectiontransport.js
test/unit/spec/twilioconnection.js
test/unit/spec/util/eventobserver.js

@makarandp0 
This PR implements the TwilioConnection close reason defined [here](https://code.hq.twilio.com/client/rtc-insights-spec/pull/55), which is based on the [TCMP FRD](https://code.hq.twilio.com/client/sdk-frd/pull/36/files#diff-3b6eb58a63e88c51d172c548d9ccf7e0R202).

JSDK-2819 EventListenerCloseEvent contains the TwilioConnection close reason.

---

.circleci/config.yml
package.json

This PR works with twilio/release-tool#2 to allow release_tool to release builds using circleci

Use circleci for releasing a build

---

CHANGELOG.md
lib/stats/peerconnectionreportfactory.js
lib/util/support.js
package.json
test/lib/mockwebrtc.js

@makarandp0
This PR makes sure we stop supporting Chrome (23 - 55) and Firefox (22 - 43) versions that support only the prefixed webkit and moz WebRTC APIs that are now deprecated.
consumes: https://github.com/twilio/twilio-webrtc.js/pull/123

JSDK-2832 Stop supporting prefixed WebRTC APIs.

---

lib/media/track/localmediatrack.js

This addresses JSDK-2880 found by QA - which is caused by usage of `off` on EventEmitter which was missing in EventEmitter prototype generated by Simpler Signaling. The same function does exist in code generated by VBT or AhoyApp.
For unblocking testing on the safari workaround - I am fixing this usage. But we do need to investigate further to see which part of the Simpler-Singaling Build is causing this issue, and if there are any other functio usages that need to be fixed.

JSDK-2880 - do not use EventEmitter.off

---

lib/media/track/localmediatrack.js
lib/media/track/remotemediatrack.js

we workaround safari audio [bug](https://bugs.webkit.org/show_bug.cgi?id=212780) by calling play() on media element that were paused.
This fails if the page was not capturing audio - because of race between media capture and media playback on document getting visible. This delay (although not very elegant) fixes this issue.
also updated local tracks to use mediaStreamTrack `ended` event.

delay audio.play() 

---

lib/media/track/localmediatrack.js
test/lib/fakemediastream.js
test/unit/spec/media/track/localmediatrack.js
test/unit/spec/util/documentvisibilitymonitor.js

@makarandp0 
This PR makes sure that the document visibility phase 1 callback resolves its Promise only after the ended MediaStreamTrack is re-acquired, even when "ended" is fired first.

JSDK-2828 Play inadvertently paused elements after an ended MediaStreamTrack is re-acquired.

---

test/integration/spec/localparticipant.js

@makarandp0 
This PR unmarks the unstable LocalParticipant integration tests. I did so because these tests now pass consistently, and one of them is skipped because the implementation that it tests is not yet scheduled to be worked on.

JSDK-2802 Stabilizing unstable LocalParticipant tests.

---

lib/media/track/localaudiotrack.js

JSDK-2909 When restarting a LocalAudioTrack in Firefox, stop existing MediaStreamTrack before calling getUserMedia.

---

CHANGELOG.md
lib/signaling/v2/peerconnection.js
lib/util/sdp/index.js
test/unit/spec/util/sdp/index.js

@makarandp0 
This PR fixes Firefox 79+ <-> Chrome interop issue in audio only Peer-to-Peer Participants. I have filed a [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1106157) for this issue.

JSDK-2914 Work around Chromium bug 1106157 by disabling RTX for Firefox 79+.

---

CHANGELOG.md
lib/util/index.js
lib/util/support.js
test/unit/spec/util/support.js

@makarandp0 
This fixes a bug in the logic for filtering out parenthesized substrings in the user agent, which resulted in `isSupported` returning `false` for Android Chrome in Motorola phones.
Ex. user agent: `Mozilla/5.0 (Linux; Android 6.0.1; Moto G (4)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36`
Now, substrings like `(Linux; Android 6.0.1; Moto G (4))` that contain nested parentheses are handled correctly.

JSDK-2878 Alternate way of filtering parenthesized substrings in the user agent.

---

CHANGELOG.md
lib/media/track/mediatrack.js
lib/media/track/remotemediatrack.js

@makarandp0 This PR makes the following changes:
1. Move the element shimming logic from RemoteMediaTrack to MediaTrack, since local audio/video elements can also be inadvertently paused.
2. Playing unintentionally paused media elements only if not backgrounded. (We have already implemented playing unintentionally paused media elements after backgrounding and foregrounding).
Please take a look and let me know what you think.

JSDK-2889 Playing unintentionally paused media elements if not backgrounded.

---

CHANGELOG.md
lib/media/track/localmediatrack.js
lib/util/detectsilentaudio.js
lib/util/detectsilentvideo.js
test/unit/spec/media/track/localmediatrack.js

@makarandp0 
This PR fixes the silent local audio issue (after playing youtube, etc) for iOS 13.6+, where the track does not go to ended state like before. Rather, it gets unmuted. Now, we detect silence after unmuted and reacquire the track.
This PR also merges the workaround for the local video silent issue (after a phone call) with the workaround for the local audio silent issue into a common workaround function.

JSDK-2928 Restart silent LocalAudioTrack on unmute.

---

CHANGELOG.md
lib/media/track/localmediatrack.js
lib/media/track/mediatrack.js
lib/util/localmediarestartdeferreds.js

@makarandp0 
This PR works around this WebKit [bug](https://bugs.webkit.org/show_bug.cgi?id=213853) by playing inadvertently paused elements only after the local media is restarted after it has ended or unmuted.

JSDK-2932 Work around WebKit Bug 213853

---

CHANGELOG.md
lib/connect.js
lib/signaling/v2/cancelableroomsignalingpromise.js
lib/signaling/v2/twilioconnectiontransport.js
lib/twilioconnection.js
lib/util/eventobserver.js
test/unit/spec/twilioconnection.js
test/unit/spec/util/eventobserver.js

This changes updates eventObserver to publish events to kibana. This change needs to go in following sequence 
Step 1: [x] [Update the schema](https://code.hq.twilio.com/client/rtc-insights-spec/pull/59) 
Step 2: [x] [update the backend](https://code.hq.twilio.com/ra/sdki-ws-gateway/pull/88) to handle new events
Step 3: [ ] cut rc with this change + push backend to stage for QA tests.

VIDEO-2800 publish signaling events to kibana

---

karma/makeconf.js
test/integration/spec/localtrackpublication.js

these relaxed settings for browser reconnect/capture/disconnect configs for karma fixes disconnect issues with firefox.
I also found these issues at much lower frequency in newer stable firefox (v79) 

JSDK-2804: firefox disconnects when running localtrackpublication.js

---

docker/dockerProxyClient.js
docker/dockerProxyServer.js
docker/fetchRequest.js
test/integration/spec/docker/reconnection.js

It turns out that `resetNetwork` could take long time (sometimes couple of minutes) on firefox. This change increases the timeout value. Other changes are just to help debug such failures. 

JSDK-2939: 'resetNetwork' timeout failures.

---

CHANGELOG.md
lib/signaling/v2/peerconnection.js
test/unit/spec/signaling/v2/peerconnection.js

In a sequence where:
Step 1. Peer A => sends offer1, revision 1
Step 2. Peer B => returns answer1, revision 1
Step 3. Peer A => sends offer2, revision 2
Step 4. Peer B => sends sync with answer1 but marks it as revision 2
This is what I see in https://issues.corp.twilio.com/browse/JSDK-2893 looking at participant logs. And I see the possibility in code of this if a sync message was sent after step 3 before PeerB set the new answer ( answer2, revision 2) as the local description.
This change ensures that sync message will always set the revision of the local description that is set, not the one that is in process of setting. 
> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the …

JSDK-2893: Fixes incorrect answer revision in sync messages

---

CHANGELOG.md
package.json
test/integration/spec/room.js

This change updates webrtc dependency to use [fix for simulcast getStats](https://github.com/twilio/twilio-webrtc.js/commit/0469bcd2e72213c8f6c4c916724e751596c22ced) + added an integration test and changelog entry

JSDK 2920: simulcast getstats

---

test/integration/spec/connect.js

this this test has been passing consistently lately. removing `unstable` tag

JSDK-2801: not unstable anymore

---

lib/preflight/preflighttest.js

This disables various workarounds for iOS safari when running preflight test. They are not applicable as preflight test works on synthetic tracks. 

JSDK-2999 safari media popup shows up during preflight

---

test/integration/spec/room.js
test/lib/util.js

These tests forces different order or audio and video m-lines for participants. These would help catch bugs like [VMS-2812](https://issues.corp.twilio.com/browse/VMS-2812)  which turned into [incident](https://twilioincidents.appspot.com/incident/5087283968475136/view) on chrome 85.
verified that test failed and [rollbar entry was captured](https://rollbar.com/Twilio/VIDEO-rtc-sfu-service/items/1987/occurrences/135997201632/) in dev when the [buggy SFU was deployed](https://twilio.slack.com/archives/C01A979A68Z/p1600363354354800).

tests that force differen m-line order

---

test/integration/spec/localtrackpublication.js

https://app.circleci.com/pipelines/github/twilio/twilio-video.js/2277/workflows/83574116-c687-430a-b07c-6015f54dde77/jobs/25182/parallel-runs/5
This test has been failing once in a while, and it's clear that we do not include trackB sometimes - need to investigate more.
When the test fails I noticed following log lines:
```
WARN LOG: '2020-09-04', '11:26:36.505Z', '|', 'WARN', 'in', '[PeerConnectionV2 #11: df846b6c-2866-4c5c-96d1-2f222b6636a4]:', 'Reusing transceiver: 1] 29b12900-9884-4641-8564-cbd6898de798 => 963f08e7-cf21-4c27-9ce8-7d781026cf9c'
WARN LOG: 'xxxx [118] Timed out waiting for : wait for alice to subscribe to Bobs tracks: RMe4f4be6aeef6c6d843ab579e43d7839b [30.014 seconds]'
✗ JSDK-2573 - race condition when recycling transceiver: 
Error: Timed out waiting for : wait for …
```

mark unstable

---

lib/preflight/preflighttest.js
lib/signaling/v2/cancelableroomsignalingpromise.js
lib/signaling/v2/twilioconnectiontransport.js
test/unit/spec/signaling/v2/twilioconnectiontransport.js

This adds a new boolean field `preflight` for `ice` and `connect` messages. This field is set to true from preflight tests.
related rsp pr: https://code.hq.twilio.com/client/room-signaling-protocol/pull/67

add preflight field to ice and connect messages

---

CHANGELOG.md
lib/localparticipant.js
lib/room.js
lib/util/twilio-video-errors.js

@innerverse @idelgado @ceaglest 
This PR documents the behavior of Large Group Rooms. I will open a separate PR for integration tests.

JSDK-3021 Document Large Group Rooms behavior.

---

CHANGELOG.md
lib/media/track/mediatrack.js

Before this change, whenever the user returned to the video app after returning from an incoming phone call, the paused video elements would be played before the LocalAudioTrack was unmuted, resulting it the LocalAudioTrack never being unmuted due to https://bugs.webkit.org/show_bug.cgi?id=213853.
GitHub Issue: #1206 

JSDK-3031 Wait until LocalAudioTrack is unmuted before playing inadvertently paused video elements.

---

CHANGELOG.md
lib/media/track/localaudiotrack.js
lib/media/track/localmediatrack.js
test/integration/spec/localtracks.js
test/unit/spec/media/track/localmediatrack.js

On some android devices track.restart did not work. This was reported on [this github issue](https://github.com/twilio/twilio-video.js/issues/1180) 
The solution is to stop the current track before restarting using different constraints. 

JSDK-3003 - stop track before restart

---

test/integration/spec/util/insightspublisher.js

We see an assert failing in insights test @  https://app.circleci.com/pipelines/github/twilio/twilio-video.js/2639/workflows/c7bc4297-cc8a-403b-9c64-0aa0f3baf50f/jobs/28768/steps
with log:
```
InsightsPublisher
connect
when attempted with an expired token
✗ should disconnect with an Error
AssertionError: false == true
at Context.<anonymous> (/tmp/0e9c83861db80405b8278497249cd6a0.browserify:115256:11)
when attempted with an invalid token
✓ should disconnect with an Error
when attempted with a valid token
✓ should be successful
disconnect
✓ should disconnect without any error
```
This instrumentation would help us find more information next time.
> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source …

instrumentation for insights asserts

---

.circleci/runbuild.js
package.json

update browserify to fix test failures 
Browserify caused [these failures](https://app.circleci.com/pipelines/github/twilio/twilio-video.js/2694/workflows/057d3b5f-58d8-4262-aa4d-d27bd4610be2/jobs/29408) and with changes we have [green build](https://app.circleci.com/pipelines/github/twilio/twilio-video.js/2719/workflows/11f244ce-dfc2-4da8-ad9d-4c168d51f6d8)

Update browserify support1x

---

lib/signaling/v2/peerconnection.js

@makarandp0 @PikaJoyce 
This PR ensures that the local SDP with `usedtx=1` is not sent over the wire, only the original SDP is sent over.
This makes sure that older SDKs do not enable DTX even though the feature is not supported. Newer SDKs add this flag by themselves if DTX is enabled, so it should not affect them.

JSDK-3063 Don't send the local SDP with DTX enabled over the wire.

---

lib/signaling/v2/peerconnection.js

@makarandp0 @dipankadas ,
After we enable DTX once, subsequent SDPs will already have it enabled even before we munge the SDP. So, we need to make sure we actively remove the DTX flag before sending the SDP over the wire.

JSDK-3063 Actively remove DTX from local SDPs sent over the wire.

---

lib/signaling/v2/room.js
test/unit/spec/signaling/v2/room.js

@makarandp0 @ramapal 
This PR makes sure that we allow disconnected Participants to be connected again if the new Participant state has a higher revision number than the previous disconnected state. Now, a Participant in a large group Room that was marked as disconnected when he/she stopped publishing media, can be considered connected again when they start publishing media.

JSDK-3076 Removing the list of disconnected Participant SIDs.

---

lib/util/index.js
test/unit/spec/util/index.js

fixed  `connectOptions.bandwidthProfie.xxx` => `connectOptions.bandwidthProfie.video.xxx`
and verified that now [bandwidth profile options](https://kibana.stage-us1.eak.twilio.com/video/app/kibana#/doc/2c8f6840-4a01-11ea-9012-ad9b36c07d10/video-insights-2020.11.24?id=d382516d-8768-4c44-a0d7-e7590807383b&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))) do get recorded

fix for bwp options not getting recorded in connect message

---

CHANGELOG.md
lib/connect.js
lib/media/track/localvideotrack.js
lib/util/eventobserver.js
test/integration/spec/connect.js
test/integration/spec/localparticipant.js
test/integration/spec/logger.js
test/lib/util.js
test/unit/spec/connect.js
test/unit/spec/util/eventobserver.js

With the introduction of[ customizable logger](https://github.com/twilio/twilio-video.js/pull/1275). Applications can use the same logger to listen for signaling events that used be fired on 'eventListener'. 
This change deprecates 'eventListener' and logs the event on logger instead.

Deprecate ConnectOptions.eventlistener property

---

lib/createlocaltrack.js
lib/createlocaltracks.js

updated the documentation to note that only one video track can be used on mobile browsers.

JSDK-3066: note mobile track limitation for createLocalTracks and createVideoTrack docs

---

package.json
tsdef/RemoteAudioTrack.d.ts
tsdef/RemoteDataTrack.d.ts
tsdef/twilio-video-tests.ts

JIRA Ticket : [JSDK-3118](https://issues.corp.twilio.com/browse/JSDK-3118)
PR contains:
I also remembered that I had added a `CHANGELOG.md` entry before we cut the RC. Let me know if there is anything else I should add to the entry since it currently just says:
```
2.11.0 (In Progress)
====================
New Features
------------
- You can now import type definitions for the SDK APIs to your project as shown below. (JSDK-3007)
```ts
import * as Video from 'twilio-video';
```

JSDK-3118 - TSDef setPriority

---

tsdef/LocalAudioTrack.d.ts

Quick fix in regards to [Karina's comment](https://issues.corp.twilio.com/browse/JSDK-2951?focusedCommentId=2786495&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2786495)
Changing some of the LocalAudioTrack method return types to `this` for consistency.

JSDK-2951 - TS Definition LocalAudioTrack Fix

---

.circleci/config.yml
lib/index.js
lib/util/log.js
lib/vendor/loglevel.js
package.json
test/umd/index.js
test/umd/require-browser/index.html
test/umd/require-browser/min.html
tsdef/index.d.ts
tsdef/loglevel.d.ts

The loglevel npm module is handling CommonJS, AMD, and browser environments all in the same file. Which doesn't work if the module is bundled with browserify, and then later used with RequireJS. To fix this issue, the loglevel module should update its build process to output AMD/Browser and CommonJS files separately. Unfortunately, this is a common mistake by some developers. See this discussion and some links to requirejs docs [here](https://stackoverflow.com/questions/15371918/mismatched-anonymous-define-module.). Summary: If using requirejs, all files should be included using requirejs. …

JSDK-3129 | Fixing loglevel module to work with browserify and requirejs

---

CHANGELOG.md
lib/room.js
tsdef/Room.d.ts
tsdef/twilio-video-tests.ts

Adding in some quick tests and updating changelog to prepare for TS definition release

JSDK-2951 Adding in tests for localAudioTrack methods

---

CHANGELOG.md
lib/util/twilio-video-errors.js

minor change updates description for ParticipantMaxTracksExceededError.

VIDEO-3843: update text for ParticipantMaxTracksExceededError 

---

CHANGELOG.md
lib/media/track/remoteaudiotrack.js
lib/media/track/remotemediatrack.js
lib/media/track/remotetrackpublication.js
lib/media/track/remotevideotrack.js
lib/media/track/trackpublication.js
lib/participant.js
lib/signaling/remotetrackpublication.js
lib/signaling/room.js
lib/signaling/v2/remoteparticipant.js
lib/signaling/v2/remotetrackpublication.js
lib/signaling/v2/room.js
test/integration/spec/bandwidthprofile.js
test/integration/spec/localtrackpublication.js
test/unit/spec/media/track/remotemediatrack.js
test/unit/spec/remoteparticipant.js
test/unit/spec/signaling/v2/remoteparticipant.js
test/unit/spec/signaling/v2/remotetrackpublication.js

client can receive track switch off notification before tracks are subscribed to (or even before client knew of it being published). client used to drop such notification. This change fixes it to remember the most recent switch off state and apply it when a track is subscribed.

VIDEO-3695: early track swichoffs

---

CHANGELOG.md
lib/media/track/localvideotrack.js
lib/media/track/mediatrack.js
lib/media/track/videotrack.js
test/unit/spec/media/track/localvideotrack.js
test/unit/spec/media/track/mediatrack.js
test/unit/spec/media/track/videotrack.js
tsdef/VideoTrack.d.ts

This PR:
- Implemented removeProcessor API
- Handle track.restart()
- Fixed an issue where processedTrack is not sent to RTCRtpSender after disable/enable
- Added checks before and during capture process whether capturing frames should proceed/stop or not. See `canCaptureFrames()` method
- Do not stop capturing frames on `mute`. This is because the track is automatically muted by the browser when not visible or looking at a different tab. In this case, we don't want to stop capturing frames.
- Stopped using `requestVideoFrameCallback` because this doesn't trigger when the page is not …

VIDEO-3561 | removeProcessor API

---

test/integration/spec/connect.js

VIDEO-4205 | Mark bitrate test unstable

---

.circleci/config.yml
.circleci/runbuild.js
scripts/circleci-run-tests.sh
test/integration/spec/room.js

This test has been failing because browser does not send  remb packets when bob unpublished tracks too soon. This adds a workaround (delay of 4 seconds) to make the test green.
It also adds some tooling to be able to run test against a specific file. You can now use `.circleci/runbuild.js` to queue a build with a specific integration test file. 

VIDEO-4191 test fix

---

.circleci/config.yml
CHANGELOG.md
lib/connect.js
lib/media/track/remotevideotrack.js
lib/participant.js
lib/room.js
lib/signaling/v2/renderhintssignaling.js
lib/util/constants.js
lib/util/validate.js
test/integration/spec/bandwidthprofile.js
test/integration/spec/localtrackpublication.js
test/integration/spec/remotetracks.js
test/integration/spec/room.js
test/unit/spec/signaling/v2/renderhintssignaling.js
tsdef/twilio-video-tests.ts
tsdef/types.d.ts

Changes in this PR:
- updated the way render hints are sent to VMS - no more waiting for 100ms. as agreed [here](https://docs.google.com/document/d/11zgCOIYux9vwlNdzd-smrGgnLQf3x0863N-WQ7zzSq8/edit#heading=h.erhtiue0ftnq) to send update immediately if no update is in flight already.  https://github.com/twilio/twilio-video.js/pull/1408/commits/8d8aa1bdb557c331159aa5a76e74bace77784696
- VIDEO-3742: added a property `idleTrackSwitchOff` to bandwidthProfile.video object. (in the same commit as above https://github.com/twilio/twilio-video.js/pull/1408/commits/8d8aa1bdb557c331159aa5a76e74bace77784696 )
- typescript definitions and documentation for the new property: https://github.com/twilio/twilio-video.js/pull/1408/commits/7c21df010caeb830e2b45240d2e8e10da558ce2c
- VIDEO-4275: send initial …

renderhints after trackstarted (VIDEO-4275, VIDEO-3742)

---

lib/media/track/remotevideotrack.js
lib/util/nullobserver.js
test/unit/spec/media/track/remotemediatrack.js
test/unit/spec/media/track/remotevideotrack.js

This change adds ResizeObserver - RemoteVideoTrack now watches the video element as they resize and report the size to VMS.

video_3739: use ResizeObserver to report video element sizes.

---

lib/participant.js
lib/remoteparticipant.js
lib/signaling/v2/remoteparticipant.js
lib/signaling/v2/room.js
test/unit/spec/remoteparticipant.js
test/unit/spec/signaling/v2/remoteparticipant.js

we must not send hints about tracks that are no more valid - This change ensure that 1) we do not send renderhints for the tracks we are not subscribed to 2) clear any cached hints when track is removed.

video-4493: clear render hints when track unpublished

---

lib/connect.js
lib/util/validate.js
tsdef/twilio-video-tests.ts
tsdef/types.d.ts

We decided to use `renderDimensions=auto` instead of `renderHints=true`. That way its clear that renderDimensions are mutually exclusive with renderHints. + added typescript definition for the new property.
corresponding idl PR: https://code.hq.twilio.com/client/video-sdk-api/pull/84 

video-4521: renderdimensions=auto

---

lib/signaling/v2/cancelableroomsignalingpromise.js
test/unit/spec/signaling/v2/cancelableroomsignalingpromise.js

SDK was requesting MSP channels even when Bandwidth Profile was not specified. now requests `render_hints`, `track_priority` and `track_switch_off` only as needed.

VIDEO-4472: request bwp msp channels as needed

---

test/integration/spec/room.js

We [introduced a workaround](https://github.com/twilio/twilio-video.js/pull/1397) - by adding a delay - as one of the bandwidth profile test was failing because of some race condition on SFU side.  This change removes the workaround as root cause is now fixed on SFU side.

remove workaround introduced for video_4191

---

lib/media/track/remotevideotrack.js
lib/signaling/v2/renderhintssignaling.js
test/unit/spec/media/track/remotevideotrack.js
test/unit/spec/signaling/v2/renderhintssignaling.js
tsdef/twilio-video-tests.ts

we decided to rename two msp fields in render_hints protocol - the msp protocol change is described here: https://code.hq.twilio.com/client/room-signaling-protocol/pull/70
for render_hint protocol:
`render_dimension` => `render_dimensions`
`track_sid` => `track`
This PR updates sdk to accommodate it.  I have verified the client against dev environment. We will merge this change only after related VMS changes are in stage. (Note: circleCi job against this PR is expected fail till then) 
Along with protocol change, this also changes an internal structure from `renderDimension` => `renderDimensions`
> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided …

video-4524 msp field rename

---

lib/media/track/remotevideotrack.js
test/integration/spec/bandwidthprofile.js
test/lib/util.js

https://issues.corp.twilio.com/browse/VIDEO-4657
when connected with
```
const connectOptions = {
"bandwidthProfile":{
"video":{
"idleTrackSwitchOff": false, 
"renderDimensions": "auto"
}
}
}
```
RenderHints are not sent when element is resized. This happens because we mark video element as invisible initially when attached, and mark them as  visible only on IntersectionObserver callback - But when `idleTrackSwitchOff === false` the callback never comes.  This causes ResizeObserver callback to not send render hints  thinking the elements are invisible.
This change fixes the issue by marking elements invisible only when `idleTrackSwitchOff` is enabled. Because that the only time we care about their visibility.
This also adds integration tests which verify auto renderDimensions behavior. …

Video-4657 auto dimensions not sent when idleTrackSwitch of is disabled.

---

lib/util/index.js

include new field in insights report. does not require change in insights spec because 
- a) bandwidthProfile [allows new fields](https://code.hq.twilio.com/client/rtc-insights-spec/blob/master/schema/video/event/room/connect.json#L60) already
- b) renderDimenstions was already a string property.
Example Kibana Query: https://kibana.us1.eak.twilio.com/video/goto/d24229d03db03d16c2fa823d45bedb84

send idleTrackSwitchOff and renderDimenstions=auto to insights

---

CHANGELOG.md
lib/connect.js
lib/media/track/remotevideotrack.js
lib/participant.js
lib/room.js
lib/signaling/v2/cancelableroomsignalingpromise.js
lib/signaling/v2/renderhintssignaling.js
lib/util/constants.js
lib/util/index.js
lib/util/validate.js
test/integration/spec/bandwidthprofile.js
test/integration/spec/connect.js
test/integration/spec/localtrackpublication.js
test/integration/spec/remotetracks.js
test/integration/spec/room.js
test/unit/spec/connect.js
test/unit/spec/media/track/remotevideotrack.js
test/unit/spec/signaling/v2/cancelableroomsignalingpromise.js
tsdef/RemoteVideoTrack.d.ts
tsdef/twilio-video-tests.ts
tsdef/types.d.ts

This change follows the blueprint to iterate on the api and options.
- rename connectOptions property: `idleTrackSwitchOff: boolean` => `subscribedTrackSwitchOffMode: enum("auto", "manual")`. This option deprecated `maxTracks`  property
- add a new property `contentPreferencesMode: enum("auto", "manual")`.  This option deprecates `renderDimensions` property.   
- added [switchOn](https://42412-46595751-gh.circle-artifacts.com/0/dist/docs/RemoteVideoTrack.html#switchOn), [switchOff](https://42412-46595751-gh.circle-artifacts.com/0/dist/docs/RemoteVideoTrack.html#switchOff), and [setContentPreferences](https://42412-46595751-gh.circle-artifacts.com/0/dist/docs/RemoteVideoTrack.html#setContentPreferences) api to RemoteVideoTrack
- updated changelog
> All …

Renderhints  updates

---

CHANGELOG.md
tsdef/LocalDataTrackOptions.d.ts

JIRA Ticket : [VIDEO-5116](https://issues.corp.twilio.com/browse/VIDEO-5116)
Fix from [this PR](https://github.com/twilio/twilio-video.js/pull/1459)
Reported from @xdumaine, 
"Fixes the type to match documentation, and allowing providing a name in options of LocalDataTrack constructor."

VIDEO-5116-LocalDataTrackOptions Type Definitions Fix

---

tsdef/types.d.ts

A small fix makes a type clientTrackSwitchOffControl => ClientTrackSwitchOffControl

Fix typescript casing

---

lib/signaling/v2/room.js
lib/signaling/v2/twilioconnectiontransport.js
lib/util/eventobserver.js
lib/util/movingaveragedelta.js
package.json
test/unit/index.js
test/unit/spec/signaling/v2/room.js
test/unit/spec/signaling/v2/twilioconnectiontransport.js
test/unit/spec/util/movingaveragedelta.js

@makarandp0 @PikaJoyce 
Adds A/V sync metrics ([example](https://kibana.us1.eak.twilio.com/video/goto/269fed43d045922091455a100a0a7d0a)) to insights, as defined [here](https://issues.corp.twilio.com/browse/VIDEO-4718).

VIDEO-4718 Adding A/V sync metrics, elapsed time and level to "stats-report" insights message.

---

CHANGELOG.md
lib/util/support.js
test/framework/webdriver.js
test/unit/spec/util/support.js

Previously, we don't check for mobile browser specifically, we only test for WebRTC support. Now that mobile browsers are starting to support WebRTC, isSupported is returning true for these browsers. We want to still return false for these until QE officially support them.

VIDEO-4419 | Update isSupported to match browser matrix support

---

lib/connect.js

JIRA Ticket : [VIDEO-3711](https://issues.corp.twilio.com/browse/VIDEO-3711)
Adding a small comment on `ConnectOptions` to notify users about ignoring invalid options.

VIDEO-3711 update connect options documentation

---

.circleci/images/build_docker_image.sh

our docker image build job is [failing to send](https://app.circleci.com/pipelines/github/twilio/twilio-video.js/4156/workflows/a7a904c9-9bdf-4aa2-bd0a-5a2544cfa1f3/jobs/45230?invite=true#step-102-184) results on slack message, because of `\r` characters in the text. This fixes it. 

remove /r/n/t from the slack message text

---

CHANGELOG.md
lib/media/track/remotemediatrack.js
lib/media/track/remotetrackpublication.js
lib/media/track/remotevideotrack.js
lib/signaling/v2/renderhintssignaling.js
test/integration/spec/bandwidthprofile.js
test/unit/spec/media/track/remotevideotrack.js
test/unit/spec/signaling/v2/renderhintssignaling.js

with client track switch off control set to auto - sdk request that track be turned off when it determines that track is not visible. However we found that sometimes react apps ends up causing elements to get hidden momentarily when layout changes. This results in  turn off and turn on request for the track in quick succession, causing a black screen momentarily. 
This fix delays requesting track turn off request by 50 ms. This required some refactoring as previously track switchOn/SwitchOff requests were clubbed together with render dimension changes. now they are handled separately.

VIDEO-5226: send auto track switch off hints bit delayed. 

---

lib/connect.js

Hide VP9 from public doc since it's not currently supported

VIDEO-5969 | Hide VP9 from public doc since it's not currently supported

---

.circleci/images/firefox/stable/Dockerfile

It seems we forgot to update firefox-stable node version. All our images are using node 14/16. Firefox stable is still using node10. This PR fixes that.

Update firefox stable node

---

CHANGELOG.md
lib/media/track/mediatrack.js
test/integration/index.js
test/integration/spec/leaktests.js
test/lib/document.js
test/unit/spec/media/track/localmediatrack.js
test/unit/spec/media/track/mediatrack.js

chrome 92 started [limiting](https://chromium-review.googlesource.com/c/chromium/src/+/2816118) the WebMediaPlayers. This [breaks](https://bugs.chromium.org/p/chromium/issues/detail?id=1232649) lot of webrtc applications. This fix ensures that 1) we do not leak media elements created internally and 2) we clear the `srcObject` before removing media elements.
The application that use `RemoteAudioTrack.detach`() method need to ensure that they clear srcObject on the returned elements as well.
related github issues: https://github.com/twilio/twilio-video.js/issues/1367 & https://github.com/twilio/twilio-video.js/issues/1528
> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the …

video-6336: media element leak causes error on chrome 92 

---

lib/preflight/getCombinedConnectionStats.ts
lib/preflight/preflighttest.ts

although chrome reports jitter values for video tracks, they does not seem correct - they are too large to be in seconds. 
For now just use jitter from audio tracks.

use audio jitter only

---

lib/media/track/audiotrack.js
package.json
test/unit/index.js
test/unit/spec/media/track/audiotrack.js

We create dummy element for audio only to generate 'started' event. Once started we were calling `_detachElement`, but that call is no-op for dummy element - Causing the audio element active until track ended. Fixed this by cleaning up dummy element specifically.

VIDEO-6336 - Cleanup dummy audio element after start

---

CHANGELOG.md
lib/preflight/preflighttest.ts

Safari does not support [RTCDtlsTransport](https://developer.mozilla.org/en-US/docs/Web/API/RTCDtlsTransport#browser_compatibility), so `dtlsConnected` event will not be available.
firefox does not support [onconnectionstatechange](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/onconnectionstatechange#browser_compatibility), so `peerConnectionConnected` event will not be emitted on firefox.
Noted these issues in docs.

doc update to mention browser limitation on networktimings

---

CHANGELOG.md
lib/signaling/v2/peerconnection.js
package.json
test/unit/spec/signaling/v2/peerconnection.js

The default simulcast layers chosen by safari have same dimensions. This causes low framerate for tracks from safari. This 
change configures the layers with with `scaleResolutionDownBy` set to 1, 2, and 4. This is still pending design task: VIDEO-6730

VIDEO-6263: low fps from safari with simulcast enabled. 

---

CHANGELOG.md
lib/media/track/localmediatrack.js
lib/media/track/localvideotrack.js
lib/media/track/mediatrack.js
lib/media/track/remotemediatrack.js
lib/util/index.js

This disables `workaroundWebKitBug1208516` for screen share track. I found that microphone and camera tracks have deviceId but screen share track does not. This fix uses this to determine if `workaroundWebKitBug1208516` needs to be applied. 
Also fixed a bug where introduction of `isIOSChrome` with lack of parenthesis was short-circuting checks after `if guessBrowser() === 'safari'`

Video-3977: disable "reacquire track" workaround for screenshare track

---

CHANGELOG.md
lib/signaling/v2/peerconnection.js
test/unit/spec/signaling/v2/peerconnection.js

we [updated](https://github.com/twilio/twilio-video.js/pull/1560) simulcast configuration to address a safari issue. 
But this [regresses](https://github.com/twilio/twilio-video.js/issues/1575) chrome's screen share track handling. w/o any configuration looks like chrome creates 2 layers for screen share at highest resolution differing only in frameRate - which is good for screen share track. 
This fix lets chrome do its thing, and apply the simulcast configuration only for safari.  

VIDEO-7000: apply simulcast configuration only for safari

---

lib/connect.js
lib/preflight/getturncredentials.ts
lib/preflight/makestat.ts
lib/preflight/preflighttest.ts
lib/signaling/v2/cancelableroomsignalingpromise.js
lib/signaling/v2/twilioconnectiontransport.js
lib/util/constants.js
lib/util/eventobserver.js
lib/util/index.js
lib/util/sid.js
test/unit/spec/signaling/v2/twilioconnectiontransport.js
test/unit/spec/util/eventobserver.js
test/unit/spec/util/index.js
tsconfig.json
tsdef/PreflightTypes.d.ts

Sends preflight metrics to gateway. this uses schema defined [here](https://code.hq.twilio.com/client/rtc-insights-spec/pull/78)
Changes:
- [refactor](https://github.com/twilio/twilio-video.js/commit/9587e8e9644add110c4105bbb65057cbd87cc13b) insights reporting - instead of passing both eventBrowser/eventPublisher to `twilioconnectiontransport` now we hooks up eventPublisher with eventObserver, and only pass eventObserver to `twilioconnectiontransport`. This ended up reducing code complexity a bit: ![Screen Shot 2021-09-13 at 1 22 12 PM](https://user-images.githubusercontent.com/6174737/133151152-5d595bf7-797f-49e9-9040-46d88d73e15f.png) 
- update preflightTest to send preflight report to gateway at the end of the test using schema defined …

Preflight metrics

---

lib/connect.js
lib/signaling/v2/cancelableroomsignalingpromise.js
lib/signaling/v2/peerconnection.js
lib/signaling/v2/peerconnectionmanager.js
lib/signaling/v2/room.js
lib/util/sdp/index.js
lib/util/sdp/simulcast.js
package.json
test/unit/spec/signaling/v2/peerconnectionmanager.js
test/unit/spec/signaling/v2/room.js
test/unit/spec/util/browserdetection.js
test/unit/spec/util/sdp/index.js
tsdef/twilio-video-tests.ts
tsdef/types.d.ts

This change implements the proposed API for adaptive simulcast.
Now  `connect` will accept a new value 'auto' for preferredVideoCodecs. This new values would enable adaptive simulcast  and request for 'publisher_hints' msp channel in initial connect message.
To handle the case for P2P room (where we do not want to enable simulcast) SDK will check for availability of publisher_hints msp in `connected` message, and if not available then rollback the offer that was sent with simulcast enabled.

VIDEO-7161 + VIDEO-7162 Simulcast API implementation + rollback support 

---

lib/signaling/v2/mediasignaling.js
lib/signaling/v2/peerconnection.js

CircleCI updated to node version 16.13.0, which handles unhandled promise rejections differently. We need to fix any code rejections that are unhandled.
This rejection was unhandled, but looking closely this rejection was more like assert. Removed the rejection code  (throws) in this case.

no more unhandled rejections in unit tests

---

lib/localparticipant.js
test/integration/spec/connect.js

fixes the error thrown from `localParticipant.setParameter`. 
also includes unit test fixes from (https://github.com/twilio/twilio-video.js/pull/1625)

Video-7401 fix setParameter error

---

lib/util/index.js
test/unit/spec/util/index.js

JIRA Tickets:
[VIDEO-6188](https://issues.corp.twilio.com/browse/VIDEO-6188)
[VIDEO-6192](https://issues.corp.twilio.com/browse/VIDEO-6192)
Addresses some of the errors we're seeing in rollbar. Some types (name/roomName) that were meant to be a string came in as integers and others (maxAudioBitrate/maxVideoBitrate) that were meant to be integers could come in as strings. Also added in some extra unit tests to capture and verify these changes.

VIDEO-6192 / 6188 - Rollbar error fixes

---

CHANGELOG.md
lib/media/track/remotevideotrack.js
test/lib/document.js
test/unit/spec/media/track/remotemediatrack.js
test/unit/spec/media/track/remotevideotrack.js

SDK sends hints about video elements considering their visibility and dimensions to SFU. Those hints were not considering picture-in-picture windows. So if PIP window is open and a tab is switched or video element becomes invisible, the track would get switched off. This PIP handling fixes that. 

Video-6677 consider PIP windows for render hints.

---

CHANGELOG.md
lib/media/track/sender.js
lib/signaling/v2/peerconnection.js
test/unit/spec/media/track/sender.js
test/unit/spec/signaling/v2/peerconnection.js

We re-enable simulcast layers (and let SFU know about it) when a track is replaced. 
However since we configure [simulcast layers  on safari depending on track dimensions](https://github.com/twilio/twilio-video.js/pull/1560) - the reset encodings need to reconfigure the layers based on replaced Tracks dimensions. This change ensures that replaceTrack does not enable layers that are were not supposed to be enabled to begin with.  

VIDEO-7790: safari replacetrack should reset layers per track dimensions

---

lib/util/cancelablepromise.js
package.json
test/integration/spec/connect.js
test/unit/spec/util/cancelablepromise.js
tsconfig.json
tsdef/index.d.ts
tsdef/twilio-video-tests.ts
tsdef/types.d.ts

This PR fixes an [issue](https://github.com/twilio/twilio-video.js/issues/1647) that was reported by a user. Currently our `connect` method returns a `Promise`, but it's supposed to return a `CancelablePromise`.

VIDEO-7831 Fix Connect to return CancelablePromise on Type Definitions

---

lib/signaling/v2/renderhintssignaling.js
test/integration/spec/audioonlyrooms.js
test/unit/spec/signaling/v2/renderhintssignaling.js

We add [retry logic](https://github.com/twilio/twilio-video.js/pull/1655) for render hint responses. This change makes this timer backoff exponentially...starting with 2 seconds, and then 4 and then 8 and so on.

Exponential backoff for render hint retries.

---

lib/signaling/v2/peerconnection.js
lib/util/index.js
lib/util/sdp/simulcast.js
test/integration/spec/bandwidthprofile/publisherhints.js
test/unit/spec/signaling/v2/peerconnection.js
test/unit/spec/util/index.js

This change configures simulcast layers as described in https://code.hq.twilio.com/client/sdk-frd/pull/96. 
- configure video and chrome screen-share track layers when adaptive simulcast is effective
- only set 'active: false' during default configuration
- apply default configuration after publisher hints are applied.
- after replaceTrack remove active flags for the layers that should be enabled.
- added bunch of tests

VIDEO-7928: configure chrome simulcast layers

---

lib/createlocaltracks.ts
tsdef/twilio-video-tests.ts
tsdef/types.d.ts

[VIDEO-8535](https://issues.corp.twilio.com/browse/VIDEO-8535)
There were some changes done to the `tsdef` file that broke how customers utilized  `createLocalTracks` by passing in a `boolean` value for `audio` and `video`. This change has been reverted and some build tests have been added to the definitions test file to catch this. 
I've verified that the react app is able to build successfully and our tests are passing locally as well. 
[VIDEO-8535](https://issues.corp.twilio.com/browse/VIDEO-8535)

VIDEO-8535 - Reverting TSDef Changes from CreateLocalTracks PR

---

test/unit/spec/createlocaltracks.ts
test/unit/spec/preflight.ts
tsconfig.json

Creating this small PR to fix some changes that that didn't get into the previous PR.
I've manually tested this and gone through all the places we call `createLocalTracks` and it looks good to go. Our integration and unit tests have the bases covered, just the TS Definition tests did not!

Removing ESModuleInterop

---

CHANGELOG.md
lib/signaling/v2/peerconnection.js
test/unit/spec/signaling/v2/peerconnection.js

We apply default encodings for safari irrespective of adaptive simulcast. For default we remove any `active` flags from RTCRtpEncodingParameters. We found that on older iOS (14.x) devices missing `active` flag from is treated as false. causing the layer to get disabled. This change sets the active=true for default encodings (which are also applied during track replace operations)
released spec change: https://code.hq.twilio.com/client/sdk-frd/pull/97

set active=true for default encodings

---

CHANGELOG.md

JIRA: [VIDEO-8791](https://issues.corp.twilio.com/browse/VIDEO-8791)
As per this [discussion](https://twilio.slack.com/archives/C0ANJHZLN/p1645028933188379) this PR adds some extra info for users in the CHANGELOG.

VIDEO-8791 - Adding extra information into CHANGELOG

---

.circleci/config.yml
.circleci/images/chrome/beta/Dockerfile
.circleci/images/chrome/stable/Dockerfile
.circleci/images/chrome/unstable/Dockerfile

JIRA Ticket : [VIDEO-8647](https://issues.corp.twilio.com/browse/VIDEO-8647)
This PR addresses our Circle CI Job that builds our chrome images. Previously our job was not updating chrome to the latest stable version. We have updated to pulling from `cimg/node` instead of `circleci/node` as that is now deprecated. I've added updates to `beta` and `unstable` chrome Dockerfile as well.

VIDEO-8647 - Fixing Chrome Docker Image

---

test/integration/spec/localparticipant/regressions.js
test/integration/spec/localtrackpublication.js

Marking some of the integration tests as unstable. I will include this in 2.21.1-rc1

Marking unstable integration tests

---

CHANGELOG.md
lib/connect.js
lib/localparticipant.js
lib/media/track/remotetrackpublication.js
lib/participant.js
lib/remoteparticipant.js
lib/signaling/v2/room.js
lib/signaling/v3/remoteparticipant.js
lib/signaling/v3/room.js
lib/signaling/v3/tracksubscriptionssignaling.js
test/unit/spec/remoteparticipant.js
test/unit/spec/signaling/v3/room.js

@makarandp0 @PikaJoyce 
- Tracks specified in ConnectOptions are now published after the connect Promise is resolved
- RemoteTracks are keyed off of Track SIDs in internal maps instead of Track IDs, since they can be associated with more than one MediaStreamTrack in large Rooms
- Keep existing subscription behavior foe DataTracks

VIDEO-8817 Integration with RSP and SFU changes for large rooms.

---

CHANGELOG.md
lib/signaling/v2/peerconnection.js
test/unit/spec/signaling/v2/peerconnection.js

For adaptive simulcast we configure simulcast layers depending on the track dimensions. This code encounters an exception and emits a console error for tracks that are stopped.  Thats because stopped track return `NaN` values for width and height [here](https://github.com/twilio/twilio-video.js/blob/82995cd8515ed384fe82acce23aa9340c2eb2f98/lib/signaling/v2/peerconnection.js#L521)
This change fixes this by not attempting to change encodings for stopped tracks. 

VIDEO-9511 - do not configure encodings for stopped tracks

---

lib/createlocaltracks.ts
lib/media/track/noisecancellationimpl.ts
tsdef/types.d.ts

While working on integrating  noise cancellation API with react app, I found two issues
1) We have some stricter type check against the tracks passed to connect being of type es5/LocalAudioTrack
a small refactor (which also makes the code cleaner) fixed this.
2) Ahoy app call getSettings() on published LocalTrack.mediaStream Tracks , This won't work with track cleaned with noise cancellation. To fix this added access to srcTrack in `NoiseCancellation` interface. 
This part needs an update to API documentation and more discussion - but for now I would like to merge this to get the pilot out along with Ahoy app implementation.
> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the …

Noise cancellation api update

---

assets/noisecancellation/rnnoise/1.0.0/rnnoise_sdk.mjs
lib/media/track/noisecancellationimpl.ts
test/integration/spec/noisecancellation.js
tsdef/types.d.ts

While working on integrating noise cancellation with ahoy app, I found need for this property. Adding it to the public interface. 

add NoiseCancellation.isEnabled property

---

CHANGELOG.md
lib/media/track/videotrack.js
test/unit/spec/media/track/videotrack.js

JIRA Ticket: [VIDEO-3576](https://issues.corp.twilio.com/browse/VIDEO-3576)
This pull requests adds a change that causes a `VideoTrack` to emit the `dimensionsChanged` event when the track dimensions first become available (during the `_start` method).
This solves an issue that a couple customers have faced where an application cannot detect the dimensions of portrait-oriented videos, and therefore cannot style them correctly in the UI. See #1470 and [VIDEO-9546](https://issues.corp.twilio.com/browse/VIDEO-9546).
Applications cannot detect the initial dimensions of a track because the …

Video 3576 - emit dimensionsChanged event on track init

---

lib/signaling/v3/room.js
test/unit/spec/signaling/v3/room.js

This PR implements [this change](https://code.hq.twilio.com/client/room-signaling-protocol/pull/87/files) in the Track Subscriptions MSP spec change.

VIDEO-9802 DataTrack subscription state is now an object instead of a data channel label.

---

lib/signaling/v2/peerconnection.js
lib/signaling/v2/room.js

when connected with `preferredVideoCodecs="auto"` we enable adaptive simulcast. That mean we default to  simulcast and if joined a p2p room revert back to unicast. Previously we used the media_signaling payload in  `connected` response from room service, as a signal to determine if we need to revert to unicast or not. We reverted to unicast if publisher_hint MSP channel was not part of the connected response.
With large rooms, connected response  does not contain information about media_signaling. This caused us to always revert to unicast for large rooms. To fix this issue this code change now looks at `media_region` in connected response as a clue to decide on reverting to unicast. `media_region` is available only when connecting to group rooms - so If media_region is not part of …

VIDEO-9966 - use no media_region as a signal to revert to unicast

---

lib/signaling/v3/tracksubscriptionssignaling.js
test/unit/spec/signaling/v3/tracksubscriptionssignaling.js

Track subscription protocol keeps track of last version of the message received, and ignores if new messages has lower version. However when VMS failovers the message version starts over again. This change ensures that we reset our version number when SDK detects VMS failover.

VIDEO-10023: handle VMS failover

---

lib/signaling/v2/twilioconnectiontransport.js
test/unit/spec/signaling/v2/twilioconnectiontransport.js

Found a bug where warning RSP messages are not bubbling up.

Fix warning is not bubbling up

---

lib/signaling/v3/room.js
test/unit/spec/signaling/v3/room.js

when track subscriptions changed mid line for track or attached mid for the first time we send 'switchOn message. However this was being sent synchronously, while trackReceiver was being set async, causing applications to receives the `switchOn` message with either null or stale mediaStreamTrack. This change fixes that.

VIDEO-10104 -  send switchOn message after ms track changes

---

CHANGELOG.md
lib/util/constants.js
test/unit/spec/util/insightspublisher.js

Addressing comments from QE in these two tickets:
[VIDEO-3612](https://issues.corp.twilio.com/browse/VIDEO-3612)
[VIDEO-8282](https://issues.corp.twilio.com/browse/VIDEO-8282)
- Editing the CHANGELOG to be more specific about which frameworks we fixed.
- Fixed our insights payload to use `mobile` and `tablet` instead of `Mobile` and `Tablet` for consistency.

Added details in changelog entry and updated insights payload constants

---

lib/media/track/audiotrack.js
lib/media/track/mediatrack.js
test/unit/spec/media/track/audiotrack.js

In large rooms, as we switch m-lines RemoteAudioTracks are attached to new MediaStreamTrack. In this process we were creating new audio elements to listen to "started" event. Creation of new audio elements and attaching srcObject properties causes creation of new WebMediaPlayers. With frequent track switching (with large room's n-loudest algorithm) causes very frequent creation and destruction of media players. 
This change avoid creating/destroying web media players by letting dummy elements stay longer. This essentially undo's the optimization introduced in https://github.com/twilio/twilio-video.js/pull/1534. Its okay because chrome 92 [changes](https://bugs.chromium.org/p/chromium/issues/detail?id=1232649) that prompted  https://github.com/twilio/twilio-video.js/pull/1534 were …

large room audio dummy element handling 

---

CHANGELOG.md
lib/util/constants.js
test/unit/spec/util/insightspublisher.js

Adding in the `platformName` into our insights payload to properly identify the device platform.

Adding platformName into insights payload

---

COMMON_ISSUES.md

This pull request adds two new entries to the Common Issues document to resolve the following tickets:
[VIDEO-10211](https://issues.corp.twilio.com/browse/VIDEO-10221): This ticket relates to an issue where local video tracks occasionally cannot be seen in Safari after being mirrored with a 3d CSS transform. The solution is to use a 2d transform instead.
[VIDEO-8757](https://issues.corp.twilio.com/browse/VIDEO-8757): This ticket relates to an issue where it is not possible for a user to change their audio output device in some browsers. This is because the related method `setSindId()` is …

Video 10221 update common issues

---

CHANGELOG.md
lib/util/support.js
lib/webrtc/util/sdp.js
test/lib/mockwebrtc.js
test/unit/spec/util/support.js

isSupported now returns false when on plan-b
sources for browser version unified plan support
https://hacks.mozilla.org/2015/06/firefox-multistream-and-renegotiation-for-jitsi-videobridge/
https://webkit.org/blog/8672/on-the-road-to-webrtc-1-0-including-vp8/
https://webrtc.org/getting-started/unified-plan-transition-guide

VIDEO-10307 isSupported now returns false when on plan-b

---

lib/media/track/mediatrack.js
test/unit/spec/media/track/mediatrack.js

The description of the issue and the potential fix is specified [here](https://issues.corp.twilio.com/browse/VIDEO-10752?focusedCommentId=4301660&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4301660).

VIDEO-10752 Detach empty MediaStream from media element.

---

test/integration/spec/webrtc/rtcpeerconnection.js

While investigating a failing test, I found the root cause (`audioContext.resume` does not settle on firefox when running in docker image) but did not find a solution to it. 
This change adds a simple test to demonstrate the issue, and marks it as `@unstable`

Audiocontext resume test + mark unstable

---

CHANGELOG.md
lib/media/track/localaudiotrack.js
lib/media/track/noisecancellationimpl.ts
test/integration/spec/noisecancellation.js

Fixed an issue where LocalAudioTrack.stop() was not stopping underlying `noiseCancellation.srcTrack`.  

Video 11047 src track was not stopped when stopping krisp enabled LocalAudioTrack

---

CHANGELOG.md
lib/room.js
lib/signaling/v2/peerconnection.js
lib/signaling/v2/peerconnectionmanager.js
lib/signaling/v2/remoteparticipant.js
lib/signaling/v2/room.js
lib/signaling/v3/remoteparticipant.js
lib/signaling/v3/remotetrackpublication.js
lib/signaling/v3/room.js
lib/webrtc/getstats.js
lib/webrtc/index.js
test/integration/spec/webrtc/getstats.js
test/unit/spec/signaling/v3/remoteparticipant.js
test/unit/spec/signaling/v3/remotetrackpublication.js
test/unit/spec/signaling/v3/room.js
test/unit/spec/webrtc/getstats.js

This PR fixes the broken `Room.getStats()` behavior in large rooms, based on the proposal described [here](https://docs.google.com/document/d/1Utox0H6ygX7v4K0_-tOIPi9amIZgiccvW05Jg-Fuuaw/edit#heading=h.y4yxwjxm6rxd).
* No changes for LocalTrack stats, since they already work.
* For each RemoteTrackPublication, we cache the following stats objects:
* `_switchOffStateChangeStats` - the RemoteTrack stats captured at the most recent switch off state change
* `_switchOnMediaStreamTrackStats` - the MediaStreamTrack stats captured when the RemoteTrack is switched on
* Ensure that …

VIDEO-8756 Fix Room.getStats()

---

lib/connect.js
test/integration/spec/bandwidthprofile/regressions.js
test/integration/spec/bandwidthprofile/video.js
test/integration/spec/localtrackpublication.js
test/integration/spec/remotetracks.js
test/integration/spec/room.js

Re-introduce maxTracks for internal testing so that maxSwitchedOnTracks behaves as expected in production.

VIDEO-11223 RemoteVideoTracks not switching on when maxSwitchedOnTracks is specified.

---

CHANGELOG.md
COMMON_ISSUES.md
lib/media/track/audiotrack.js
lib/media/track/remoteaudiotrack.js
test/unit/spec/media/track/audiotrack.js

Issues fixed:
* VIDEO-11352
* VIDEO-11354
* VIDEO-11356
* VIDEO-11359
Also updated `COMMON_ISSUES.md` to reflect current status.

Fix iOS Safari issues by moving VIDEO-6336 workaround to RemoteAudioTrack.

---

lib/webrtc/rtcpeerconnection/firefox.js
test/integration/spec/webrtc/rtcpeerconnection.js

JIRA: [VIDEO-11007](https://issues.corp.twilio.com/browse/VIDEO-11007)
Removing firefox workaround and the integration test

VIDEO-11007 - Remove Firefox workaround 1480277

---

lib/webrtc/rtcpeerconnection/firefox.js

ES6 syntax changes for FirefoxRTCPeerConnection

FirefoxRTCPeerConnection es6 syntax

---

lib/twilioconnection.js
test/integration/spec/docker/reconnection.js

JIRA : [VIDEO-10700](https://issues.corp.twilio.com/browse/VIDEO-10700)
Fix unstable reconnection test. This bug was caused by the tests using a close code 3005 that is a real code that causes undesirable signal closing behavior. A note has been added to prevent this from happening in the future as well as changing the close code to a number that is not in use.

VIDEO-10700-Fix Reconnection Network Test

---

COMMON_ISSUES.md

This PR addresses a WebKit bug that is currently filed. We have updated the COMMON_ISSUES for developers to use an alternative method to restart their local media.
JIRA Ticket : [VIDEO-11793](https://issues.corp.twilio.com/browse/VIDEO-11793)

VIDEO-11793 - Change COMMON_ISSUES entry

---

CHANGELOG.md
COMMON_ISSUES.md

iOS 17 bugfix: update changelog and common issues

---

CHANGELOG.md
lib/media/track/localaudiotrack.js

VIDEO-13006 iOS 17 Chrome: disable Krisp upon foregrounding

---

CHANGELOG.md

This fix covers Desktop Safari 18 and all iOS browsers running iOS 18.

docs: clarify bug fix in MediaStreamTrack cloning

---

CHANGELOG.md
lib/createlocaltrack.js
lib/index.ts
package.json
test/unit/spec/connect.js
test/unit/spec/createlocaltrack.js
test/unit/spec/createlocaltracks.ts
tsdef/types.d.ts

- [VBLOCKS-3826](https://twilio-engineering.atlassian.net/browse/VBLOCKS-3826)
- Added support for passing a custom `getUserMedia` as an option in `connect()`, `createLocalTracks()`, `createLocalAudioTrack()`, and `createLocalVideoTrack()` methods.

[VBLOCKS-3826] feat: add support for custom getUserMedia implementation

---

lib/createlocaltrack.js
lib/media/track/localaudiotrack.js
test/unit/spec/createlocaltrack.js
tsdef/types.d.ts

- [VBLOCKS-3828](https://twilio-engineering.atlassian.net/browse/VBLOCKS-3828)
- add support for enumerateDevices option in createLocalTrack

feat: add support for enumerateDevices option in createLocalTrack

---

CHANGELOG.md
LICENSE.md
README.md
lib/media/track/capturevideoframes.js
lib/media/track/videotrack.js
package.json
test/lib/mockstreams.js
test/unit/index.js
test/unit/spec/media/track/videotrack.js
tsdef/VideoProcessor.d.ts
tsdef/types.d.ts

* Refactor video frame capture logic to its own module.
* Use insertable streams where supported.
* Support inputFrameBufferType=videoframe.
* Support outputFrameBufferContextType=bitmaprenderer.
* Support outputFrameBufferContextType=bitmaprenderer only for chrome.
* Work around: https://github.com/markdown-it/linkify-it/issues/111
* VBLOCKS-3643 VBLOCKS-3644
* docs: introduce beta support for Video Processor V3

feat: VideoProcessors v3.0 (#2053)

---

test/integration/spec/connect.js
test/lib/mockwebrtc.js
test/unit/spec/signaling/v2/peerconnection.js
tsdef/twilio-video-tests.ts
tsdef/types.d.ts

- [VBLOCKS-3827](https://twilio-engineering.atlassian.net/browse/VBLOCKS-3827)
- add support for RTCPeerconnection option in `connectOptions`

[VBLOCKS-3827] custom RTCPeerconnection

---

lib/media/track/mediatrack.js
lib/participant.js
test/unit/spec/media/track/mediatrack.js

- [VBLOCKS-4111](https://twilio-engineering.atlassian.net/browse/VBLOCKS-4111)
- Validate MediaStream constructor in MediaTrack

[VBLOCKS-4111] feat: validate MediaStream constructor in MediaTrack

---

lib/signaling/v2/peerconnection.js
lib/webrtc/getstats.js
test/integration/spec/webrtc/getstats.js
test/unit/spec/webrtc/getstats.js

- [VBLOCKS-3977](https://twilio-engineering.atlassian.net/browse/VBLOCKS-3977)
We require `getStats()` to be able to accept a track as a selector and retrieve only relevant information. Some WebRTC implementations do not support this functionality, so this polyfills it.

[VBLOCKS-3977] Polyfill getStats in VDI

---

lib/connect.js
lib/signaling/v2/peerconnection.js
test/integration/spec/connect.js
tsdef/twilio-video-tests.ts
tsdef/types.d.ts

- [VBLOCKS-4208](https://twilio-engineering.atlassian.net/browse/VBLOCKS-4208)
This PR introduces a new property to the `ConnectOptions` called `rtcConfiguration`, allowing users to define the configuration passed to `RTCPeerConnection`.

[VBLOCKS-4208] add: custom rtcConfiguration to ConnectOptions

---

lib/media/track/mediatrack.js
lib/participant.js
lib/room.js
test/unit/spec/media/track/mediatrack.js

- [VBLOCKS-4179](https://twilio-engineering.atlassian.net/browse/VBLOCKS-4179)
- [VBLOCKS-4191](https://twilio-engineering.atlassian.net/browse/VBLOCKS-4191)
This PR removes the burden of manually attaching and detaching MediaStream to elements on Citrix by extracting that logic from the consumer and putting it in the SDK. After this change, customers using Citrix should be able to call `track.attach(element)` or `track.detach(element)`, maintaining the same API.
- Added support for [trackStarted](https://sdk.twilio.com/js/video/releases/2.29.0/docs/Room.html#event:trackStarted) event on Citrix  environments.
- Updated MediaTrack to validate `MediaStream` constructor with an additional check for `createMediaStream` method.
- Introduced `_prepareCustomMediaElement` and `_removeMediaStream` …

[VBLOCKS-4179] [VBLOCKS-4191] fix: MediaTrack lifecycle on Citrix

---

test/integration/spec/livetranscription.js

The transcription feature will only return results for speech-like audio tracks, fake audio tracks without any speech will not return results.

[VBLOCKS-4696] Use a real speech for real-time transcription E2E tests

---

CHANGELOG.md
lib/media/track/remotevideotrack.js
test/unit/spec/media/track/remotevideotrack.js

This PR ensures that video elements rendered in a document PiP play after appearing on the screen when the `clientTrackSwitchOffControl` is set to `auto`, fixing issue #2044.

[VBLOCKS-4766] Fix document PiP support

---

CHANGELOG.md
lib/signaling/v2/peerconnection.js
lib/util/sdp/index.js

- This PR prevents repeated payload types in the munged SDP section.
- Fixes #2122

[VBLOCKS-5037] fix: SDP generation with invalid payload types

---

lib/util/sdp/index.js
lib/util/sdp/issue8329.js
test/unit/spec/util/sdp/issue8329.js

- Added PT conflict detection and reassignment in Issue 8329 workaround.
Implementation details:
- Detect duplicate PTs mapped to different codecs in malformed SDP
- Reassign conflicting PTs to next available numbers (96-127 range)
- Update all related SDP lines (rtpmap, fmtp, rtcp-fb) consistently
- Added a new unit test to validate the functionality
Fixes #2122

[VBLOCKS-5078] fix: resolve payload type conflicts in issue8329 workaround

---

lib/media/track/localvideotrack.js
lib/media/track/remotevideotrack.js
lib/media/track/videotrack.js
test/unit/spec/media/track/remotevideotrack.js
test/unit/spec/media/track/videotrack.js

- Extends document Picture-in-Picture support from RemoteVideoTrack to LocalVideoTrack.
- LocalVideoTrack now adds intersection observer that only activates when a document PiP is open.
- Fixes issue where local video tracks freeze when displayed in document PiP windows

[RC Fix] Adjust PiP support for Local Participant

---

lib/connect.js
lib/signaling/v2/cancelableroomsignalingpromise.js
lib/util/index.js
test/unit/spec/util/index.js

This PR separates "connecting" and "connected" events to replace the single "connect" insight event

[VBLOCKS-5149] Publish room insights events

---

lib/insights/applicationeventpublisher.js

Add missing `terminated` event to the ApplicationEventPublisher

[VBLOCKS] feat: add beforeunload monitoring to ApplicationEventPublisher

---

lib/insights/networkeventpublisher.js
lib/webrtc/getstats.js
test/unit/spec/stats/remotevideotrackstats.js

- Fix the network monitoring logic to replace the `NetworkMonitor` dependency with a more straightforward alternative since `NetworkMonitor` relays on the connection's `type` property to detect changes, which is not supported in most browsers.
- Add the `freezeCount` property to the standardized `getStats` response.

fix: update network monitoring and freezeCount on stats handler
