twilio/twilio-video.js

- lib/media/localmedia.js
This commit allows a constraints object to be passed in as the first param to allow specific cameras or mics to be selected.
> addCamera and addMicrophone allow constraints

- test/integration/spec/webrtc/rtcpeerconnection.js
> Using lib/webrtc/mediastream in RTCPeerConnection unit tests.

- .travis.yml
- package.json
- scripts/integration.js
> Use travis-multirunner

- integration.conf.js
- package.json
- scripts/karma.js
- test/integration/index.js
- test/integration/spec/connect.js
- test/integration/spec/localparticipant.js
- test/integration/spec/localtracks.js
- test/integration/spec/room.js
- test/integration/spec/util/insightspublisher.js
> Spawn Karma for each integration test module

- CHANGELOG.md
- README.md
@rfbrazier @kedartoraskar any changes you'd like to see?
> Update CHANGELOG.md/README.md for 1.0.0

- README.md
- appveyor.yml
This isn't running Chrome or Firefox browser tests yet.
> Add Appveyor integration

- lib/webrtc/getstats.js
@manjeshbhargav @ryan-rowland workaround for [Bugzilla 1377225](https://bugzilla.mozilla.org/show_bug.cgi?id=1377225)
> Workaround Bugzilla 1377225

- lib/webrtc/rtcpeerconnection/chrome.js
- lib/webrtc/rtcpeerconnection/firefox.js
- lib/webrtc/rtcsessiondescription/firefox.js
@manjeshbhargav mind taking a look? This is another take on #142.
> Fix RTCSessionDescription/RTCPeerConnection not defined errors

- CHANGELOG.md
- COMMON_ISSUES.md
> Update common issues and changelog

- .travis.yml
- package.json
Also, allow Chrome Stable on Linux to fail (the RTCSessionDescription tests crash it for some reason, although Chrome Beta is fine...).
> Update travis-multirunner and start testing Safari

- lib/util/sdp.js
> setCodecPreferences: check if PCMA/PCMU PTs exist

- .travis.yml
> Travis: run tests against P2P and SFU

- test/integration/spec/connect.js
@markandrus 
The "connect" fixed bitrate codec + bitrate test was failing in SFU mode as the codec map did not contain "pcma" and "pcmu". So the modified test passing condition is:
The test should pass either if the selected codec is not in the fixed payload types, or if it is, then the b= line should not be present.
> JSDK-1505 Modifying connect codec+bitrate test to work with SFU

- lib/localparticipant.js
- lib/media/track/localtrackpublication.js
- test/integration/spec/connect.js
- test/integration/spec/localparticipant.js
- test/unit/spec/localparticipant.js
- test/unit/spec/media/track/localtrackpublication.js
@manjeshbhargav this is to match our IDL.
> Rename LocalTrackPublication `sid` to `trackSid`

- lib/localparticipant.js
- test/unit/spec/localparticipant.js
Otherwise LocalTrackPublications won't be created/updated.
***
@manjeshbhargav per our Slack conversation.
> {add,remove}Track{,s} should delegate to {,un}publishTrack{,s}

- lib/connect.js
> Add link to REST API in preferredVideoCodecs JSDoc

- lib/signaling/v2/peerconnection.js
- test/unit/spec/signaling/v2/peerconnection.js
> Ensure 1st PT in local offer matches codec we send

- lib/connect.js
- lib/createlocaltrack.js
- lib/createlocaltracks.js
- lib/localparticipant.js
- lib/media/track/index.js
- lib/media/track/localtrackpublication.js
- lib/media/track/remotedatatrack.js
- lib/media/track/remotemediatrack.js
- lib/signaling/localtrackpublication.js
- lib/signaling/remotetrack.js
- lib/signaling/track.js
- lib/signaling/v2/localparticipant.js
- lib/signaling/v2/localtrackpublication.js
- lib/signaling/v2/remotetrack.js
- lib/util/index.js
- test/integration/spec/connect.js
- test/integration/spec/localparticipant.js
- test/unit/spec/createlocaltracks.js
- test/unit/spec/localparticipant.js
- test/unit/spec/media/track/localdatatrack.js
- test/unit/spec/media/track/localmediatrack.js
- test/unit/spec/media/track/localtrackpublication.js
- test/unit/spec/media/track/remotedatatrack.js
- test/unit/spec/media/track/remotemediatrack.js
- test/unit/spec/remoteparticipant.js
- test/unit/spec/signaling/v2/localtrackpublication.js
- test/unit/spec/signaling/v2/remotetrack.js
@markandrus Reopening the "Track Names" PR here.
> Track Names

- CHANGELOG.md
- lib/participant.js
- lib/remoteparticipant.js
- lib/room.js
- test/unit/spec/remoteparticipant.js
- test/unit/spec/room.js
> Fix trackUnsubscribed timing bug

- COMMON_ISSUES.md
Fixes https://github.com/twilio/twilio-video.js/issues/156
@manjeshbhargav
> Warn about Safari & Angular

- lib/index.js
- lib/util/browsersupport.js
- lib/util/support.js
- test/integration/index.js
- test/integration/spec/util/support.js
- test/umd/index.js
- test/umd/require-browser/index.html
- test/umd/require-browser/min.html
> Twilio.Video.isSupported Flag

- CHANGELOG.md
@manjeshbhargav how does this look?
> Add isSupported to CHANGELOG.md

- lib/connect.js
- lib/signaling/v2/peerconnection.js
- lib/util/index.js
- lib/util/sdp.js
- lib/util/sdp/index.js
- lib/util/sdp/simulcast.js
- test/integration/index.js
- test/integration/spec/connect.js
- test/integration/spec/util/simulcast.js
- test/lib/mocksdp.js
- test/unit/index.js
- test/unit/spec/util/sdp.js
This PR allows `twilio-video.js` users to connect to a Room with VP8 simulcast on Chrome as follows:
```javascript
const room = await Twilio.Video.connect('my-token', {
name: 'my-cool-room',
preferredVideoCodecs: [ {codec: 'VP8', simulcast: true} ]
});
```
> VP8 Simulcast Support for Chrome

- COMMON_ISSUES.md
- lib/localparticipant.js
- lib/signaling/v2/peerconnectionmanager.js
- lib/signaling/v2/room.js
- test/integration/spec/connect.js
- test/integration/spec/localparticipant.js
- test/integration/spec/localtrackpublication.js
- test/integration/spec/room.js
- test/unit/spec/signaling/v2/room.js
> Add back the dummy audio MediaStreamTrack fix

- CHANGELOG.md
@manjeshbhargav mind taking a look?
> Update CHANGELOG.md for 1.7.0

- lib/media/track/index.js
- test/unit/spec/media/track/localdatatrack.js
- test/unit/spec/media/track/localmediatrack.js
@manjeshbhargav mind taking a look?
> Stringify Track name in LocalTrackOptions

- CHANGELOG.md
> Update CHANGELOG.md for 1.7.0-rc2

- lib/signaling/v2/peerconnection.js
- lib/signaling/v2/peerconnectionmanager.js
- package.json
- test/unit/spec/signaling/v2/peerconnection.js
@markandrus 
Let me know what you think. I've basically opened this PR to run travis for FF/Safari. Chrome integration tests are working when I ran it locally (for both P2P and SFU).
> JSDK-1640, JSDK-1641, JSDK-1642 Consuming WebRTC 1.0 APIs.

- lib/signaling/v2/peerconnection.js
- lib/util/sdp/index.js
- lib/util/sdp/issue8329.js
- test/unit/index.js
- test/unit/spec/util/sdp/index.js
- test/unit/spec/util/sdp/issue8329.js
_Not ready to merge._
https://bugs.chromium.org/p/webrtc/issues/detail?id=8329
> Implement workaround for Issue 8329

- lib/signaling/v2/localparticipant.js
- lib/signaling/v2/peerconnection.js
@markandrus Also fixing options override in LocalParticipantV2.
Issue: https://github.com/twilio/twilio-video.js/issues/220
> Fixing memory leak in PeerConnectionV2.

- .travis.yml
- CHANGELOG.md
- COMMON_ISSUES.md
- lib/localparticipant.js
- lib/signaling/v2/peerconnectionmanager.js
- lib/signaling/v2/room.js
- lib/util/sdp.js
- test/integration/spec/connect.js
- test/integration/spec/localparticipant.js
- test/integration/spec/localtrackpublication.js
- test/integration/spec/room.js
- test/unit/spec/signaling/v2/room.js
@manjeshbhargav let's backport this fix from #202 to 1.6.1. I've cherry-picked the commits from that PR, editing where necessary to fix conflicts.
> Backport dummy audio track fix

- lib/signaling/v2/room.js
> JSDK-1574 Publish new LocalParticipantV2 state only for non-SID updates.

- CHANGELOG.md
- lib/data/receiver.js
- lib/media/track/index.js
- lib/signaling/v2/localparticipant.js
- lib/signaling/v2/peerconnection.js
- lib/signaling/v2/room.js
- package.json
- test/integration/spec/localparticipant.js
- test/unit/spec/media/track/localdatatrack.js
- test/unit/spec/media/track/localmediatrack.js
- test/unit/spec/signaling/v2/peerconnection.js
> Backport bugfixes

- .travis.yml
> Enable Firefox Nightly with RTCRtpTransceiver support

- .travis.yml
- karma/makeconf.js
> Remove chrome_webrtc_1_0; add Chrome Canary

- lib/iceserversource/nts.js
> Add TURNS support by updating ECS URL

- CHANGELOG.md
> Update CHANGELOG.md for 1.8.0

- CHANGELOG.md
- lib/signaling/v2/transport.js
- test/unit/spec/signaling/v2/transport.js
> Raise SignalingConnectionTimeoutError if keep-alives timeout

- CHANGELOG.md
- lib/signaling/v2/transport.js
- test/unit/spec/signaling/v2/transport.js
> Raise SignalingConnectionDisconnectedError when WebSocket is disconnected

- lib/remoteparticipant.js
- test/unit/spec/remoteparticipant.js
> JSDK-1997 Set RemoteTrack's .sid before calling Participant#addTrack().

- lib/signaling/v2/peerconnection.js
- package.json
@manjeshbhargav PTAL. Check out https://github.com/twilio/twilio-webrtc.js/pull/26 for motivation
> Allow passing Chrome-specific constraints

- .github/ISSUE_TEMPLATE.md
@idelgado following the pattern in https://github.com/twilio/video-quickstart-android/blob/master/.github/ISSUE_TEMPLATE.md
> JSDK-1919: Note about PII

- .travis.yml
- CHANGELOG.md
- lib/participant.js
- lib/signaling/remotetrackpublication.js
- lib/signaling/track.js
- lib/signaling/v2/room.js
- test/env.js
- test/integration/index.js
- test/integration/spec/localparticipant.js
- test/integration/spec/localtrackpublication.js
- test/integration/spec/rest.js
- test/unit/index.js
- test/unit/spec/remoteparticipant.js
- test/unit/spec/signaling/v2/remotetrackpublication.js
@markandrus 
TODO:
Unit + integration tests.
> Track Subscription REST API support.

- lib/localparticipant.js
- test/unit/spec/localparticipant.js
> JSDK 2063: Fix removeTracks

- lib/localparticipant.js
- lib/media/track/index.js
- lib/media/track/remoteaudiotrack.js
- lib/media/track/remotedatatrack.js
- lib/media/track/remotemediatrack.js
- lib/media/track/remotevideotrack.js
- lib/participant.js
- lib/remoteparticipant.js
- lib/room.js
- lib/util/index.js
> Deprecation warnings

- lib/localparticipant.js
- lib/media/track/index.js
- lib/media/track/localdatatrack.js
- lib/media/track/localmediatrack.js
- lib/media/track/remoteaudiotrack.js
- lib/media/track/remotedatatrack.js
- lib/media/track/remotemediatrack.js
- lib/media/track/remotetrackpublication.js
- lib/media/track/remotevideotrack.js
- lib/participant.js
- lib/remoteparticipant.js
- lib/room.js
- test/integration/spec/connect.js
- test/integration/spec/localparticipant.js
- test/integration/spec/localtrackpublication.js
- test/integration/spec/rest.js
- test/integration/spec/room.js
- test/lib/util.js
- test/unit/spec/localparticipant.js
- test/unit/spec/media/track/remotedatatrack.js
- test/unit/spec/media/track/remotemediatrack.js
- test/unit/spec/media/track/remotetrackpublication.js
- test/unit/spec/remoteparticipant.js
- test/unit/spec/room.js
> Remove deprecated apis and events

- CHANGELOG.md
- README.md
> Updating CHANGELOG.md to add deprecation notes.

- CHANGELOG.md
> Removing "publication" from "trackSubscribed"/"trackUnsubscribed" callbacks.

- lib/signaling/v2/cancelableroomsignalingpromise.js
- lib/signaling/v2/peerconnection.js
- lib/signaling/v2/transport.js
- lib/util/index.js
> Use OrderedTrackMatcher with Unified Plan in Chrome

- CHANGELOG.md
@anna-vasilko 
Can you +1 this change since Mark is not here?
> Prep for 1.13.0.

- CHANGELOG.md
> Updating CHANGELOG.md to include 1.13.0 changes.

- lib/eventemitter.js
- lib/util/index.js
- package.json
- test/unit/spec/util/index.js
@markandrus 
* Updating `@twilio/webrtc` dependency to `3.0.0-rc1`.
* Hiding `EventEmitter`'s prototype non-method properties.
* Setting `version` to 2.0.0-dev.
> Prep for twilio-video.js@2.0.0-rc1.

- lib/room.js
- test/integration/spec/room.js
> JSDK-2122 Extending "trackStat" instead of "trackStats".

- lib/localparticipant.js
- lib/room.js
- lib/util/log.js
- test/unit/spec/localparticipant.js
- test/unit/spec/room.js
- test/unit/spec/util/log.js
> Room shouldn't listen to "trackAdded"/"trackRemoved"

- lib/connect.js
- lib/signaling/v2/cancelableroomsignalingpromise.js
- lib/signaling/v2/index.js
- lib/signaling/v2/twilioconnectiontransport.js
- lib/twilioconnection.js
- test/env.js
- test/integration/spec/connect.js
- test/lib/defaults.js
- test/unit/index.js
- test/unit/spec/signaling/v2/twilioconnectiontransport.js
- test/unit/spec/twilioconnection.js
@markandrus 
This PR contains changes for network handoff. As and when a commit is added for each of the tickets below, the corresponding checkbox will be checked.
> JSDK-2006 Network Handoff

- CHANGELOG.md
- lib/signaling/v2/peerconnection.js
- lib/signaling/v2/peerconnectionmanager.js
- lib/stats/peerconnectionreportfactory.js
- lib/util/sdp/issue8329.js
- package.json
- test/integration/spec/room.js
- test/lib/defaults.js
- test/unit/spec/signaling/v2/peerconnectionmanager.js
- test/unit/spec/util/sdp/issue8329.js
We did an experiment with RTCRtpTransceivers in 1.4.0-rc1. It revealed some issues. This PR tries to fix them up.
> Firefox/RTCRtpTransceiver fixes for 1.x

- CHANGELOG.md
- lib/connect.js
- lib/localparticipant.js
- lib/media/track/audiotrack.js
- lib/media/track/mediatrack.js
- lib/media/track/videotrack.js
- lib/signaling/v2/cancelableroomsignalingpromise.js
- lib/signaling/v2/peerconnection.js
- lib/signaling/v2/peerconnectionmanager.js
- lib/signaling/v2/transport.js
- lib/signaling/v2/twilioconnectiontransport.js
- lib/stats/peerconnectionreportfactory.js
- lib/util/index.js
- lib/util/log.js
- lib/util/sdp/issue8329.js
- test/integration/spec/room.js
- test/lib/defaults.js
- test/unit/spec/media/track/mediatrack.js
- test/unit/spec/signaling/v2/peerconnectionmanager.js
- test/unit/spec/signaling/v2/twilioconnectiontransport.js
- test/unit/spec/util/log.js
- test/unit/spec/util/sdp/issue8329.js
There were some improvements we should add from 1.x to 2.x.
> Merge support-1.x back into master

- lib/signaling/v2/peerconnection.js
- lib/util/index.js
- test/unit/spec/signaling/v2/peerconnection.js
@manjeshbhargav Implemented signal end-of-candidates on Edge browser.
> Signal end of candidates

- lib/signaling/v2/peerconnection.js
> JSDK-2160 Stop transceivers only after remote "answer" is applied

- COMMON_ISSUES.md
@markandrus 
I have added a blurb about JSDK-2161 in both the Safari and Firefox sections. Please review when you get a chance.
> Updating COMMON_ISSUES.md with details of JSDK-2161

- CHANGELOG.md
- lib/participant.js
- lib/remoteparticipant.js
- test/unit/spec/localparticipant.js
- test/unit/spec/remoteparticipant.js
> JSDK-2173 Using the private member RemoteTrack#_id instead

- .travis.yml
- lib/connect.js
- lib/signaling/v2/cancelableroomsignalingpromise.js
- lib/signaling/v2/transport.js
- lib/signaling/v2/twilioconnectiontransport.js
- lib/twilioconnection.js
- lib/util/index.js
- test/env.js
- test/integration/spec/connect.js
- test/integration/spec/localparticipant.js
- test/integration/spec/localtrackpublication.js
- test/integration/spec/rest.js
- test/integration/spec/room.js
- test/lib/defaults.js
- test/lib/rest.js
- test/lib/token.js
- test/unit/spec/signaling/v2/twilioconnectiontransport.js
- test/unit/spec/twilioconnection.js
@markandrus @syerrapragada 
This PR contains the implementation of re-connect to VSG with exponential backoff.
TODO:
Test multiple network handoff scenarios before handing off to QA.
> TCMP Re-connect

- lib/signaling/v2/room.js
- test/unit/spec/signaling/v2/room.js
@syerrapragada ,
This will fix JSDK-2185. Please take a look when you can.
> JSDK-2185 Remove RemoteParticipantV2s not present in "synced" message.

- lib/connect.js
@markandrus @manjeshbhargav 
Should I include that P2P, Group rooms work? I have manually tested that they work
> Print the Edge experimental support warning

- CHANGELOG.md
- lib/localparticipant.js
- test/integration/spec/localparticipant.js
> JSDK-2212 Ensure LocalTrackPublicationV2 is not null.

- CHANGELOG.md
- package.json
> Prepping for 2.0.0-beta3

- lib/signaling/v2/twilioconnectiontransport.js
> Setting longer backoff and jitter values.

- lib/util/index.js
> JSDK-2239 Differentiating between "unified-plan" only and "plan-b" only Chrome versions

- CHANGELOG.md
- lib/signaling/v2/cancelableroomsignalingpromise.js
- package.json
- test/integration/spec/localparticipant.js
- test/integration/spec/util/simulcast.js
- test/lib/defaults.js
* Making "sdpSemantics" flag private.
* Upgrading twilio-webrtc.js to 3.2.0-rc3
* Updating CHANGELOG.md
@syerrapragada
> Prep for 2.0.0-rc8

- lib/connect.js
- lib/participant.js
- lib/signaling/localtrackpublication.js
- lib/signaling/participant.js
- lib/signaling/remotetrackpublication.js
- lib/signaling/track.js
- lib/signaling/v2/peerconnectionmanager.js
- lib/signaling/v2/remoteparticipant.js
- lib/signaling/v2/remotetrackpublication.js
- lib/signaling/v2/room.js
- lib/signaling/v2/transport.js
- lib/signaling/v2/twilioconnectiontransport.js
- lib/util/constants.js
- test/integration/spec/localparticipant.js
- test/integration/spec/rest.js
- test/unit/spec/signaling/v2/remoteparticipant.js
- test/unit/spec/signaling/v2/remotetrackpublication.js
- test/unit/spec/signaling/v2/transport.js
- test/unit/spec/signaling/v2/twilioconnectiontransport.js
Also in the PR:
* Reverting to add dummy audio MediaStreamTrack only for Firefox.
* Using the ALB urls for Video Signaling Gateway.
> JSDK-2245 Upgrade RSP to version 2.

- karma/makeconf.js
- lib/signaling/v2/peerconnectionmanager.js
- lib/util/index.js
- package.json
- test/lib/util.js
> JSDK-2232 Unified Plan support for Safari 12.1

- CHANGELOG.md
- package.json
> Prep for 2.0.0-rc10

- lib/signaling/v2/peerconnection.js
> JSDK-2248 Reverting changes.

- CHANGELOG.md
- package.json
> Prep for 1.15.0-rc1.

- CHANGELOG.md
- README.md
- package.json
> Prep for 2.0.0-beta5.

- lib/signaling/v2/cancelableroomsignalingpromise.js
- test/integration/spec/localparticipant.js
- test/integration/spec/util/simulcast.js
- test/lib/defaults.js
> Converting "sdpSemantics" to a private flag.

- package.json
> JSDK-2266 Upgrading to twilio-webrtc.js@2.2.1-rc1.

- package.json
> Upgrading to twilio-webrtc.js@2.2.1-rc3.

- .travis.yml
- CHANGELOG.md
- lib/signaling/v2/peerconnection.js
- test/integration/spec/connect.js
- test/integration/spec/localparticipant.js
- test/unit/spec/signaling/v2/peerconnection.js
@innerverse ,
Also, updated CHANGELOG.md entry for TCMP to recommend disconnecting from Room on tab close.
> JSDK-2219 Once glare is handled, execute a queued call to createOffer(), if any.

- karma/makeconf.js
- package.json
- test/integration/spec/connect.js
> Prepping for 2.0.0-rc12.

- COMMON_ISSUES.md
Now that a github issue has been opened, I've shortened the COMMON_ISSUES.md entry.
> JSDK-2281 Shorten the entry and link to the github issue.

- lib/signaling/v2/peerconnectionmanager.js
- test/integration/spec/connect.js
> JSDK-2279 Rejecting connect()'s CancelablePromise with a MediaConnectionError.

- CHANGELOG.md
> Prep for 2.0.0-rc13.

- lib/signaling/v2/peerconnection.js
- lib/util/sdp/index.js
- test/integration/spec/localparticipant.js
- test/unit/spec/util/sdp/index.js
#550 introduced the regressions mentioned in the title. I have commented in JSDK-2291 as to why we are reverting this change.
> JSDK-2291, JSDK-2292 Reverting changes for JSDK-2276.

- CHANGELOG.md
- README.md
* Linking to 2.x CHANGELOG in 1.x CHANGELOG
* Linking to master branch in 1.x README
* Updating 1.12.0 CHANGELOG entry to mention plan-b enforcement
> JSDK-2295 1.x CHANGELOG and README changes

- COMMON_ISSUES.md
@anna-vasilko @idelgado 
This PR adds a COMMON_ISSUES.md entry which links to this github issue: #565.
Please take a look at the wording in this entry and in the github issue and provide feedback
if required.
> JSDK-2299 COMMON_ISSUES.md entry linking to the github issue.

- CHANGELOG.md
- COMMON_ISSUES.md
- README.md
- package.json
@anna-vasilko 
* Setting the date for the release
* Re-indenting and polishing CHANGELOG.md entries
* Re-writing COMMON_ISSUES.md entries for better clarity
* Upgrading to twilio-webrtc.js@4.0.0
> Prepping for twilio-video.js@2.0.0-beta6

- CHANGELOG.md
> Prep for twilio-video.js@1.16.0

- CHANGELOG.md
- lib/signaling/v2/peerconnection.js
- test/integration/spec/connect.js
> JSDK-2314 Enabling VP8 simulcast support for Safari.

- CHANGELOG.md
- lib/signaling/v2/peerconnection.js
- test/integration/spec/connect.js
> JSDK-2315 Enabling VP8 simulcast support for Safari

- COMMON_ISSUES.md
> JSDK-2294 COMMON_ISSUES.md entry for autoplay policy

- CHANGELOG.md
- COMMON_ISSUES.md
> JSDK-2319 Document ParticipantNotFoundError for session expiry.

- CHANGELOG.md
> Prepping for 1.17.0.

- CHANGELOG.md
- lib/room.js
- lib/signaling/v2/peerconnection.js
- lib/util/sdp/index.js
- package.json
- test/integration/spec/localparticipant.js
- test/integration/spec/util/insightspublisher.js
- test/unit/spec/util/sdp/index.js
@syerrapragada Continuing from #592 .
> JSDK-2312, JSDK-2303

- CHANGELOG.md
> Adding CHANGELOG.md entry for LocalParticipant.setNetworkQualityConfiguration().

- CHANGELOG.md
> Prep for 1.18.0

- CHANGELOG.md
- README.md
> Prep for 2.0.0-beta8.

- lib/signaling/v2/peerconnection.js
This PR cherry-picks the changes in #621 on to the `support-1.x` branch.
> JSDK-2330 Make sure preferredCodecs is honored.

- CHANGELOG.md
- COMMON_ISSUES.md
- lib/signaling/v2/peerconnection.js
- lib/signaling/v2/peerconnectionmanager.js
- test/unit/spec/signaling/v2/peerconnection.js
- test/unit/spec/signaling/v2/peerconnectionmanager.js
@syerrapragada @ceaglest 
This PR contains the following changes:
> ICE Improvements

- .travis.yml
- lib/signaling/v2/peerconnection.js
- lib/util/sdp/index.js
- test/unit/spec/util/sdp/index.js
This PR cherry-picks changes from #643 and #649 in order to enable filtering of local codecs based on remote sdps.
> JSDK-2376 Cherry-picking changes from PRs #643 and #649

- .travis.yml
- CHANGELOG.md
- COMMON_ISSUES.md
- lib/connect.js
- lib/signaling/v2/peerconnection.js
- lib/signaling/v2/peerconnectionmanager.js
- lib/util/constants.js
- test/integration/spec/connect.js
- test/unit/spec/connect.js
- test/unit/spec/signaling/v2/peerconnection.js
- test/unit/spec/signaling/v2/peerconnectionmanager.js
Since we have decided to push Unified Plan support for Chrome further by at least a week or two, I'm bringing in Region Selection and ICE improvements for the next beta release. Please review these cherry-picked commits to see if the changes are ok.
> Prepping for 2.0.0-rc27.

- CHANGELOG.md
- README.md
> Setting release date for 2.0.0-beta10.

- CHANGELOG.md
- README.md
This PR:
* Setting release date.
* Pointing QuickStart link to 1.x branch.
> Prepping for twilio-video.js@1.18.1.

- CHANGELOG.md
- README.md
- lib/connect.js
@ceaglest @anna-vasilko @aymenn 
Please take a look at these changes to the documentation for `region`, and let me know what you think.
> Updating "region" docs and setting release date.

- CHANGELOG.md
- lib/connect.js
- lib/signaling/v2/cancelableroomsignalingpromise.js
- lib/signaling/v2/iceconnectionmonitor.js
- lib/signaling/v2/peerconnection.js
- lib/signaling/v2/twilioconnectiontransport.js
- lib/util/constants.js
- lib/util/index.js
- test/integration/spec/connect.js
- test/unit/index.js
- test/unit/spec/signaling/v2/iceconnectionmonitor.js
- test/unit/spec/signaling/v2/peerconnection.js
- test/unit/spec/signaling/v2/twilioconnectiontransport.js
- test/unit/spec/util/sdp/index.js
@makarandp0 
This PR:
- Rebases the latest changes from `master` onto `feature/mediaMonitor` in preparation for merging it back to `master`.
- Ports/refactors changes from #666 with an added unit test.
Please review and confirm that your changes are intact after the rebase.
> JSDK-2337 Merge IceConnectionMonitor feature branch.

- lib/connect.js
- lib/signaling/v2/cancelableroomsignalingpromise.js
- lib/signaling/v2/twilioconnectiontransport.js
- lib/util/index.js
- test/unit/spec/signaling/v2/twilioconnectiontransport.js
@makarandp0 @innerverse 
This PR implements the BandwidthProfileOptions specified as a ConnectOptions parameter `bandwidthProfile`. Please take a look when you can.
> BandwidthProfileOptions: mode, maxSubscriptionBitrate and maxTracks.

- CHANGELOG.md
- package.json
@makarandp0 
This PR preps for the release of 2.0.0-beta12. Please take a look.
> Setting the release date and upgrading twilio-webrtc.js to 4.1.0.

- lib/localparticipant.js
- lib/media/track/index.js
- lib/util/constants.js
- lib/util/index.js
- test/integration/spec/connect.js
- test/integration/spec/room.js
- test/lib/util.js
- test/unit/spec/localparticipant.js
- test/unit/spec/signaling/v2/twilioconnectiontransport.js
@makarandp0 
**WIP**
This PR has the following changes:
* Changing TrackPriority value "medium" to "standard" in accordance with the updated RSP spec
* Moving "mode" into "video" in accordance with the updated RSP spec
The RSP changes are still in dev, so let's keep this open until we can verify in prod. I'd love to get your feedback in the meantime.
> JSDK-2346, JSDK-2405 Consume the updated RSP spec

- CHANGELOG.md
- lib/connect.js
- lib/util/index.js
- test/integration/spec/connect.js
- test/unit/spec/connect.js
- test/unit/spec/signaling/v2/twilioconnectiontransport.js
@makarandp0 
_WIP_
~~Adding integration tests for renderDimensions.~~ - *This only affects bandwidth allocation and cannot be deterministically tested*.
> JSDK-2441 - dominantSpeakerPriority and renderDimensions

- CHANGELOG.md
- COMMON_ISSUES.md
- lib/connect.js
- lib/localparticipant.js
* Adding CHANGELOG.md entry for refactoring Bandwidth Constraints API implementation.
* Correcting typo for Expedited Forwarding.
* Adding COMMON_ISSUES.md entry for Firefox bug in their impl. of RTCRtpSender.setParameters().
* Updating docs for "maxAudioBitrate" and "maxVideoBitrate" to mention observed bitrate ranges.
> Prepping for 1.19.0

- CHANGELOG.md
- COMMON_ISSUES.md
- lib/connect.js
- lib/localparticipant.js
> Prepping for 2.0.0-rc37.

- .travis.yml
- CHANGELOG.md
- COMMON_ISSUES.md
- README.md
- bower.json
- lib/connect.js
- lib/data/receiver.js
- lib/data/transport.js
- lib/localparticipant.js
- lib/signaling/v2/peerconnection.js
- lib/signaling/v2/room.js
- lib/signaling/v2/transport.js
- lib/util/insightspublisher/index.js
- lib/util/insightspublisher/null.js
- lib/util/sdp/index.js
- package.json
- test/integration/spec/connect.js
- test/integration/spec/localparticipant.js
- test/integration/spec/util/insightspublisher.js
- test/lib/mocksdp.js
- test/lib/util.js
- test/unit/spec/signaling/v2/peerconnection.js
- test/unit/spec/signaling/v2/room.js
- test/unit/spec/signaling/v2/transport.js
- test/unit/spec/util/insightspublisher.js
- test/unit/spec/util/sdp/index.js
@makarandp0 This PR updates `support-1.x` (Chrome Unified Plan support) with the changes from `support-1.x-chrome-planb` in preparation for cutting 1.20.0-rc1.
> Merge support-1.x-chrome-planb to support-1.x

- COMMON_ISSUES.md
@makarandp0 
Based on the observations noted [here](https://paper.dropbox.com/doc/JSDK-2509-Next-Steps--Ak6majkTPv1heZKTSPNvlyA~Ag-mMucshYiq165d6rvMdK6q), I'm adding a COMMON_ISSUES.md entry describing the issue. Please take a look when you can.
> JSDK-2509 Adding COMMON_ISSUES.md entry.

- CHANGELOG.md
- README.md
- package.json
> Prepping for 2.0.0-beta14.

- CHANGELOG.md
- lib/connect.js
- lib/util/constants.js
> JSDK-2312 Enable unified plan support for Chrome.

- lib/connect.js
- lib/createlocaltrack.js
- lib/createlocaltracks.js
- lib/index.js
- lib/media/track/localaudiotrack.js
- lib/media/track/localdatatrack.js
- lib/media/track/localvideotrack.js
- scripts/docs.js
Port https://github.com/twilio/twilio-video.js/pull/753 over to support-1.x-chrome-planb branch
> JSDK-2320 document is supported for 1x branch

- lib/util/sdp/index.js
- lib/util/support.js
- test/integration/spec/localparticipant.js
- test/unit/spec/util/support.js
@makarandp0 
This PR fixes JSDK-2534 and JSDK-2515. If you need some clarification regarding the fixes, we can meet up using video app.
> Prep for 2.0.0 rc44.

- CHANGELOG.md
- README.md
- package.json
@makarandp0 @anna-vasilko @aymenn 
**Changes:**
> Prep for 2.0.0-beta15.

- scripts/circleci-run-tests.sh
stage/dev environment does not all regions. limit them for integration tests.
> limit regions for stage builds

- .circleci/config.yml
- .circleci/runbuild.js
- scripts/circleci-run-tests.sh
This change ports https://github.com/twilio/twilio-video.js/pull/798 into support-1.x branch
This will enable running integration tests on stage environment against 1.x code. 
Once this is merged you can run following command to schedule a integration test job
```
curl -u ${CIRCLECI_TOKEN}: -X POST \
--header 'Content-Type: application/json' \
-d '{
"branch": "support-1.x",
"parameters": {
"backend_workflow": true,
"pr_workflow": false,
"environment": "stage"
}
}' \
https://circleci.com/api/v2/project/github/twilio/twilio-video.js/pipeline
```
Example run:
https://circleci.com/workflow-run/9a09dd93-4927-423e-8af0-df5aa963f0fe
> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the …
> backend tests for 1.x

- CHANGELOG.md
> chagenlog typo + bug fixes

- CHANGELOG.md
- README.md
> update README links to beta16

- lib/connect.js
- lib/media/track/localvideotrack.js
updates docs to fix:  
https://issues.corp.twilio.com/browse/JSDK-2618
https://issues.corp.twilio.com/browse/JSDK-2613
- connect rejection handlers:
[Before](http://stage.twiliocdn.com/sdk/js/video/releases/2.0.0-beta16/docs/module-twilio-video.html#.connect__anchor) and [After](https://6254-46595751-gh.circle-artifacts.com/0/home/circleci/project/dist/docs/module-twilio-video.html#.connect__anchor)
- missing events in Fires section of LocalVideoTrack
[Before](http://stage.twiliocdn.com/sdk/js/video/releases/2.0.0-beta16/docs/LocalVideoTrack.html) and [After](https://6254-46595751-gh.circle-artifacts.com/0/home/circleci/project/dist/docs/LocalVideoTrack.html)
> All third-party contributors acknowledge that any contributions they provide will be made under the …
> JSDK-2618 & JSDK-2613 small doc fixes

- CHANGELOG.md
- README.md
- lib/util/support.js
- test/unit/spec/util/support.js
> JSDK-2633 isSupported returns false for non-Chromium Edge.

- CHANGELOG.md
> Prep for 1.20.1

- CHANGELOG.md
- README.md
- package.json
> Merge master into develop

- .circleci/images/chrome/beta/Dockerfile
- .circleci/images/chrome/stable/Dockerfile
- .circleci/images/chrome/unstable/Dockerfile
- .circleci/images/firefox/beta/Dockerfile
- .circleci/images/firefox/stable/Dockerfile
- .circleci/images/firefox/unstable/Dockerfile
- docker/dockerProxyClient.js
- docker/dockerProxyServer.js
- test/integration/spec/docker/reconnection.js
- test/lib/defaults.js
- test/lib/post.js
- test/lib/rest.js
- test/lib/util.js
This port infra changes from #888 into master.
> port infra (docker images + proxy) changes from #888

- README.md
> Link to twilio-video-app-react.

- README.md
- lib/connect.js
This is a PR for both JSDK-2699 as well as JSDK- 2713
Added documentation updates for how to run unit and integration tests (JSDK-2699).
Updated DominantSpeakerPriority documentation (JSDK-2713).
> JSDK-2699/JSDK-2713

- .circleci/config.yml
CircleCI config to automatically trigger QE tests.
> Trigger for CircleCI QE Tests

- .circleci/images/docker-compose.yml
- CHANGELOG.md
- README.md
- lib/connect.js
- lib/localparticipant.js
- lib/participant.js
- lib/room.js
- lib/signaling/v2/cancelableroomsignalingpromise.js
- lib/signaling/v2/localparticipant.js
- lib/signaling/v2/room.js
- lib/signaling/v2/twilioconnectiontransport.js
- lib/util/constants.js
- package.json
- test/integration/spec/connect.js
- test/integration/spec/docker/reconnection.js
- test/integration/spec/remotetracks.js
- test/unit/spec/localparticipant.js
- test/unit/spec/remoteparticipant.js
- test/unit/spec/room.js
- test/unit/spec/signaling/v2/cancelableroomsignalingpromise.js
- test/unit/spec/signaling/v2/twilioconnectiontransport.js
```
git checkout master
git branch prep_for_release_2.3.0
git checkout prep_for_release_2.3.0
git merge develop
echo and fixed some conflicts
```
> Prep for release 2.3.0

- .circleci/config.yml
- CHANGELOG.md
- README.md
- package.json
```
git checkout develop
git checkout -b merge_from_master 
git merge master
echo resolve conflicts
```
> Merge from master after 2.3.0

- README.md
> Adding link to best practices guide.

- test/integration/spec/connect.js
cherry-pick #921 
```
git cherry-pick 481fe123d7ca14f361bc7c6cbbebb736bc494e9f
```
* fix media region tests for stage
* Update test/integration/spec/connect.js
Co-Authored-By: Manjesh Malavalli <mmalavalli@twilio.com>
Co-authored-by: Manjesh Malavalli <mmalavalli@twilio.com>
> JSDK-2729: fix media region tests for stage (develop)

- COMMON_ISSUES.md
> JSDK-2769 Adding COMMON_ISSUES.md entry.

- lib/signaling/v2/room.js
- test/unit/spec/signaling/v2/room.js
> JSDK-2762 Publishing "active-ice-candidate-pair" on the first period followed by every other period.

- CHANGELOG.md
- lib/signaling/v2/peerconnection.js
- lib/util/networkmonitor.js
- test/lib/mockconnection.js
- test/unit/spec/util/networkmonitor.js
* Refactoring NetworkMonitor implementation and unit tests.
> Prep for 2.4.0-rc2.

- .circleci/config.yml
> QSDK-6569 Fix qe test trigger

- lib/util/support.js
- test/unit/spec/util/support.js
> JSDK-2756 isSupported returns false for Desktop Brave.

- CHANGELOG.md
- COMMON_ISSUES.md
- README.md
> Prep for 2.4.0.

- .circleci/config.yml
merge recent master into tmp-develop - so that qe workflow gets kicked off when we cut RC.
> merge master into tmp-develop

- CHANGELOG.md
- package.json
This PR has the following changes:
* Updating twilio-webrtc.js to 4.2.1-rc1.
* Updating CHANGELOG.md.
> Prep for 2.5.0-rc2.

- CHANGELOG.md
- lib/signaling/v2/cancelableroomsignalingpromise.js
- lib/twilioconnection.js
- lib/util/eventobserver.js
- test/unit/spec/twilioconnection.js
- test/unit/spec/util/eventobserver.js
> Prep for 2.5.0-rc3.

- .release.json
- CHANGELOG.md
- README.md
- lib/connect.js
@makarandp0 
* Setting release date.
* Fix "waiting" event documentation.
* Edit doc links to point to 2.5.0.
* Fix CHANGELOG entry formatting.
> Prep for 2.5.0.

- lib/twilioconnection.js
- test/unit/spec/twilioconnection.js
> JSDK-2841 TCMP client transitions from "waiting" to "open" upon receiving "welcome".

- CHANGELOG.md
- package.json
@manjeshbhargav Please take a look.
> update changelog + webrtc dependency

- CHANGELOG.md
- lib/stats/peerconnectionreportfactory.js
- lib/twilioconnection.js
- lib/util/support.js
- package.json
- test/lib/mockwebrtc.js
- test/unit/spec/twilioconnection.js
@makarandp0 
This PR cherry-picks changes for JSDK-2832, JSDK-2841 and JSDK-2848 from `tmp-develop`.
> Prep for 2.5.1-rc1

- CHANGELOG.md
> Added some details on the support policy and the 1.x EOS date

- CHANGELOG.md
- README.md
- package.json
> Prep for 2.7.0

- CHANGELOG.md
> Added details on the support policy and end of support date

- CHANGELOG.md
- lib/media/track/localmediatrack.js
- lib/media/track/localvideotrack.js
- lib/util/detectsilentvideo.js
- test/lib/fakemediastream.js
- test/unit/spec/media/track/localmediatrack.js
@makarandp0 
Reopening #1106 here because the JIRA ticket used in the previous PR was the wrong one (JSDK-2899). This PR updates the commit messages, branch name and CHANGELOG.md entry to use the correct JIRA ticket (JSDK-2915).
> JSDK-2915 Detect silent video upon unmute and restart the LocalVideoTrack.

- karma/makeconf.js
- test/integration/spec/localtrackpublication.js
> increase browser disconnect Tolerance (#1120)

- .circleci/images/build_docker_image.sh
- scripts/circleci-run-tests.sh
We have a job that updates our docker containers for tests with new browser versions. This small change will make the job notify #eng-sdk-js of any updates. 
> Slack notifications about updated browser version

- lib/preflight/preflighttest.js
@charliesantos, Thanks for spotting this issue! With this fix we should get the rtt times inline with our expectations :)
> fix rtt (look for currentRoundTripTime, and not totalRoundTripTime)

- COMMON_ISSUES.md
> Adding COMMON_ISSUES.md entry for JSDK-2987.

- LICENSE.md
> Update copyright year to 2020

- CHANGELOG.md
- README.md
> Prep 2.8.0-beta.1 release

- .gitignore
- package.json
- tsdef/.eslintrc.json
- tsdef/LocalVideoTrack.d.ts
- tsdef/RemoteAudioTrack.d.ts
- tsdef/RemoteVideoTrack.d.ts
- tsdef/Track.d.ts
- tsdef/VideoTrack.d.ts
- tsdef/index.d.ts
- tsdef/twilio-video-tests.ts
This is a PR for the video track TS definitions.
> JSDK-2953 - Video Track TS Definitions

- test/lib/rest.js
Lately we have been [seeing](https://app.circleci.com/pipelines/github/twilio/twilio-video.js/2505/workflows/5d5a2da3-b91e-4c03-8dce-745c8bf1141d/jobs/27427/steps) some integration tests failing because it failed to create room. This instrumentation would help it debug further.
> record details of room creation failures.

- CHANGELOG.md
- lib/connect.js
- lib/signaling/v2/peerconnection.js
- lib/util/sdp/index.js
- test/integration/spec/connect.js
- test/unit/spec/util/sdp/index.js
@makarandp0 @ceaglest 
This pull request implements the ConnectOptions API spec changes specified [here](https://code.hq.twilio.com/client/video-sdk-api/pull/73). The LocalTrackPublishOptions API spec changes will be implemented in a separate release.
> JSDK-3022 DTX for Opus codec.

- test/integration/spec/room.js
This change adds some instrumentation for getStats test (that used to fail on firefox) - I did not see the failure in my recent runs. So I am re-enabling the test.
Also picked the changes from the same file from develop branch.
> JSDK-2808 - re-enable getstat test + pick from develop

- README.md
> Prep for 2.7.3 - updating doc links to pinned URL.

- CHANGELOG.md
- README.md
> Prep for 2.8.0-beta.2 - updating doc links and setting release date.

- package.json
same as https://github.com/twilio/twilio-video.js/pull/1262, 
> Update browserify for master

- CHANGELOG.md
- lib/signaling/v2/cancelableroomsignalingpromise.js
- lib/signaling/v2/recording.js
- lib/util/eventobserver.js
- lib/util/index.js
- test/integration/spec/room.js
- test/unit/spec/signaling/v2/cancelableroomsignalingpromise.js
- test/unit/spec/signaling/v2/recording.js
- test/unit/spec/util/index.js
Cherry Picked: https://github.com/twilio/twilio-video.js/pull/1277 and https://github.com/twilio/twilio-video.js/pull/1270 
> cherry pick recording and connect insights changes to prepare for RC

- lib/signaling/v2/cancelableroomsignalingpromise.js
- lib/util/eventobserver.js
- lib/util/index.js
- test/unit/spec/signaling/v2/cancelableroomsignalingpromise.js
- test/unit/spec/util/index.js
This cherry-picks https://github.com/twilio/twilio-video.js/pull/1270 to include in preflight beta.
> add connect insight event for preflight beta

- CHANGELOG.md
> prep for 2.8.0-beta.3

- package.json
- tsdef/index.d.ts
- tsdef/twilio-video-tests.ts
- tsdef/types.d.ts
PR for custom logger type definition. 
> JSDK-3094 custom logger definitions

- README.md
Removing the video-product email off README.
> JSDK-3095 - Changing README text on master branch

- tsdef/twilio-video-tests.ts
- tsdef/types.d.ts
[JIRA Ticket](https://issues.corp.twilio.com/browse/JSDK-3097)
Here are the added properties on the `ConnectOptions`. 
Added some more 'tests' as well which were taken from the cdn examples as well as the React app to make sure that the object literals work when passing into `preferredVideoCodecs` and `preferredAudioCodecs`.
> JSDK-3097 - Adding to ConnectOptions

- CHANGELOG.md
Updating the CHANGELOG.md support for 1.x text.
> JSDK-3098 Updating CHANGELOG.md

- CHANGELOG.md
Adding changelog for RequireJS fix
> Adding changelog for RequireJS fix

- test/integration/spec/connect.js
JSDK-2512 | Adding tests for maxAudioBitrate and maxVideoBitrate
> JSDK-2512 | Adding tests for maxAudioBitrate and maxVideoBitrate

- lib/media/track/localvideotrack.js
- lib/media/track/videotrack.js
- test/unit/spec/media/track/localvideotrack.js
- test/unit/spec/media/track/videotrack.js
- tsdef/VideoTrack.d.ts
> VIDEO-3995 VIDEO-3996 | Handle null outputframe and adding tsdef

- lib/localparticipant.js
- lib/media/track/localmediatrack.js
- lib/media/track/localvideotrack.js
- lib/media/track/mediatrack.js
- lib/media/track/remotevideotrack.js
- lib/media/track/videotrack.js
- lib/util/constants.js
- test/unit/spec/localparticipant.js
- test/unit/spec/media/track/localmediatrack.js
- test/unit/spec/media/track/localvideotrack.js
- test/unit/spec/media/track/mediatrack.js
- test/unit/spec/media/track/videotrack.js
See commit history for details on the changes.
> Videoprocessor updates

- lib/localparticipant.js
- lib/media/track/localvideotrack.js
- lib/media/track/mediatrack.js
- lib/media/track/remotemediatrack.js
- lib/media/track/sender.js
- lib/media/track/videotrack.js
- test/unit/spec/localparticipant.js
- test/unit/spec/media/track/localvideotrack.js
- test/unit/spec/media/track/mediatrack.js
- test/unit/spec/media/track/remotemediatrack.js
- test/unit/spec/media/track/sender.js
- test/unit/spec/media/track/videotrack.js
Please check commit history for details.
> Videoprocessor rc3 bugfixes

- lib/localparticipant.js
- lib/media/track/remotemediatrack.js
- test/unit/spec/localparticipant.js
- test/unit/spec/media/track/remotemediatrack.js
Please see commit history for details.
> VIDEO-4175 VIDEO-4278 | Videoprocessor rc4 bugfixes

- lib/media/track/remotevideotrack.js
- lib/util/nullintersectionobserver.js
- test/unit/spec/media/track/remotemediatrack.js
- test/unit/spec/media/track/remotevideotrack.js
JIRA Ticket: [VIDEO-4298](https://issues.corp.twilio.com/browse/VIDEO-4298)
DRAFT PR 
Making some progress on these unit tests. Still need to add one visible and invisible element tests.
> VIDEO-4298-IntersectionObserver Unit Tests

- CHANGELOG.md
- COMMON_ISSUES.md
- lib/signaling/v2/peerconnection.js
- lib/util/sdp/index.js
- test/unit/spec/util/sdp/index.js
@makarandp0 @charliesantos 
This PR fixes [VIDEO-3736](https://issues.corp.twilio.com/browse/VIDEO-3736).
> VIDEO-3736 Remove H264 from remote SDPs where applicable.

- lib/signaling/v2/peerconnection.js
- lib/util/index.js
> VIDEO-3736 Fixing regressions in desktop Firefox by limiting the workaround to Android Firefox.

- lib/connect.js
- lib/media/track/remotevideotrack.js
- lib/participant.js
- lib/room.js
- lib/signaling/v2/renderhintssignaling.js
- lib/signaling/v2/room.js
- lib/util/nullobserver.js
- test/integration/spec/bandwidthprofile.js
- test/unit/spec/media/track/remotevideotrack.js
This PR adds `renderHints` connectOptions property and plumbing to pass the property to `RemoteVideoTrack`
also updated unit test against on/off state of various options, added integration tests for `idleTrackSwitchOff` property
> VIDEO-4383 connect options for render hints

- CHANGELOG.md
> Update Changelog to include 1.x EOL date

- CHANGELOG.md
- lib/connect.js
Updates changelog for `renderDimensions="auto"`
related FRD PR: https://code.hq.twilio.com/client/sdk-frd/pull/71
> changelog for renderDimensions=auto

- CHANGELOG.md
- README.md
- test/crossbrowser/src/videodriver/index.ts
- test/lib/sdkdriver/test/integration/spec/sdkdriver.ts
https://issues.corp.twilio.com/browse/VIDEO-4495
> VIDEO-4495 | Update to latest cdn

- README.md
Update readme links to use latest cdn.
> Update readme links to use latest cdn

- CHANGELOG.md
Update CHANGELOG.md for Video Processor API Beta
> Update CHANGELOG.md for Video Processor API Beta

- CHANGELOG.md
Remove a duplicate changelog line. 
> remove duplicate  changelog line

- lib/signaling/v2/room.js
- test/unit/spec/signaling/v2/room.js
JIRA Ticket: [VIDEO-4508](https://issues.corp.twilio.com/browse/VIDEO-4508)
This PR fixes default `relayProtocol` behavior. If it is not found in the stats report, the property will not be published.
> VIDEO-4508 RelayProtocol

- COMMON_ISSUES.md
- Re-structured common issues by browser name
- Used collapsible markdown to make the doc more compact
- Removed old issues (the ones fixed and rolled out by browser vendors more than 2 years ago)
- Added some recent relevant issues, more can be added later but it should be good for now
> Common Issues polish

- CHANGELOG.md
- lib/stats/networkqualitybandwidthstats.js
Base on https://docs.google.com/document/d/1DADjEpPKlLZUBvV884_lJYi1VxdWkh2TLH0lK_s6T8M/edit#
> Update bandwidth docs

- .circleci/images/chrome/beta/Dockerfile
- .circleci/images/chrome/unstable/Dockerfile
- .circleci/images/firefox/beta/Dockerfile
- .circleci/images/firefox/unstable/Dockerfile
@makarandp0 
Re-opening #1489 against `master` as you suggested.
> Upgrading node to the latest version for beta and unstable browsers.

- CHANGELOG.md
- lib/media/track/localvideotrack.js
- lib/media/track/remotevideotrack.js
- lib/media/track/videotrack.js
- package.json
- test/unit/spec/media/track/videotrack.js
- tsdef/VideoProcessor.d.ts
> VIDEO-4442 | Update VideoProcessor.processFrame method signature

- lib/localparticipant.js
- lib/media/track/localvideotrack.js
- lib/media/track/videoprocessoreventobserver.js
- lib/media/track/videotrack.js
- lib/util/constants.js
- lib/util/eventobserver.js
- test/unit/index.js
- test/unit/spec/localparticipant.js
- test/unit/spec/media/track/localvideotrack.js
- test/unit/spec/media/track/videoprocessoreventobserver.js
- test/unit/spec/media/track/videotrack.js
Implementing the videoprocessor insights events https://code.hq.twilio.com/client/rtc-insights-spec/pull/76
See example events in kibana https://kibana.dev-us1.eak.twilio.com/video/goto/3b653e6f39570da3fba44a2efeb2a711
> VIDEO-5272 | VideoProcessor Insights events

- CHANGELOG.md
- README.md
- lib/util/support.js
- test/unit/spec/util/support.js
JIRA: [VIDEO-5723](https://issues.corp.twilio.com/browse/VIDEO-5723)
Updated support for iOS Chrome and adjusted unit test.
> VIDEO-5723 - isSupported for iOS Chrome

- .circleci/config.yml
- CHANGELOG.md
- lib/util/support.js
- package.json
- test/serversiderender/index.js
- test/serversiderender/spec/issupported.js
> VIDEO-5888 | Fix issue for server side rendering applications

- .circleci/config.yml
- .circleci/images/build_docker_image.sh
- scripts/circleci-run-tests.sh
This uses dockerhub creds from `dockerhub-push` `dockerhub-pulls` contexts.
> VIDEO-5808 use dockerhub creds from context

- CHANGELOG.md
reference internal ticket in change log + but minor update 
> video-6336 changelog update

- README.md
remove stale build status from the readme. 
> VIDEO-6490: remove stale appveyor link

- lib/connect.js
- lib/createlocaltracks.js
- lib/localparticipant.js
- lib/media/track/mediatrack.js
- lib/signaling/v2/peerconnection.js
- lib/util/sdp/issue8329.js
- package.json
- test/integration/spec/bandwidthprofile/regressions.js
- test/integration/spec/bandwidthprofile/renderhints.js
- test/integration/spec/bandwidthprofile/video.js
- test/integration/spec/browserbugs/chromium.js
- test/integration/spec/connect.js
- test/integration/spec/docker/reconnection.js
- test/integration/spec/leaktests.js
- test/integration/spec/localtrackpublication.js
- test/integration/spec/localtracks.js
- test/integration/spec/preflight.js
- test/integration/spec/room.js
- test/integration/spec/util/insightspublisher.js
- test/integration/spec/util/simulcast.js
- test/lib/mockwebrtc.js
- test/unit/spec/util/sdp/issue8329.js
@makarandp0 @PikaJoyce 
This PR consumes the changes made in twilio/twilio-webrtc.js#141.
> VIDEO-4958 Consuming the changes in twilio-webrtc.js PR #141.

- package.json
Small PR updating the typescript package to fix errors occurring on CircleCI
> CircleCI build fix

- CHANGELOG.md
Updating the date for 2.17.0 release
> Update CHANGELOG.md for 2.17.0

- lib/connect.js
- lib/signaling/v2/cancelableroomsignalingpromise.js
- lib/signaling/v2/localparticipant.js
- lib/signaling/v2/publisherhintsignaling.js
- lib/signaling/v2/renderhintssignaling.js
- lib/signaling/v2/room.js
- lib/signaling/v2/twilioconnectiontransport.js
- lib/util/index.js
- tsdef/types.d.ts
Hey @manjeshbhargav, This change enables publisher hints - For now they just handle the 'enabled' property of the simulcast layers. Still need to write unit and integration tests, but would like to get some early feedback. 
> VIDEO-6976 - respect publisher hints

- COMMON_ISSUES.md
- package.json
> adapter.js known issue + update dev dependency

- CHANGELOG.md
Fixed couple of typos, and added additional notes about limitation of the feature.
> adaptive simulcast change log update

- COMMON_ISSUES.md
> Add iOS 15.1 common issues

- test/lib/post.js
Added some instrumentation so that we see room creation failure reasons. We are seeing lot of [those on stage](https://twilio.slack.com/archives/C0C4K4G0H/p1636493755063000)
This change shows more information in logs: https://app.circleci.com/pipelines/github/twilio/twilio-video.js/5266/workflows/06fea69e-b4d1-4a20-ac78-e70aeebf5d5e/jobs/56147
> instrumentation for room failures

- COMMON_ISSUES.md
I just had a discussion with Anna and moving the iOS 15 issues under each specific browser and prefixing them with iOS 15 seems better for our customers.
> Update common issues

- COMMON_ISSUES.md
> Add Android 12 issue to common issues

- COMMON_ISSUES.md
> Remove non actionable workaround

- lib/signaling/v2/twilioconnectiontransport.js
> VIDEO-7799 Remove cached access token in TwilioConnectionTransport

- COMMON_ISSUES.md
> Add low audio workaround

- CHANGELOG.md
- lib/signaling/v2/renderhintssignaling.js
- test/unit/spec/signaling/v2/renderhintssignaling.js
This PR fixes https://issues.corp.twilio.com/browse/VIDEO-7654 by implementing proposal from https://code.hq.twilio.com/client/room-signaling-protocol/pull/76
> resend render hints

- CHANGELOG.md
Adding changelog entry for VIDEO-7831
> VIDEO-7831-AddChangelog

- CHANGELOG.md
- README.md
- lib/media/track/remotevideotrack.js
- test/lib/document.js
- test/unit/spec/media/track/remotemediatrack.js
- test/unit/spec/media/track/remotevideotrack.js
> Prep for 2.18.2

- CHANGELOG.md
- lib/util/cancelablepromise.js
- package.json
- test/integration/spec/connect.js
- test/unit/spec/util/cancelablepromise.js
- tsconfig.json
- tsdef/index.d.ts
- tsdef/twilio-video-tests.ts
- tsdef/types.d.ts
Merging CancelablePromise fix and audioLevel fix
> VIDEO 3600 7831 | Merging CancelablePromise fix and audioLevel fix

- test/integration/spec/connect.js
Remove .only from integration tests
> Remove .only

- .circleci/config.yml
> VIDEO-8664 | Removing framework tests

- CHANGELOG.md
> Update doc link

- CHANGELOG.md
- README.md
- lib/signaling/v2/peerconnection.js
- test/unit/spec/signaling/v2/peerconnection.js
> prepare for release 2.20.1

- .circleci/images/chrome/beta/Dockerfile
- .circleci/images/chrome/stable/Dockerfile
- .circleci/images/chrome/unstable/Dockerfile
* VIDEO-8647 Fixing docker images build for Chrome
> VIDEO-8647 - Fixing Chrome Docker Image

- lib/signaling/v2/twilioconnectiontransport.js
- lib/util/index.js
- test/unit/spec/signaling/v2/twilioconnectiontransport.js
Changes:
1. Set RSP version to 3.
2. Always request track_subscriptions MSP.
> VIDEO-8868 Connect to a RSP v3 Room (Large Room)

- COMMON_ISSUES.md
This PR is just for adding the Android 11 issue as well as some relevant links.
> Adding known Android 11 issue and relevant links

- CHANGELOG.md
- COMMON_ISSUES.md
Prep 2.21.1 RC, adding in CHANGELOG entry and updating develop branch with the most recent updates on master.
Also noticed some dashes missing on the last entry so fixed that up as well.
> Prep for 2.21.1 RC

- CHANGELOG.md
- README.md
- package.json
> merge master

- CHANGELOG.md
- lib/media/track/localdatatrack.js
- lib/media/track/remoteaudiotrack.js
- lib/media/track/remotedatatrack.js
- lib/media/track/remotetrackpublication.js
- lib/media/track/remotevideotrack.js
- lib/media/track/videotrack.js
- test/unit/spec/media/track/remotevideotrack.js
- test/unit/spec/media/track/videotrack.js
- test/unit/spec/remoteparticipant.js
- test/unit/spec/signaling/v3/tracksubscriptionssignaling.js
This PR contains changes for the following tickets:
- [VIDEO-8745](https://issues.corp.twilio.com/browse/VIDEO-8745)
- [VIDEO-8746](https://issues.corp.twilio.com/browse/VIDEO-8746)
- [VIDEO-8747](https://issues.corp.twilio.com/browse/VIDEO-8747)
- [VIDEO-8748](https://issues.corp.twilio.com/browse/VIDEO-8748)
> [Large Rooms] RemoteVideoTrack switch on/off and subscriptions

- lib/signaling/v3/remoteparticipant.js
- lib/signaling/v3/room.js
- lib/signaling/v3/tracksubscriptionssignaling.js
- test/unit/spec/signaling/v3/room.js
- test/unit/spec/signaling/v3/tracksubscriptionssignaling.js
Update the `track_subscriptions` MSP parser to handle DataTrack subscriptions. Based on https://code.hq.twilio.com/client/room-signaling-protocol/pull/85
> VIDEO-9374 Update track_subscriptions MSP parser to handle DataTrack subscriptions.

- lib/media/track/mediatrack.js
- test/env.js
- test/integration/spec/connect.js
- test/integration/spec/remotetracks.js
- test/lib/defaults.js
- test/lib/rest.js
- test/lib/util.js
Integration tests for n-loudest audio based on this [test plan](https://docs.google.com/document/d/1KUqexjewqyKDnonho5EEfyYg1kTFo9xrmSdwaUDZeXs/edit?usp=sharing).
> VIDE0-9660 n-loudest audio integration tests

- CHANGELOG.md
- lib/localparticipant.js
- lib/media/track/remoteaudiotrack.js
- lib/media/track/remoteaudiotrackpublication.js
- lib/media/track/remotemediatrack.js
- lib/media/track/remotetrackpublication.js
- lib/media/track/remotevideotrack.js
- lib/media/track/remotevideotrackpublication.js
- lib/participant.js
- lib/signaling/remotetrackpublication.js
- lib/signaling/v2/remotetrackpublication.js
- lib/signaling/v3/remotetrackpublication.js
- lib/util/index.js
- test/unit/spec/media/track/remotemediatrack.js
- test/unit/spec/media/track/remotetrackpublication.js
- test/unit/spec/remoteparticipant.js
This PR implements the following changes requested in this [JIRA ticket comment](https://issues.corp.twilio.com/browse/VIDEO-9760?focusedCommentId=4167889&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-4167889).
> VIDEO-9760 remove enabled deprecation for v2

- lib/index.ts
- tsdef/index.d.ts
- tsdef/twilio-video-tests.ts
- tsdef/types.d.ts
Exposing TwilioWarning that way developers can also do 
```js
import { connect, TwilioWarning } from 'twilio-video';
const room = await connect('token', {
notifyWarnings: [TwilioWarning.recordingMediaLost]
// Other connect options
});
```
> Exposing twilio warning

- CHANGELOG.md
- lib/util/browserdetection.js
- lib/util/constants.js
- lib/util/index.js
- lib/util/insightspublisher/index.js
- test/unit/spec/util/browserdetection.js
- test/unit/spec/util/index.js
- test/unit/spec/util/insightspublisher.js
JIRA Ticket : [VIDEO-8282](https://issues.corp.twilio.com/browse/VIDEO-8282)
Adding in iPad detection function to send to insights.
> VIDEO-8282 - Adding iPad Detection

- tsdef/twilio-video-tests.ts
- tsdef/types.d.ts
small update for https://github.com/twilio/twilio-video.js/pull/1783 - Added new types in `types.d.ts`
> add typescript definition for new property

- README.md
Updating CDN Link in the readme
> Fix CDN Link in readme

- CHANGELOG.md
- README.md
- package.json
Merge from master PR
Keeping changes from 2.21.2-rc3, updating the changelog and readme.
> Merge from master

- CHANGELOG.md
- lib/connect.js
- lib/localparticipant.js
- lib/media/track/localtrackpublication.js
- lib/room.js
- lib/util/twiliowarning.js
- tsdef/LocalParticipant.d.ts
- tsdef/LocalTrackPublication.d.ts
- tsdef/Room.d.ts
- tsdef/TwilioWarning.d.ts
- tsdef/index.d.ts
- tsdef/twilio-video-tests.ts
- tsdef/types.d.ts
- Mentioning some possible causes of the warnings in the API docs
- Removing public references of TwilioWarning as this created confusion to some folks. See [thread](https://twilio.slack.com/archives/C031MM5GY69/p1654021970923649). TwilioWarning will mean more in the future so removing it for now.
> VIDEO-10366 Update docs

- COMMON_ISSUES.md
Adding iOS 15 bug on common issues page. See [VIDEO-10004](https://issues.corp.twilio.com/browse/VIDEO-10004) for details
> VIDEO-10004 iOS 15 echo in common issues

- lib/noisecancellationadapter.ts
Updates krisp version to 2.1.0
> use krisp version 2.1.0

- lib/signaling/v2/peerconnection.js
> VIDEO-10551 Ensure encodings object exists before modifying priority.

- lib/signaling/v3/room.js
> VIDEO-10707 Remove initially switched off warning.

- lib/media/track/videotrack.js
> VIDEO-10772 Make sure .mediaStreamTrack exists before accessing .enabled property.

- CHANGELOG.md
- README.md
> Prep for 3.0.0-preview.1

- CHANGELOG.md
- lib/util/support.js
- lib/webrtc/util/sdp.js
- test/lib/mockwebrtc.js
- test/unit/spec/util/support.js
> Merge 2.22.2 release from master

- CHANGELOG.md
> changelog update for 2.23.1-rc2

- CHANGELOG.md
- README.md
- package.json
> Prep for 3.0.0-preview.2

- CHANGELOG.md
- lib/media/track/localvideotrack.js
Fix for github issue:  https://github.com/twilio/twilio-video.js/issues/1863
> VIDEO-11263 Make sure the dummy element is not null before pausing it.

- CHANGELOG.md
- tsdef/LocalTrackOptions.d.ts
Fix for GitHub issue: https://github.com/twilio/twilio-video.js/issues/1826
> VIDEO-11659 Make LocalTrackOptions property logLevel optional.

- CHANGELOG.md
- README.md
> Prep for 3.0.0-preview.3.

- CHANGELOG.md
- lib/signaling/v2/peerconnection.js
- test/unit/spec/signaling/v2/peerconnection.js
Fix for #1857 (and potentially #1856).
> VIDEO-11516 Updating encodings only if width and height are present in MST settings.

- .circleci/config.yml
- .circleci/images/firefox/beta/Dockerfile
- .circleci/images/firefox/stable/Dockerfile
- .circleci/images/firefox/unstable/Dockerfile
JIRA: [VIDEO-7732](https://issues.corp.twilio.com/browse/VIDEO-7732)
This PR fixes our firefox image build job.
> VIDEO-7732 - Fix Firefox Docker Image

- CHANGELOG.md
- lib/createlocaltrack.js
- lib/createlocaltracks.ts
- lib/media/track/localaudiotrack.js
- lib/media/track/localmediatrack.js
- lib/media/track/localvideotrack.js
- lib/media/track/mediatrack.js
- lib/media/track/remotemediatrack.js
- lib/util/browserdetection.js
- test/lib/fakemediastream.js
- test/unit/spec/createlocaltrack.js
- test/unit/spec/createlocaltracks.ts
- test/unit/spec/media/track/localaudiotrack.js
- tsdef/index.d.ts
- tsdef/types.d.ts
* [Proposal](https://docs.google.com/document/d/1gbCP9PwcCHbf0472bwaYtk2iJK_NbhQ1tcYlXGE414k/edit#heading=h.niibyagv52y1)
* [IDL changes](https://code.hq.twilio.com/client/video-sdk-api/pull/103)
> VIDEO-11701 Default Device Capture Mode

- CHANGELOG.md
- lib/media/track/localaudiotrack.js
> VIDEO-11859 Select the actual default device ID instead of "default" (Chrome).

- package.json
- test/integration/spec/bandwidthprofile/regressions.js
- test/integration/spec/bandwidthprofile/video.js
- test/integration/spec/localtrackpublication.js
- test/integration/spec/remotetracks.js
- test/integration/spec/room.js
- test/integration/spec/webrtc/rtcpeerconnection.js
- test/lib/util.js
- test/umd/index.js
> VIDEO-10693, VIDEO-10686 [Firefox] Fixing BWP, regression, and Room.on("dominantSpeakerChanged") tests.

- package.json
- test/integration/spec/bandwidthprofile/regressions.js
- test/integration/spec/bandwidthprofile/video.js
- test/integration/spec/localtrackpublication.js
- test/integration/spec/remotetracks.js
- test/integration/spec/room.js
- test/integration/spec/webrtc/rtcpeerconnection.js
- test/lib/util.js
VIDEO-10693, VIDEO-10686 [Firefox] Fixing BWP, regression, and Room.on("dominantSpeakerChanged") tests. (#1925)
* VIDEO-10693 [Firefox] Fixing BWP and regression tests.
* VIDEO-10686 Potential fix for Room "dominantSpeakerChanged" event tests.
* Disabling AudioContext test on Firefox, since it always fails due to a bug.
* Updating puppeteer to fix UMD test.
* Removing createSyntheticAudioStreamTrack().
> Merge feature/green-builds to develop.

- CHANGELOG.md
- README.md
> Prep for 2.25.0.

- lib/webrtc/rtcsessiondescription/chrome.js
Changes regarding function prototype -> class syntax + vars -> const/let statements
> ChromeRTCSessionDescription ES6 class syntax

- CHANGELOG.md
- lib/media/track/localaudiotrack.js
- lib/media/track/localmediatrack.js
- lib/media/track/localvideotrack.js
- lib/media/track/sender.js
- lib/room.js
- lib/transceiver.js
- test/lib/fakemediastream.js
- test/unit/spec/media/track/localmediatrack.js
- test/unit/spec/media/track/sender.js
- tsdef/LocalAudioTrack.d.ts
- tsdef/LocalVideoTrack.d.ts
- tsdef/Room.d.ts
This PR implements the following [proposal](https://docs.google.com/document/d/1hVDcsMLAAEL2uuES5Dzl6KXRtnqMDt-5hxZBd8u9kW0/edit?usp=sharing) for working around [VIDEO-11360](https://issues.corp.twilio.com/browse/VIDEO-11360).
> VIDEO-11360 LocalMediaTrack.isMuted and Room.refreshInactiveMedia.

- lib/webrtc/rtcpeerconnection/safari.js
Syntax changes to changing public properties into getters, ${} string variable formatting, concise arrow functions, object/array destructuring, and removing references to self and arguments
> SafariRTCPeerConnection es6 syntax

- lib/webrtc/getstats.js
Declaring default values in function declaration, object/array destructuring, concise require statements
> getStats es6 syntax

- lib/webrtc/getstats.js
Split require statements into util to and util/sdp
> split require statements for util

- lib/twilioconnection.js
- test/integration/spec/docker/reconnection.js
- test/integration/spec/localparticipant/networkqualitylevel.js
Update master branch with develop test fix
> Update Master with VIDEO-10700

- CHANGELOG.md
- tsdef/index.d.ts
> VIDEO-12383 Fix createLocalAudioTrack() type definition

- CHANGELOG.md
- lib/webrtc/getstats.js
- test/integration/spec/webrtc/getstats.js
- tsdef/AudioTrack.d.ts
- tsdef/MediaTrack.d.ts
- tsdef/VideoTrack.d.ts
- tsdef/index.d.ts
- tsdef/twilio-video-tests.ts
* Fix for #1968.
* Fix for #1960.
> VIDEO-12411 [Chrome 112+][Room.getStats()] Read from RTCMediaSourceStats instead of RTCMediaStreamTrackStats

- CHANGELOG.md
- lib/connect.js
- lib/webrtc/getstats.js
- lib/webrtc/util/index.js
- test/lib/mockwebrtc.js
- test/unit/spec/util/support.js
- test/unit/spec/webrtc/getstats.js
- test/unit/spec/webrtc/util/index.js
> VIDEO-12534 and VIDEO-12494

- CHANGELOG.md
- README.md
- lib/media/track/localmediatrack.js
- lib/media/track/localvideotrack.js
- lib/media/track/remotevideotrack.js
- lib/media/track/videoprocessoreventobserver.js
- lib/media/track/videotrack.js
- package.json
- test/unit/spec/media/track/videoprocessoreventobserver.js
- test/unit/spec/media/track/videotrack.js
- tsdef/VideoProcessor.d.ts
- tsdef/VideoTrack.d.ts
- tsdef/index.d.ts
- tsdef/types.d.ts
> Prep for 2.27.0.

- lib/localparticipant.js
- package.json
> VIDEO-12972 Update LocalParticipant#trackPublished event documentation.

- CHANGELOG.md
- lib/media/track/localmediatrack.js
- lib/media/track/localvideotrack.js
- lib/util/index.js
- test/integration/spec/preflight.js
> VIDEO-13012,VIDEO-13013 iOS 17 beta bug fixes

- CHANGELOG.md
- README.md
- lib/media/track/localmediatrack.js
- lib/media/track/localvideotrack.js
- lib/util/index.js
- package.json
- test/integration/spec/preflight.js
> Prep for 2.28.0

- CHANGELOG.md
- lib/media/track/localaudiotrack.js
> VIDEO-13010 Enable auto default device capture mode for iOS LocalAudioTracks with Noise Cancellation.

- README.md
> Change the EOL year to 2026

- CHANGELOG.md
- lib/media/track/videotrack.js
> VBLOCKS-3643 VBLOCKS-3644 Support bitmaprenderer context for all browsers

- CHANGELOG.md
- LICENSE.md
> Prep for 2.29.0-beta.1

- CHANGELOG.md
- README.md
- tsdef/VideoProcessor.d.ts
- tsdef/types.d.ts
docs: introduce beta support for Video Processor V3
> docs: introduce beta support for Video Processor V3

- lib/participant.js
- lib/room.js
- lib/signaling/v2/peerconnection.js
- tsdef/twilio-video-tests.ts
- tsdef/types.d.ts
- [VBLOCKS-4043](https://twilio-engineering.atlassian.net/browse/VBLOCKS-4043)
- add support for custom MediaStream implementation in connect options
> [VBLOCKS-4043] feat: add support for custom MediaStream implementation

- lib/util/index.js
- test/unit/spec/media/track/mediatrack.js
- test/unit/spec/util/index.js
- [VBLOCKS-3979](https://twilio-engineering.atlassian.net/browse/VBLOCKS-3979)
Add insights regarding the usage of WebRTC redirections
> [VBLOCKS-3979] Add WebRTC redirection insights 

- CHANGELOG.md
- lib/connect.js
- lib/createlocaltracks.ts
> VBLOCKS-4369 Changelog and API docs for VDI

- CHANGELOG.md
- README.md
- Update the Changelog to set the release date for version 2.30.0
- Update the CDN link in the README
> doc: Update changelog and README for version 2.30.0

- README.md
Adding api token with scope=badge only from circleci.
> doc: Fix CI badge

- CHANGELOG.md
- lib/media/track/remotevideotrack.js
- test/unit/spec/media/track/remotevideotrack.js
Support for documentPictureInPicture
> VBLOCKS-4212 documentPictureInPicture support

- .release.json
> Fix build - adding lock file

- package-lock.json
- package.json
Set the minimum Node.js version to the current LTS. This clarifies the development environment requirements for contributors and CI tools without affecting the library's functionality.
> chore: update minimum Node.js version to 22

- CHANGELOG.md
Update the changelog with the new real-time transcription feature.
Note for the future: Update documentation link placeholder.
> [VBLOCKS-4694] realtime transcription changelog

- lib/insights/computepressuremonitor.js
- test/unit/spec/util/computepressuremonitor.js
- Created a simple computed pressure monitor based on the Compute Pressure API
- Added unit tests and an example usage of the designed API for review
> [VBLOCKS-5005] feat: add Compute Pressure monitor

- lib/connect.js
- lib/createlocaltracks.ts
- lib/insights/mediastreameventpublisher.js
- lib/util/eventobserver.js
- test/integration/spec/getusermediaevents.js
- test/unit/spec/insights/mediastreameventpublisher.js
- Publish the get-user-media events to the Insights backend using MediaStreamEventPublisher.
> [VBLOCKS-5064] feat: implement MediaStreamEventPublisher for getUserMedia

- lib/insights/computepressuremonitor.js
- lib/insights/networkeventpublisher.js
- lib/insights/resourceeventpublisher.js
- lib/room.js
- lib/util/index.js
- test/unit/spec/util/computepressuremonitor.js
- Update the network monitoring to use the correct types.
- Refactor the ComputePressureMonitor.
- Simplify ComputePressureMonitor unit tests.
> [VBLOCKS-5305] Adjust insights typings

- .circleci/config.yml
Adding Healthcheck workflow that tests for group rooms.
> VBLOCKS-4945 Healthcheck workflow

- CHANGELOG.md
Document Advanced Insights changes in the `CHANGELOG.md`
> doc: add entry to the changelog for Advanced Insights
